/*
 * 服务用语词库 — 在此追加 phrases 条目
 * 必填: chinese, lang, text, meaning, ipa, katakana, romanization, scenario, knowledge, derived
 * 可选: audioFile (mp3 路径，有则优先播放)
 */

const LANGUAGES = [
  { id: "ko", name: "🇰🇷 韩语（한국어）", lang: "ko-KR", enabled: true },
  { id: "yue", name: "🇭🇰 粤语（廣東話）", lang: "zh-HK", enabled: false },
  { id: "en", name: "🇺🇸 英语（English）", lang: "en-US", enabled: true },
  { id: "de", name: "🇩🇪 德语（Deutsch）", lang: "de-DE", enabled: true },
  { id: "fr", name: "🇫🇷 法语（Français）", lang: "fr-FR", enabled: true },
  { id: "es", name: "🇪🇸 西班牙语（Español）", lang: "es-ES", enabled: true },
  { id: "it", name: "🇮🇹 意大利语（Italiano）", lang: "it-IT", enabled: true },
  { id: "ru", name: "🇷🇺 俄语（Русский）", lang: "ru-RU", enabled: true },
  { id: "ar", name: "🇸🇦 阿拉伯语（العربية）", lang: "ar-SA", enabled: true },
  { id: "th", name: "🇹🇭 泰语（ไทย）", lang: "th-TH", enabled: false },
  { id: "pt", name: "🇵🇹 葡萄牙语（Português）", lang: "pt-BR", enabled: true },
  { id: "he", name: "🇮🇱 希伯来语（עברית）", lang: "he-IL", enabled: true }
];

    /*
     * phrases 数组 — 追加新条目只需 push 同结构对象
     * 必填: chinese, lang, text, meaning, ipa, katakana, romanization, scenario, knowledge, derived
     * 可选: audioFile (mp3 路径，有则优先播放)
     */


const phrases = [
     // ── 您好 ──
{
  chinese: "您好",
  lang: "ko",
  text: "안녕하세요",
  meaning: "您好 / 你好（礼貌问候）",
  ipa: "/an.njʌŋ.ha.se.jo/",
  katakana: "アンニョンハセヨ",
  romanization: "annyeonghaseyo",
  audioFile: null,
  scenario: "面对客人、接待、电话开头等场合都可以使用。早中晚基本通用，是最安全的韩语礼貌问候。",
  knowledge: "「안녕하세요」是日常最常用的礼貌问候。比「안녕」正式，适合对顾客、长辈、上司、初次见面的人使用。服务场合通常用这句即可。",
  derived: [
    { text: "안녕하십니까", meaning: "更正式、更郑重的问候，多用于广播、正式讲话、非常正式的接待场合" },
    { text: "반갑습니다", meaning: "见到您很高兴 / 幸会" }
  ],
  status: "reviewed"
},
{
  chinese: "您好",
  lang: "yue",
  text: "您好",
  meaning: "您好（正式问候）",
  ipa: "/nei5 hou2/",
  katakana: "ネイホウ",
  romanization: "nei5 hou2",
  audioFile: null,
  scenario: "粤语区服务场合可用，适合酒店、餐厅、商场等正式接待。实际口语中「你好」也很常见。",
  knowledge: "粤语里「您好」比「你好」更郑重，但日常服务现场并不一定频繁使用。若想自然一点，也可以使用「你好」。",
  derived: [
    { text: "你好", meaning: "你好，较自然通用" },
    { text: "早晨", meaning: "早上好，粤语中非常常用" }
  ],
  status: "reviewed"
},
{
  chinese: "您好",
  lang: "en",
  text: "Hello",
  meaning: "您好 / 你好",
  ipa: "/həˈloʊ/",
  katakana: "ハロー",
  romanization: "hello",
  audioFile: null,
  scenario: "通用问候，适用于酒店前台、餐厅、电话接听等场合。",
  knowledge: "服务业中可用 Hello 作为开场。若想更有服务感，可接一句 “How may I help you?”。早上、下午、晚上也可分别使用 Good morning / Good afternoon / Good evening。",
  derived: [
    { text: "Good morning", meaning: "早上好" },
    { text: "How may I help you?", meaning: "请问有什么可以帮您？" }
  ],
  status: "reviewed"
},
{
  chinese: "您好",
  lang: "de",
  text: "Guten Tag",
  meaning: "您好 / 日安",
  ipa: "/ˈɡuːtn̩ taːk/",
  katakana: "グーテンターク",
  romanization: "Guten Tag",
  audioFile: null,
  scenario: "白天正式问候，适用于酒店、商店、银行等服务场合。",
  knowledge: "字面意为「美好的一天」。早晨用 Guten Morgen，傍晚或晚上用 Guten Abend。",
  derived: [
    { text: "Guten Morgen", meaning: "早上好" },
    { text: "Guten Abend", meaning: "晚上好" }
  ],
  status: "reviewed"
},
{
  chinese: "您好",
  lang: "fr",
  text: "Bonjour",
  meaning: "您好 / 日安",
  ipa: "/bɔ̃.ʒuʁ/",
  katakana: "ボンジュール",
  romanization: "bonjour",
  audioFile: null,
  scenario: "进入店铺、餐厅、酒店前台或开始对话时的标准问候。",
  knowledge: "法语服务场景中 Bonjour 非常重要。傍晚或晚上可用 Bonsoir。Bienvenue 是「欢迎」，但不一定适合作为最普通的开场问候。",
  derived: [
    { text: "Bonsoir", meaning: "晚上好" },
    { text: "Enchanté(e)", meaning: "幸会 / 很高兴认识您" }
  ],
  status: "reviewed"
},
{
  chinese: "您好",
  lang: "es",
  text: "Hola",
  meaning: "您好 / 你好",
  ipa: "/ˈola/",
  katakana: "オラ",
  romanization: "hola",
  audioFile: null,
  scenario: "西班牙语中最通用的问候，服务场合也可以使用。若根据时间更正式表达，可用 Buenos días / Buenas tardes / Buenas noches。",
  knowledge: "原来的 Buenos días 更准确对应「早上好」。如果中文词条是「您好」，Hola 更通用；如果是「早上好」，则应使用 Buenos días。",
  derived: [
    { text: "Buenos días", meaning: "早上好" },
    { text: "¿En qué puedo ayudarle?", meaning: "请问有什么可以帮您？" }
  ],
  status: "reviewed"
},
{
  chinese: "您好",
  lang: "it",
  text: "Buongiorno",
  meaning: "您好 / 日安",
  ipa: "/bwɔnˈdʒorno/",
  katakana: "ブオンジョルノ",
  romanization: "buongiorno",
  audioFile: null,
  scenario: "白天正式问候，进入商店、酒店前台或开始服务时使用。",
  knowledge: "傍晚或晚上改用 Buonasera。Ciao 较随意，不建议对初次见面的客人使用。",
  derived: [
    { text: "Buonasera", meaning: "晚上好" },
    { text: "Salve", meaning: "您好，介于正式与随意之间" }
  ],
  status: "reviewed"
},
{
  chinese: "您好",
  lang: "ru",
  text: "Здравствуйте",
  meaning: "您好",
  ipa: "/ˈzdrastvʊjtʲe/",
  katakana: "ズドラーストヴィチェ",
  romanization: "zdravstvuyte",
  audioFile: null,
  scenario: "对陌生人、顾客、长辈使用的正式问候，适合服务业。",
  knowledge: "这是正式问候。对熟人或朋友可用 Привет，但不适合服务场合。",
  derived: [
    { text: "Добрый день", meaning: "日安 / 下午好" },
    { text: "Доброе утро", meaning: "早上好" }
  ],
  status: "reviewed"
},
{
  chinese: "您好",
  lang: "ar",
  text: "مرحباً",
  meaning: "您好 / 你好",
  ipa: "/ˈmar.ħa.ban/",
  katakana: "マルハバン",
  romanization: "marḥaban",
  audioFile: null,
  scenario: "阿拉伯语中较通用的问候，适合酒店、餐厅等服务场合。比宗教色彩较强的问候更中性。",
  knowledge: "السلام عليكم 是非常常见且礼貌的问候，尤其在穆斯林文化圈中使用广泛。但作为面向各国客人的酒店服务学习词条，مرحباً 更中性、更容易使用。",
  derived: [
    { text: "السلام عليكم", meaning: "愿平安归于您，常见正式问候" },
    { text: "أهلاً وسهلاً", meaning: "欢迎 / 欢迎您" }
  ],
  status: "reviewed"
},
{
  chinese: "您好",
  lang: "th",
  text: "สวัสดีครับ/ค่ะ",
  meaning: "您好",
  ipa: "/sa.wat.diː kʰráp/ / /sa.wat.diː kʰâː/",
  katakana: "サワッディー・クラップ / サワッディー・カー",
  romanization: "sawatdee khrap / sawatdee kha",
  audioFile: null,
  scenario: "泰国服务业最常用问候。男性说 ครับ，女性说 ค่ะ。",
  knowledge: "ครับ / ค่ะ 是礼貌结尾。你是男性的话，实际使用时应说 สวัสดีครับ。",
  derived: [
    { text: "สวัสดี", meaning: "你好，省略礼貌结尾后较随意" },
    { text: "ยินดีต้อนรับ", meaning: "欢迎" }
  ],
  status: "reviewed"
},
{ chinese: "您好", lang: "pt", text: "Olá", meaning: "您好 / 你好", ipa: "/oˈla/", katakana: "オラ", romanization: "olá", audioFile: null, scenario: "通用问候，适用于酒店前台、玄关、餐厅及一般接待场合。", knowledge: "「Olá」是葡萄牙语最通用的问候。酒店服务中根据时段使用「Bom dia」「Boa tarde」「Boa noite」通常更有礼貌、更自然。本词库的 TTS 统一采用巴西葡萄牙语 pt-BR。", derived: [{ text: "Bom dia", meaning: "早上好 / 上午好", ipa: "/bõ ˈdʒi.ɐ/", katakana: "ボン・ジーア", romanization: "bom dia", audioFile: null }, { text: "Boa tarde", meaning: "下午好", ipa: "/ˈbo.ɐ ˈtaʁ.dʒi/", katakana: "ボア・タルジ", romanization: "boa tarde", audioFile: null }, { text: "Boa noite", meaning: "晚上好 / 晚安", ipa: "/ˈbo.ɐ ˈnoj.tʃi/", katakana: "ボア・ノイチ", romanization: "boa noite", audioFile: null }], status: "reviewed" },
{ chinese: "您好", lang: "he", text: "שלום", meaning: "您好 / 你好", ipa: "/ʃaˈlom/", katakana: "シャローム", romanization: "shalom", audioFile: null, scenario: "现代希伯来语中最通用的问候，适用于酒店前台、玄关、餐厅及一般接待场合。", knowledge: "「שלום」字面与「和平」有关，同时可以表示你好和再见，不需要根据客人的性别变化。正式服务中也可根据时段使用「בוקר טוב」或「ערב טוב」。", derived: [{ text: "בוקר טוב", meaning: "早上好", ipa: "/ˈbo.ker tov/", katakana: "ボケル・トヴ", romanization: "boker tov", audioFile: null }, { text: "ערב טוב", meaning: "晚上好", ipa: "/ˈe.rev tov/", katakana: "エレヴ・トヴ", romanization: "erev tov", audioFile: null }, { text: "ברוכים הבאים", meaning: "欢迎各位（男性或男女混合群体）", ipa: "/bruˈxim ha.baˈim/", katakana: "ブルヒーム・ハバイーム", romanization: "brukhim haba'im", audioFile: null }], status: "reviewed" },
 // ── 早上好 ──
{ chinese: "早上好", lang: "ko", text: "안녕하세요", meaning: "早上好 / 您好（韩语早晨也使用）", ipa: "/an.njʌŋ.ha.se.jo/", katakana: "アンニョンハセヨ", romanization: "annyeonghaseyo", audioFile: null, scenario: "韩语没有像英语 Good morning 那样日常必用的时间限定问候。酒店早餐、早班接待和面对顾客时，早晨通常仍说「안녕하세요」。", knowledge: "「좋은 아침입니다」字面是「早上好」，语法正确，但在韩国日常服务场景中不如「안녕하세요」自然。", derived: [{ text: "좋은 아침입니다", meaning: "早上好，字面对应表达，但日常使用频率较低", ipa: "/tɕo.ɯn a.tɕʰim.im.ni.da/", katakana: "チョウン・アチミムニダ", romanization: "joeun achimimnida", audioFile: null }, { text: "굿모닝", meaning: "Good morning 的外来语说法，较轻松随意", ipa: "/kun.mo.niŋ/", katakana: "グンモニン", romanization: "gunmoning", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "yue", text: "早晨", meaning: "早上好", ipa: "/tsou̯² sɐn⁴/", katakana: "ゾウサン", romanization: "zou2 san4", audioFile: null, scenario: "粤语中非常自然的上午问候，适合酒店早餐、早班接待、餐厅及日常交流。", knowledge: "「早晨」是粤语最常见的早晨问候。也可以只说「早」，但语气更简短、随意。", derived: [{ text: "早", meaning: "早，更简短随意", ipa: "/tsou̯²/", katakana: "ゾウ", romanization: "zou2", audioFile: null }, { text: "早唞", meaning: "晚安，不是早上好；注意不要因「早」字而混淆", ipa: "/tsou̯² tʰɐu̯²/", katakana: "ゾウタウ", romanization: "zou2 tau2", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "en", text: "Good morning", meaning: "早上好", ipa: "/ˌɡʊd ˈmɔːr.nɪŋ/", katakana: "グッド・モーニング", romanization: "good morning", audioFile: null, scenario: "早晨面对客人时的标准礼貌问候，适合酒店前台、早餐服务、电话接听和送客前的交谈。", knowledge: "通常在中午以前使用，但具体切换时间并非严格固定。面对客人时建议使用完整的 Good morning，而不是只说 Morning。", derived: [{ text: "Morning", meaning: "早，省略式问候，较随意", ipa: "/ˈmɔːr.nɪŋ/", katakana: "モーニング", romanization: "morning", audioFile: null }, { text: "Good morning. How may I assist you?", meaning: "早上好，请问有什么可以为您效劳？", ipa: "/ˌɡʊd ˈmɔːr.nɪŋ | haʊ meɪ aɪ əˈsɪst juː/", katakana: "グッド・モーニング。ハウ・メイ・アイ・アシスト・ユー", romanization: "Good morning. How may I assist you?", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "de", text: "Guten Morgen", meaning: "早上好", ipa: "/ˈɡuːtn̩ ˈmɔʁɡn̩/", katakana: "グーテン・モルゲン", romanization: "Guten Morgen", audioFile: null, scenario: "早晨面对客人时的标准问候，适合酒店、餐厅、商店和早餐服务。", knowledge: "具体何时改用 Guten Tag 没有绝对统一的时间，通常随着上午推进而逐渐切换，不必严格限定为十点或十一点。", derived: [{ text: "Morgen", meaning: "早，简略且较随意", ipa: "/ˈmɔʁɡn̩/", katakana: "モルゲン", romanization: "Morgen", audioFile: null }, { text: "Guten Morgen. Wie kann ich Ihnen helfen?", meaning: "早上好，请问有什么可以帮您？", ipa: "/ˈɡuːtn̩ ˈmɔʁɡn̩ | viː kan ɪç ˈiːnən ˈhɛlfn̩/", katakana: "グーテン・モルゲン。ヴィー・カン・イヒ・イーネン・ヘルフェン", romanization: "Guten Morgen. Wie kann ich Ihnen helfen?", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "fr", text: "Bonjour", meaning: "早上好 / 您好 / 日安", ipa: "/bɔ̃.ʒuʁ/", katakana: "ボンジュール", romanization: "bonjour", audioFile: null, scenario: "从早晨到白天面对客人时使用，是酒店、餐厅、商店和日常交流中的标准问候。", knowledge: "法语通常不另设日常专用的「早上好」。Bonjour 从早晨开始使用，傍晚后逐渐改用 Bonsoir。", derived: [{ text: "Bonne matinée", meaning: "祝您上午愉快，通常在分别或结束服务时使用", ipa: "/bɔn ma.ti.ne/", katakana: "ボンヌ・マティネ", romanization: "bonne matinée", audioFile: null }, { text: "Bonjour, monsieur", meaning: "先生，您好 / 早上好", ipa: "/bɔ̃.ʒuʁ mə.sjø/", katakana: "ボンジュール・ムスィユー", romanization: "bonjour, monsieur", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "es", text: "Buenos días", meaning: "早上好", ipa: "/ˈbwe.nos ˈdi.as/", katakana: "ブエノス・ディアス", romanization: "buenos días", audioFile: null, scenario: "早晨面对客人时的标准礼貌问候，适用于酒店、餐厅、商店及电话接听。", knowledge: "西班牙及拉丁美洲都广泛使用。何时改用 Buenas tardes 会因地区和用餐习惯而不同，因此不建议把切换时间固定写成十四点。", derived: [{ text: "Muy buenos días", meaning: "早上好，语气更热情或更郑重", ipa: "/mui̯ ˈbwe.nos ˈdi.as/", katakana: "ムイ・ブエノス・ディアス", romanization: "muy buenos días", audioFile: null }, { text: "Buenos días. ¿En qué puedo ayudarle?", meaning: "早上好，请问有什么可以帮您？", ipa: "/ˈbwe.nos ˈdi.as | en ke ˈpwe.ðo a.ʝuˈðaɾ.le/", katakana: "ブエノス・ディアス。エン・ケ・プエド・アユダルレ", romanization: "Buenos días. ¿En qué puedo ayudarle?", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "it", text: "Buongiorno", meaning: "早上好 / 您好 / 日安", ipa: "/bwɔnˈdʒor.no/", katakana: "ブオンジョルノ", romanization: "buongiorno", audioFile: null, scenario: "早晨及白天面对客人时的标准问候，适合酒店早餐、前台、餐厅和商店。", knowledge: "Buongiorno 的使用范围不只限于早晨，也可延续到下午。何时改用 Buonasera 会因地区和个人习惯而不同，不宜固定为十七点。", derived: [{ text: "Buona giornata", meaning: "祝您今天愉快，通常在告别或结束服务时使用", ipa: "/ˈbwɔ.na dʒorˈna.ta/", katakana: "ブオナ・ジョルナータ", romanization: "buona giornata", audioFile: null }, { text: "Buongiorno, come posso aiutarla?", meaning: "早上好，请问有什么可以帮您？", ipa: "/bwɔnˈdʒor.no | ˈko.me ˈpɔs.so a.juˈtar.la/", katakana: "ブオンジョルノ。コメ・ポッソ・アイウタルラ", romanization: "Buongiorno, come posso aiutarla?", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "ru", text: "Доброе утро", meaning: "早上好", ipa: "/ˈdo.brə.jɪ ˈu.trə/", katakana: "ドーブラエ・ウートラ", romanization: "dobroye utro", audioFile: null, scenario: "早晨面对客人时的标准问候，适合酒店前台、早餐服务和餐厅。", knowledge: "这是中性表达，对不同性别和人数的客人都可以使用。随着时间进入白天，可改用「Добрый день」。", derived: [{ text: "Доброе утро. Чем могу помочь?", meaning: "早上好，请问有什么可以帮您？", ipa: "/ˈdo.brə.jɪ ˈu.trə | tɕem mɐˈɡu pɐˈmotɕ/", katakana: "ドーブラエ・ウートラ。チェム・マグー・パモーチ", romanization: "Dobroye utro. Chem mogu pomoch?", audioFile: null }, { text: "Добрый день", meaning: "您好 / 日安，白天使用", ipa: "/ˈdo.brɨj dʲenʲ/", katakana: "ドーブルィ・ジェーニ", romanization: "dobryy den", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "ar", text: "صباح الخير", meaning: "早上好", ipa: "/sˤa.baː.ħ‿al.xajr/", katakana: "サバーハル・ハイル", romanization: "ṣabāḥ al-khayr", audioFile: null, scenario: "阿拉伯语地区早晨常用的标准问候，适合酒店、餐厅、商店及日常交流。", knowledge: "对方常以「صباح النور」回应。不同地区的实际发音会略有差异，这里采用现代标准阿拉伯语的写法和近似读音。", derived: [{ text: "صباح النور", meaning: "光明的早晨，回应「صباح الخير」时常用", ipa: "/sˤa.baː.ħ‿an.nuːr/", katakana: "サバーハン・ヌール", romanization: "ṣabāḥ an-nūr", audioFile: null }, { text: "صباح الخير، كيف يمكنني مساعدتك؟", meaning: "早上好，请问有什么可以帮您？", ipa: "/sˤa.baː.ħ‿al.xajr | kaj.fa jum.ki.nu.niː mu.saː.ʕa.da.tuk/", katakana: "サバーハル・ハイル。カイファ・ユムキヌニー・ムサーアダトゥク", romanization: "ṣabāḥ al-khayr, kayfa yumkinunī musāʿadatuk?", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "th", text: "สวัสดีครับ/ค่ะ", meaning: "早上好 / 您好（泰语早晨也使用）", ipa: "/sà.wàt.diː kʰráp/ / /sà.wàt.diː kʰâː/", katakana: "サワッディー・クラップ / サワッディー・カー", romanization: "sawatdee khrap / sawatdee kha", audioFile: null, scenario: "泰语没有像英语一样必须在早晨使用的日常专用问候。酒店早餐和早班服务中，通常仍使用「สวัสดีครับ/ค่ะ」。", knowledge: "男性使用「ครับ」，女性使用「ค่ะ」。你本人实际使用时说「สวัสดีครับ」。", derived: [{ text: "สวัสดีตอนเช้าครับ/ค่ะ", meaning: "早上好，明确强调早晨，但日常使用不如单说「สวัสดีครับ/ค่ะ」自然", ipa: "/sà.wàt.diː tɔːn tɕʰáːw kʰráp/ / /sà.wàt.diː tɔːn tɕʰáːw kʰâː/", katakana: "サワッディー・トーンチャーオ・クラップ / カー", romanization: "sawatdee ton chao khrap / kha", audioFile: null }, { text: "อรุณสวัสดิ์", meaning: "早安，较书面、文学或正式，不是一般服务现场首选", ipa: "/ʔa.run sà.wàt/", katakana: "アルン・サワット", romanization: "arun sawat", audioFile: null }], status: "reviewed" },
{ chinese: "早上好", lang: "he", text: "בוקר טוב", meaning: "早上好", ipa: "/ˈbo.ker tov/", katakana: "ボケル・トヴ", romanization: "boker tov", audioFile: null, scenario: "早晨面对客人时使用，是现代希伯来语中最标准自然的晨间问候，适合酒店前台、早餐服务和餐厅接待。", knowledge: "「בוקר טוב」字面就是「早上好」，男女、单复数都可以直接使用，不需要改变形式。到了晚上则使用「ערב טוב」。", derived: [{ text: "בוקר טוב, ברוכים הבאים", meaning: "早上好，欢迎各位", ipa: "/ˈbo.ker tov | bruˈxim ha.baˈim/", katakana: "ボケル・トヴ、ブルヒーム・ハバイーム", romanization: "boker tov, brukhim haba'im", audioFile: null }, { text: "יום טוב", meaning: "祝您今天愉快 / 日安", ipa: "/jom tov/", katakana: "ヨム・トヴ", romanization: "yom tov", audioFile: null }], status: "reviewed" },
// ── 欢迎光临 ──
{ chinese: "欢迎光临", lang: "ko", text: "어서 오세요", meaning: "欢迎光临 / 欢迎您来", ipa: "/ʌ.sʌ o.se.jo/", katakana: "オソ・オセヨ", romanization: "eoseo oseyo", audioFile: null, scenario: "适合客人进入玄关、餐厅或接待场所时使用，是韩语服务业中自然且常见的固定欢迎语。", knowledge: "韩国服务现场通常直接说「어서 오세요」，不必每次都补充场所名称。需要正式介绍来馆地点时，可以使用「Hoshinoya Tokyo에 오신 것을 환영합니다」。", patterns: [{ scene: "玄关／前台", text: "안녕하세요. Hoshinoya Tokyo에 오신 것을 환영합니다.", meaning: "您好，欢迎来到 Hoshinoya Tokyo。", ipa: "/an.njʌŋ.ha.se.jo | ho.ɕi.no.ja to.kʲo.e o.ɕin kʌ.sɯl hwan.jʌŋ.ham.ni.da/", katakana: "アンニョンハセヨ。ホシノヤ・トーキョーエ・オシン・ゴスル・ファニョンハムニダ", romanization: "Annyeonghaseyo. Hoshinoya Tokyo-e osin geoseul hwanyeonghamnida.", audioFile: null }, { scene: "餐厅", text: "안녕하세요. 레스토랑에 오신 것을 환영합니다.", meaning: "您好，欢迎来到餐厅。", ipa: "/an.njʌŋ.ha.se.jo | ɾe.sɯ.tʰo.ɾaŋ.e o.ɕin kʌ.sɯl hwan.jʌŋ.ham.ni.da/", katakana: "アンニョンハセヨ。レストランエ・オシン・ゴスル・ファニョンハムニダ", romanization: "Annyeonghaseyo. Reseutorang-e osin geoseul hwanyeonghamnida.", audioFile: null }, { scene: "可替换模板", text: "{place}에 오신 것을 환영합니다.", meaning: "欢迎来到{场所}。将 {place} 替换为场所名称。", ipa: "/{place}.e o.ɕin kʌ.sɯl hwan.jʌŋ.ham.ni.da/", katakana: "［場所］エ・オシン・ゴスル・ファニョンハムニダ", romanization: "{place}-e osin geoseul hwanyeonghamnida.", audioFile: null }], derived: [{ text: "어서 들어오세요", meaning: "请进 / 快请进", ipa: "/ʌ.sʌ tɯ.ɾʌ.o.se.jo/", katakana: "オソ・トゥロオセヨ", romanization: "eoseo deureo-oseyo", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "yue", text: "歡迎嚟到 Hoshinoya Tokyo", meaning: "欢迎来到 Hoshinoya Tokyo", ipa: "/fuːn⁵⁵ jɪŋ²¹ lɐi̯²¹ tou̯³³ hoː.siː.noː.jaː toː.kʲoː/", katakana: "フーンイン・ライドウ・ホシノヤ・トーキョー", romanization: "fun1 jing4 lai4 dou3 Hoshinoya Tokyo", audioFile: null, scenario: "比单独朗读书面感较强的「歡迎光臨」更接近日常口头迎接。可在玄关、前台或正式接待时与「你好」「早晨」搭配使用。", knowledge: "粤语中的「歡迎光臨」能够理解，也常见于标语和广播；实际面对客人时，「你好／早晨＋歡迎嚟到……」通常更自然。", patterns: [{ scene: "玄关／前台", text: "你好，歡迎嚟到 Hoshinoya Tokyo。", meaning: "您好，欢迎来到 Hoshinoya Tokyo。", ipa: "/nei̯²³ hou̯³⁵ | fuːn⁵⁵ jɪŋ²¹ lɐi̯²¹ tou̯³³ hoː.siː.noː.jaː toː.kʲoː/", katakana: "ネイホウ。フーンイン・ライドウ・ホシノヤ・トーキョー", romanization: "nei5 hou2, fun1 jing4 lai4 dou3 Hoshinoya Tokyo.", audioFile: null }, { scene: "餐厅", text: "你好，歡迎嚟到餐廳。", meaning: "您好，欢迎来到餐厅。", ipa: "/nei̯²³ hou̯³⁵ | fuːn⁵⁵ jɪŋ²¹ lɐi̯²¹ tou̯³³ tsʰaːn⁵⁵ tʰɛŋ⁵⁵/", katakana: "ネイホウ。フーンイン・ライドウ・ツァーンテン", romanization: "nei5 hou2, fun1 jing4 lai4 dou3 caan1 teng1.", audioFile: null }, { scene: "可替换模板", text: "歡迎嚟到 {place}。", meaning: "欢迎来到{场所}。将 {place} 替换为场所名称。", ipa: "/fuːn⁵⁵ jɪŋ²¹ lɐi̯²¹ tou̯³³ {place}/", katakana: "フーンイン・ライドウ・［場所］", romanization: "fun1 jing4 lai4 dou3 {place}.", audioFile: null }], derived: [{ text: "請入嚟", meaning: "请进来，较口语", ipa: "/tsʰɪŋ²⁵ jɐp̚⁵ lɐi̯²¹/", katakana: "ツェン・ヤップ・ライ", romanization: "cing2 jap6 lai4", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "en", text: "Welcome to Hoshinoya Tokyo", meaning: "欢迎来到 Hoshinoya Tokyo", ipa: "/ˈwel.kəm tə ˌhoʊ.ʃiˈnoʊ.jə ˈtoʊ.ki.oʊ/", katakana: "ウェルカム・トゥ・ホシノヤ・トーキョー", romanization: "Welcome to Hoshinoya Tokyo", audioFile: null, scenario: "适合客人首次抵达玄关或前台时使用。根据时间在前面加 Good morning、Good afternoon 或 Good evening 会更自然。", knowledge: "客人已经入住、只是前往餐厅时，不必再次欢迎其来到整个酒店。此时更适合使用时段问候，并欢迎客人参加早餐或晚餐。", patterns: [{ scene: "玄关／前台", text: "Good afternoon. Welcome to Hoshinoya Tokyo.", meaning: "下午好，欢迎来到 Hoshinoya Tokyo。", ipa: "/ˌɡʊd ˌæf.tərˈnuːn | ˈwel.kəm tə ˌhoʊ.ʃiˈnoʊ.jə ˈtoʊ.ki.oʊ/", katakana: "グッド・アフタヌーン。ウェルカム・トゥ・ホシノヤ・トーキョー", romanization: "Good afternoon. Welcome to Hoshinoya Tokyo.", audioFile: null }, { scene: "餐厅／晚餐", text: "Good evening. Welcome to dinner at Hoshinoya Tokyo.", meaning: "晚上好，欢迎前来享用 Hoshinoya Tokyo 的晚餐。", ipa: "/ˌɡʊd ˈiːv.nɪŋ | ˈwel.kəm tə ˈdɪn.ər æt ˌhoʊ.ʃiˈnoʊ.jə ˈtoʊ.ki.oʊ/", katakana: "グッド・イーブニング。ウェルカム・トゥ・ディナー・アット・ホシノヤ・トーキョー", romanization: "Good evening. Welcome to dinner at Hoshinoya Tokyo.", audioFile: null }, { scene: "可替换模板", text: "Welcome to {place}.", meaning: "欢迎来到{场所}。将 {place} 替换为场所或活动名称。", ipa: "/ˈwel.kəm tə {place}/", katakana: "ウェルカム・トゥ・［場所］", romanization: "Welcome to {place}.", audioFile: null }], derived: [{ text: "It’s a pleasure to welcome you", meaning: "很荣幸欢迎您的到来", ipa: "/ɪts ə ˈpleʒ.ər tə ˈwel.kəm juː/", katakana: "イッツ・ア・プレジャー・トゥ・ウェルカム・ユー", romanization: "It’s a pleasure to welcome you", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "de", text: "Herzlich willkommen im Hoshinoya Tokyo", meaning: "欢迎来到 Hoshinoya Tokyo", ipa: "/ˈhɛʁt͡slɪç ˈvɪlkɔmən ɪm hoːʃinoːja ˈtoːkio/", katakana: "ヘルツリヒ・ヴィルコメン・イム・ホシノヤ・トーキョー", romanization: "Herzlich willkommen im Hoshinoya Tokyo", audioFile: null, scenario: "适合客人首次到达玄关、前台或正式迎宾场合。通常可先加 Guten Morgen、Guten Tag 或 Guten Abend。", knowledge: "德语的欢迎表达常与时段问候组合使用。酒店名称前使用 im，餐厅场景则可使用 in unserem Restaurant 或 im Restaurant des Hoshinoya Tokyo。", patterns: [{ scene: "玄关／前台", text: "Guten Tag. Herzlich willkommen im Hoshinoya Tokyo.", meaning: "您好，欢迎来到 Hoshinoya Tokyo。", ipa: "/ˈɡuːtn̩ taːk | ˈhɛʁt͡slɪç ˈvɪlkɔmən ɪm hoːʃinoːja ˈtoːkio/", katakana: "グーテン・ターク。ヘルツリヒ・ヴィルコメン・イム・ホシノヤ・トーキョー", romanization: "Guten Tag. Herzlich willkommen im Hoshinoya Tokyo.", audioFile: null }, { scene: "餐厅", text: "Guten Abend. Herzlich willkommen im Restaurant des Hoshinoya Tokyo.", meaning: "晚上好，欢迎来到 Hoshinoya Tokyo 的餐厅。", ipa: "/ˈɡuːtn̩ ˈaːbn̩t | ˈhɛʁt͡slɪç ˈvɪlkɔmən ɪm ʁɛstoˈʁɑ̃ː deːs hoːʃinoːja ˈtoːkio/", katakana: "グーテン・アーベント。ヘルツリヒ・ヴィルコメン・イム・レストラン・デス・ホシノヤ・トーキョー", romanization: "Guten Abend. Herzlich willkommen im Restaurant des Hoshinoya Tokyo.", audioFile: null }, { scene: "可替换模板", text: "Herzlich willkommen in {place}.", meaning: "欢迎来到{场所}。冠词与介词有时需随场所调整。", ipa: "/ˈhɛʁt͡slɪç ˈvɪlkɔmən ɪn {place}/", katakana: "ヘルツリヒ・ヴィルコメン・イン・［場所］", romanization: "Herzlich willkommen in {place}.", audioFile: null }], derived: [{ text: "Schön, dass Sie da sind", meaning: "很高兴您能来", ipa: "/ʃøːn das ziː daː zɪnt/", katakana: "シェーン・ダス・ズィー・ダー・ズィント", romanization: "Schön, dass Sie da sind", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "fr", text: "Bienvenue au Hoshinoya Tokyo", meaning: "欢迎来到 Hoshinoya Tokyo", ipa: "/bjɛ̃.və.ny o ho.ʃi.no.ja to.kjo/", katakana: "ビヤンヴニュ・オ・ホシノヤ・トーキョー", romanization: "Bienvenue au Hoshinoya Tokyo", audioFile: null, scenario: "适合客人首次抵达酒店、正式接待或介绍场所时使用。普通迎面接待时通常先说 Bonjour 或 Bonsoir。", knowledge: "法语服务现场一般先进行时段问候，再补充 Bienvenue。对于酒店名称，可采用「Bienvenue au Hoshinoya Tokyo」。", patterns: [{ scene: "玄关／前台", text: "Bonjour. Bienvenue au Hoshinoya Tokyo.", meaning: "您好，欢迎来到 Hoshinoya Tokyo。", ipa: "/bɔ̃.ʒuʁ | bjɛ̃.və.ny o ho.ʃi.no.ja to.kjo/", katakana: "ボンジュール。ビヤンヴニュ・オ・ホシノヤ・トーキョー", romanization: "Bonjour. Bienvenue au Hoshinoya Tokyo.", audioFile: null }, { scene: "餐厅", text: "Bonsoir. Bienvenue au restaurant du Hoshinoya Tokyo.", meaning: "晚上好，欢迎来到 Hoshinoya Tokyo 的餐厅。", ipa: "/bɔ̃.swaʁ | bjɛ̃.və.ny o ʁɛs.to.ʁɑ̃ dy ho.ʃi.no.ja to.kjo/", katakana: "ボンソワール。ビヤンヴニュ・オ・レストラン・デュ・ホシノヤ・トーキョー", romanization: "Bonsoir. Bienvenue au restaurant du Hoshinoya Tokyo.", audioFile: null }, { scene: "可替换模板", text: "Bienvenue à {place}.", meaning: "欢迎来到{场所}。介词可能根据场所名称变为 au、à la、aux 或 à。", ipa: "/bjɛ̃.və.ny a {place}/", katakana: "ビヤンヴニュ・ア・［場所］", romanization: "Bienvenue à {place}.", audioFile: null }], derived: [{ text: "Entrez, je vous en prie", meaning: "请进", ipa: "/ɑ̃.tʁe ʒə vu.zɑ̃ pʁi/", katakana: "アントレ・ジュ・ヴ・ザン・プリ", romanization: "Entrez, je vous en prie", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "es", text: "Le damos la bienvenida a Hoshinoya Tokyo", meaning: "欢迎您来到 Hoshinoya Tokyo", ipa: "/le ˈða.mos la bjem.beˈni.ða a ho.ʃi.no.ja ˈto.kjo/", katakana: "レ・ダモス・ラ・ビエンベニーダ・ア・ホシノヤ・トーキョー", romanization: "Le damos la bienvenida a Hoshinoya Tokyo", audioFile: null, scenario: "正式、礼貌且不需要根据客人性别改变形式，适合酒店玄关、前台及正式接待。", knowledge: "单说 Bienvenido 或 Bienvenida 需要判断客人的性别；「Le damos la bienvenida」更适合建立统一的服务用语。面对多人时可将 Le 改为 Les。", patterns: [{ scene: "玄关／前台", text: "Buenos días. Le damos la bienvenida a Hoshinoya Tokyo.", meaning: "早上好，欢迎您来到 Hoshinoya Tokyo。", ipa: "/ˈbwe.nos ˈdi.as | le ˈða.mos la bjem.beˈni.ða a ho.ʃi.no.ja ˈto.kjo/", katakana: "ブエノス・ディアス。レ・ダモス・ラ・ビエンベニーダ・ア・ホシノヤ・トーキョー", romanization: "Buenos días. Le damos la bienvenida a Hoshinoya Tokyo.", audioFile: null }, { scene: "餐厅", text: "Buenas noches. Le damos la bienvenida al restaurante de Hoshinoya Tokyo.", meaning: "晚上好，欢迎您来到 Hoshinoya Tokyo 的餐厅。", ipa: "/ˈbwe.nas ˈno.tʃes | le ˈða.mos la bjem.beˈni.ða al res.tawˈɾan.te ðe ho.ʃi.no.ja ˈto.kjo/", katakana: "ブエナス・ノーチェス。レ・ダモス・ラ・ビエンベニーダ・アル・レスタウランテ・デ・ホシノヤ・トーキョー", romanization: "Buenas noches. Le damos la bienvenida al restaurante de Hoshinoya Tokyo.", audioFile: null }, { scene: "可替换模板", text: "Le damos la bienvenida a {place}.", meaning: "欢迎您来到{场所}。面对多人时使用 Les damos。", ipa: "/le ˈða.mos la bjem.beˈni.ða a {place}/", katakana: "レ・ダモス・ラ・ビエンベニーダ・ア・［場所］", romanization: "Le damos la bienvenida a {place}.", audioFile: null }], derived: [{ text: "Pase, por favor", meaning: "请进", ipa: "/ˈpa.se poɾ faˈβoɾ/", katakana: "パセ・ポル・ファボール", romanization: "Pase, por favor", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "it", text: "Le diamo il benvenuto a Hoshinoya Tokyo", meaning: "欢迎您来到 Hoshinoya Tokyo", ipa: "/le ˈdja.mo il bem.veˈnu.to a ho.ʃi.no.ja ˈto.kjo/", katakana: "レ・ディアモ・イル・ベンヴェヌート・ア・ホシノヤ・トーキョー", romanization: "Le diamo il benvenuto a Hoshinoya Tokyo", audioFile: null, scenario: "正式、礼貌，而且不必根据客人的性别改变形式，适合酒店玄关、前台和正式接待。", knowledge: "Benvenuto 或 Benvenuta 会随客人性别变化；「Le diamo il benvenuto」可以作为统一、稳妥的服务表达。", patterns: [{ scene: "玄关／前台", text: "Buongiorno. Le diamo il benvenuto a Hoshinoya Tokyo.", meaning: "您好，欢迎您来到 Hoshinoya Tokyo。", ipa: "/bwɔnˈdʒor.no | le ˈdja.mo il bem.veˈnu.to a ho.ʃi.no.ja ˈto.kjo/", katakana: "ブオンジョルノ。レ・ディアモ・イル・ベンヴェヌート・ア・ホシノヤ・トーキョー", romanization: "Buongiorno. Le diamo il benvenuto a Hoshinoya Tokyo.", audioFile: null }, { scene: "餐厅", text: "Buonasera. Le diamo il benvenuto al ristorante di Hoshinoya Tokyo.", meaning: "晚上好，欢迎您来到 Hoshinoya Tokyo 的餐厅。", ipa: "/bwo.naˈse.ra | le ˈdja.mo il bem.veˈnu.to al ri.stoˈran.te di ho.ʃi.no.ja ˈto.kjo/", katakana: "ブオナセーラ。レ・ディアモ・イル・ベンヴェヌート・アル・リストランテ・ディ・ホシノヤ・トーキョー", romanization: "Buonasera. Le diamo il benvenuto al ristorante di Hoshinoya Tokyo.", audioFile: null }, { scene: "可替换模板", text: "Le diamo il benvenuto a {place}.", meaning: "欢迎您来到{场所}。介词可能根据场所发生变化。", ipa: "/le ˈdja.mo il bem.veˈnu.to a {place}/", katakana: "レ・ディアモ・イル・ベンヴェヌート・ア・［場所］", romanization: "Le diamo il benvenuto a {place}.", audioFile: null }], derived: [{ text: "Prego, entri pure", meaning: "请进", ipa: "/ˈprɛ.ɡo ˈɛn.tri ˈpu.re/", katakana: "プレーゴ・エントリ・プレ", romanization: "Prego, entri pure", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "ru", text: "Добро пожаловать в Hoshinoya Tokyo", meaning: "欢迎来到 Hoshinoya Tokyo", ipa: "/dɐˈbro pɐˈʐaɫəvətʲ f ho.ʂɨ.no.ja ˈto.kʲɪ.o/", katakana: "ダブロー・パジャーラヴァチ・フ・ホシノヤ・トーキョー", romanization: "Dobro pozhalovat’ v Hoshinoya Tokyo", audioFile: null, scenario: "适合酒店玄关、前台、活动及正式接待场景。可在前面加 Доброе утро、Добрый день 或 Добрый вечер。", knowledge: "「Добро пожаловать」本身不随客人的性别或人数变化。介词 в 在无声辅音前可能听起来接近「フ」。", patterns: [{ scene: "玄关／前台", text: "Добрый день. Добро пожаловать в Hoshinoya Tokyo.", meaning: "您好，欢迎来到 Hoshinoya Tokyo。", ipa: "/ˈdo.brɨj dʲenʲ | dɐˈbro pɐˈʐaɫəvətʲ f ho.ʂɨ.no.ja ˈto.kʲɪ.o/", katakana: "ドーブルィ・ジェーニ。ダブロー・パジャーラヴァチ・フ・ホシノヤ・トーキョー", romanization: "Dobryy den’. Dobro pozhalovat’ v Hoshinoya Tokyo.", audioFile: null }, { scene: "餐厅", text: "Добрый вечер. Добро пожаловать в ресторан Hoshinoya Tokyo.", meaning: "晚上好，欢迎来到 Hoshinoya Tokyo 的餐厅。", ipa: "/ˈdo.brɨj ˈvʲe.tɕɪr | dɐˈbro pɐˈʐaɫəvətʲ v rʲɪ.stɐˈran ho.ʂɨ.no.ja ˈto.kʲɪ.o/", katakana: "ドーブルィ・ヴェーチェル。ダブロー・パジャーラヴァチ・ヴ・リスタラーン・ホシノヤ・トーキョー", romanization: "Dobryy vecher. Dobro pozhalovat’ v restoran Hoshinoya Tokyo.", audioFile: null }, { scene: "可替换模板", text: "Добро пожаловать в {place}.", meaning: "欢迎来到{场所}。", ipa: "/dɐˈbro pɐˈʐaɫəvətʲ v {place}/", katakana: "ダブロー・パジャーラヴァチ・ヴ・［場所］", romanization: "Dobro pozhalovat’ v {place}.", audioFile: null }], derived: [{ text: "Проходите, пожалуйста", meaning: "请进", ipa: "/prə.xɐˈdʲi.tʲe pɐˈʐa.lʊ.stə/", katakana: "プラハヂーチェ・パジャールスタ", romanization: "Prokhodite, pozhaluysta", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "ar", text: "أهلاً وسهلاً بكم في Hoshinoya Tokyo", meaning: "欢迎来到 Hoshinoya Tokyo", ipa: "/ʔah.lan wa sah.lan bi.kum fiː ho.ʃi.no.ja toː.ki.joː/", katakana: "アハラン・ワ・サハラン・ビクム・フィー・ホシノヤ・トーキョー", romanization: "ahlan wa sahlan bikum fī Hoshinoya Tokyo", audioFile: null, scenario: "适合酒店玄关、前台、餐厅和正式接待。بكم 是面对多位客人时的形式，也常作为较稳妥的迎宾表达。", knowledge: "普通迎面接待时，单说「أهلاً وسهلاً」已经自然。需要说明欢迎来到具体场所时，再加「بكم في＋场所」。", patterns: [{ scene: "玄关／前台", text: "أهلاً وسهلاً بكم في Hoshinoya Tokyo.", meaning: "欢迎来到 Hoshinoya Tokyo。", ipa: "/ʔah.lan wa sah.lan bi.kum fiː ho.ʃi.no.ja toː.ki.joː/", katakana: "アハラン・ワ・サハラン・ビクム・フィー・ホシノヤ・トーキョー", romanization: "Ahlan wa sahlan bikum fī Hoshinoya Tokyo.", audioFile: null }, { scene: "餐厅", text: "أهلاً وسهلاً بكم في مطعم Hoshinoya Tokyo.", meaning: "欢迎来到 Hoshinoya Tokyo 的餐厅。", ipa: "/ʔah.lan wa sah.lan bi.kum fiː matˤ.ʕam ho.ʃi.no.ja toː.ki.joː/", katakana: "アハラン・ワ・サハラン・ビクム・フィー・マトアム・ホシノヤ・トーキョー", romanization: "Ahlan wa sahlan bikum fī maṭʿam Hoshinoya Tokyo.", audioFile: null }, { scene: "可替换模板", text: "أهلاً وسهلاً بكم في {place}.", meaning: "欢迎来到{场所}。", ipa: "/ʔah.lan wa sah.lan bi.kum fiː {place}/", katakana: "アハラン・ワ・サハラン・ビクム・フィー・［場所］", romanization: "Ahlan wa sahlan bikum fī {place}.", audioFile: null }], derived: [{ text: "تفضل", meaning: "请 / 请进，对一位男性使用", ipa: "/ta.fadˤ.dˤal/", katakana: "タファッダル", romanization: "tafaḍḍal", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "th", text: "ยินดีต้อนรับสู่ Hoshinoya Tokyo ครับ/ค่ะ", meaning: "欢迎来到 Hoshinoya Tokyo", ipa: "/jin.diː tɔ̂ːn.ráp sùː ho.ɕi.no.ja toː.kʰjoː kʰráp/ / /jin.diː tɔ̂ːn.ráp sùː ho.ɕi.no.ja toː.kʰjoː kʰâː/", katakana: "インディー・トーンラップ・スー・ホシノヤ・トーキョー・クラップ / カー", romanization: "yin di ton rap su Hoshinoya Tokyo khrap / kha", audioFile: null, scenario: "适合酒店玄关、前台、活动及正式迎宾。男性说 ครับ，女性说 ค่ะ。", knowledge: "日常面对刚进入的客人，也可以先说「สวัสดีครับ/ค่ะ」。需要正式说明欢迎来到具体场所时，使用「ยินดีต้อนรับสู่＋场所」。", patterns: [{ scene: "玄关／前台", text: "สวัสดีครับ/ค่ะ ยินดีต้อนรับสู่ Hoshinoya Tokyo ครับ/ค่ะ", meaning: "您好，欢迎来到 Hoshinoya Tokyo。", ipa: "/sà.wàt.diː kʰráp kʰâː | jin.diː tɔ̂ːn.ráp sùː ho.ɕi.no.ja toː.kʰjoː kʰráp kʰâː/", katakana: "サワッディー・クラップ / カー。インディー・トーンラップ・スー・ホシノヤ・トーキョー・クラップ / カー", romanization: "Sawatdee khrap/kha. Yin di ton rap su Hoshinoya Tokyo khrap/kha.", audioFile: null }, { scene: "餐厅", text: "ยินดีต้อนรับสู่ห้องอาหารของ Hoshinoya Tokyo ครับ/ค่ะ", meaning: "欢迎来到 Hoshinoya Tokyo 的餐厅。", ipa: "/jin.diː tɔ̂ːn.ráp sùː hɔ̂ːŋ ʔaː.hǎːn kʰɔ̌ːŋ ho.ɕi.no.ja toː.kʰjoː kʰráp kʰâː/", katakana: "インディー・トーンラップ・スー・ホーンアーハーン・コーン・ホシノヤ・トーキョー・クラップ / カー", romanization: "Yin di ton rap su hong ahan khong Hoshinoya Tokyo khrap/kha.", audioFile: null }, { scene: "可替换模板", text: "ยินดีต้อนรับสู่ {place} ครับ/ค่ะ", meaning: "欢迎来到{场所}。", ipa: "/jin.diː tɔ̂ːn.ráp sùː {place} kʰráp kʰâː/", katakana: "インディー・トーンラップ・スー・［場所］・クラップ / カー", romanization: "Yin di ton rap su {place} khrap/kha.", audioFile: null }], derived: [{ text: "เชิญครับ/ค่ะ", meaning: "请 / 请进", ipa: "/tɕʰɤːn kʰráp/ / /tɕʰɤːn kʰâː/", katakana: "チューン・クラップ / カー", romanization: "choen khrap / kha", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "pt", text: "Seja bem-vindo(a)", meaning: "欢迎光临 / 欢迎您来到这里", ipa: "/ˈse.ʒɐ bẽj̃ ˈvĩ.du(a)/", katakana: "セジャ・ベンヴィンド（ベンヴィンダ）", romanization: "seja bem-vindo(a)", audioFile: null, scenario: "迎接客人进入酒店、餐厅或办理入住时使用，是葡萄牙语服务业最自然、最常见的欢迎表达。", knowledge: "根据客人性别变化：男性用「bem-vindo」，女性用「bem-vinda」。面对团体可使用「Sejam bem-vindos」。若直接欢迎来到酒店，可说「Seja bem-vindo ao Hoshinoya Tokyo」。", derived: [{ text: "Seja bem-vindo ao Hoshinoya Tokyo", meaning: "欢迎来到 Hoshinoya Tokyo（男性）", ipa: "/ˈse.ʒɐ bẽj̃ ˈvĩ.du aw o.ʃi.no.ja toˈkjo/", katakana: "セジャ・ベンヴィンド・アオ・ホシノヤ・トウキョウ", romanization: "seja bem-vindo ao Hoshinoya Tokyo", audioFile: null }, { text: "Entre, por favor", meaning: "请进", ipa: "/ˈẽ.tɾi poʁ fa.voʁ/", katakana: "エントレ・ポル・ファヴォール", romanization: "entre, por favor", audioFile: null }], status: "reviewed" },
{ chinese: "欢迎光临", lang: "he", text: "ברוכים הבאים", meaning: "欢迎光临 / 欢迎各位", ipa: "/bruˈxim ha.baˈim/", katakana: "ブルヒーム・ハバイーム", romanization: "brukhim haba'im", audioFile: null, scenario: "酒店、餐厅、活动接待及正式迎宾时最自然的欢迎表达。", knowledge: "这是现代希伯来语中最常见的欢迎语，字面意思为「欢迎来到这里」。面对单独女性可说「ברוכה הבאה (brukha haba'ah)」，但酒店面对一般客人时直接使用「ברוכים הבאים」即可。", derived: [{ text: "ברוכים הבאים ל־Hoshinoya Tokyo", meaning: "欢迎来到 Hoshinoya Tokyo", ipa: "/bruˈxim ha.baˈim le ho.ʃi.no.ja to.kjo/", katakana: "ブルヒーム・ハバイーム・レ・ホシノヤ・トウキョウ", romanization: "brukhim haba'im le-Hoshinoya Tokyo", audioFile: null }, { text: "בבקשה, היכנסו", meaning: "请进", ipa: "/be.va.kaˈʃa hi.ka.neˈsu/", katakana: "ベヴァカシャ・ヒカネス", romanization: "bevakasha, hikanesu", audioFile: null }], status: "reviewed" },
      // ── 请稍等 ──
{ chinese: "请稍等", lang: "ko", text: "잠시만 기다려 주세요", meaning: "请稍等一下", ipa: "/tɕam.ɕi.man ki.da.ɾjʌ tɕu.se.jo/", katakana: "チャムシマン・キダリョ・ジュセヨ", romanization: "jamsiman gidaryeo juseyo", audioFile: null, scenario: "需要查询信息、取物品或暂时离开客人身边时使用，适合前台、餐厅及电话服务。", knowledge: "「잠시만」表示「稍等一下」，「기다려 주세요」表示礼貌地请求对方等待。相比直接说「기다리세요」，语气更柔和，适合服务场合。", derived: [{ text: "조금만 더 기다려 주세요", meaning: "请再稍等一下", ipa: "/tɕo.gɯm.man tʌ ki.da.ɾjʌ tɕu.se.jo/", katakana: "チョグムマン・ト・キダリョ・ジュセヨ", romanization: "jogeumman deo gidaryeo juseyo", audioFile: null }, { text: "금방 가져다드리겠습니다", meaning: "马上为您拿来", ipa: "/kɯm.baŋ ka.dʑʌ.da.dɯ.ɾi.get̚.sɯm.ni.da/", katakana: "クムバン・カジョダドゥリゲッスムニダ", romanization: "geumbang gajyeodadeurigetseumnida", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "yue", text: "唔該，請稍等", meaning: "劳驾，请稍等", ipa: "/m̩²¹ kɔːi̯⁵⁵ | tsʰɪŋ²⁵ sɐːu̯³⁵ tɐŋ³⁵/", katakana: "ンーゴイ、チェン・サーウダン", romanization: "m4 goi1, cing2 saau2 dang2", audioFile: null, scenario: "需要客人短暂等待、查询资料或取物品时使用，适合酒店、餐厅和柜台服务。", knowledge: "单说「請稍等」较正式；在前面加「唔該」会使口头表达更自然、更有礼貌。「等陣」比较口语，不建议作为正式服务用语的首选。", derived: [{ text: "唔該，等一等", meaning: "劳驾，请等一下，较口语但仍礼貌", ipa: "/m̩²¹ kɔːi̯⁵⁵ | tɐŋ³⁵ jɐt̚⁵ tɐŋ³⁵/", katakana: "ンーゴイ、ダン・ヤッ・ダン", romanization: "m4 goi1, dang2 jat1 dang2", audioFile: null }, { text: "我即刻返嚟", meaning: "我马上回来", ipa: "/ŋɔː¹³ tɕɪk̚⁵ hɐk̚⁵ fɐːn⁵⁵ lɐi̯²¹/", katakana: "ンゴー・ジェッハッ・ファーンライ", romanization: "ngo5 zik1 hak1 faan1 lai4", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "en", text: "One moment, please", meaning: "请稍等一下", ipa: "/wʌn ˈmoʊ.mənt pliːz/", katakana: "ワン・モーメント・プリーズ", romanization: "One moment, please", audioFile: null, scenario: "需要查询信息、取物品或暂时处理其他事务时使用，适合前台、餐厅和面对面服务。", knowledge: "也可以说「Just a moment, please」。「Please hold」主要用于电话中请对方不要挂断，不宜作为普通面对面等待用语。", derived: [{ text: "I’ll be right with you", meaning: "我马上来为您服务", ipa: "/aɪl bi raɪt wɪð juː/", katakana: "アイル・ビー・ライト・ウィズ・ユー", romanization: "I’ll be right with you", audioFile: null }, { text: "Thank you for your patience", meaning: "感谢您的耐心等候", ipa: "/ˈθæŋk juː fər jʊr ˈpeɪ.ʃəns/", katakana: "サンキュー・フォー・ユア・ペイシェンス", romanization: "Thank you for your patience", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "de", text: "Einen Moment, bitte", meaning: "请稍等一下", ipa: "/ˈaɪ̯nən moˈmɛnt ˈbɪtə/", katakana: "アイネン・モメント・ビッテ", romanization: "Einen Moment, bitte", audioFile: null, scenario: "需要查询、取物品或暂时离开时使用，适合酒店、餐厅、商店及电话服务。", knowledge: "这是自然且礼貌的固定表达。「Einen Augenblick, bitte」意思相近，也可用于正式服务场合。", derived: [{ text: "Einen Augenblick, bitte", meaning: "请稍等片刻", ipa: "/ˈaɪ̯nən ˈaʊ̯ɡn̩ˌblɪk ˈbɪtə/", katakana: "アイネン・アウゲンブリック・ビッテ", romanization: "Einen Augenblick, bitte", audioFile: null }, { text: "Ich bin gleich wieder bei Ihnen", meaning: "我马上回来为您服务", ipa: "/ɪç bɪn ɡlaɪ̯ç ˈviːdɐ baɪ̯ ˈiːnən/", katakana: "イヒ・ビン・グライヒ・ヴィーダー・バイ・イーネン", romanization: "Ich bin gleich wieder bei Ihnen", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "fr", text: "Un instant, s’il vous plaît", meaning: "请稍等一下", ipa: "/œ̃.n‿ɛ̃s.tɑ̃ sil vu plɛ/", katakana: "アン・ナンスタン、スィル・ヴ・プレ", romanization: "Un instant, s’il vous plaît", audioFile: null, scenario: "服务过程中需要查询、取物品或暂时离开时使用，适合酒店、餐厅和柜台服务。", knowledge: "面对客人应使用敬称形式「s’il vous plaît」，不要改成对熟人使用的「s’il te plaît」。", derived: [{ text: "Je reviens tout de suite", meaning: "我马上回来", ipa: "/ʒə ʁə.vjɛ̃ tu də sɥit/", katakana: "ジュ・ルヴィヤン・トゥ・ドゥ・スュイット", romanization: "Je reviens tout de suite", audioFile: null }, { text: "Veuillez patienter un instant", meaning: "请稍候片刻，较正式", ipa: "/vø.je pa.sjɑ̃.te œ̃.n‿ɛ̃s.tɑ̃/", katakana: "ヴイエ・パスィヤンテ・アン・ナンスタン", romanization: "Veuillez patienter un instant", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "es", text: "Un momento, por favor", meaning: "请稍等一下", ipa: "/um moˈmen.to poɾ faˈβoɾ/", katakana: "ウン・モメント、ポル・ファボール", romanization: "Un momento, por favor", audioFile: null, scenario: "需要查询、取物品或暂时处理其他事务时使用，适合酒店、餐厅和柜台服务。", knowledge: "单说「Un momento」也能表达稍等，但加上「por favor」更加礼貌，适合面对客人。", derived: [{ text: "Permítame un momento", meaning: "请给我一点时间 / 请稍等片刻", ipa: "/peɾˈmi.ta.me um moˈmen.to/", katakana: "ペルミタメ・ウン・モメント", romanization: "Permítame un momento", audioFile: null }, { text: "Enseguida vuelvo", meaning: "我马上回来", ipa: "/en.seˈɣi.ða ˈβwel.βo/", katakana: "エンセギーダ・ブエルボ", romanization: "Enseguida vuelvo", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "it", text: "Un momento, per favore", meaning: "请稍等一下", ipa: "/um moˈmen.to per faˈvo.re/", katakana: "ウン・モメント、ペル・ファヴォーレ", romanization: "Un momento, per favore", audioFile: null, scenario: "需要查询信息、取物品或短暂离开时使用，适合酒店、餐厅和正式服务场合。", knowledge: "「Un attimo, per favore」也很常见，但语气稍口语；「Un momento, per favore」作为统一的服务表达更稳妥。", derived: [{ text: "Torno subito", meaning: "我马上回来", ipa: "/ˈtor.no ˈsu.bi.to/", katakana: "トルノ・スービト", romanization: "Torno subito", audioFile: null }, { text: "La prego di attendere un momento", meaning: "请您稍候片刻，较正式", ipa: "/la ˈprɛ.ɡo di atˈtɛn.de.re um moˈmen.to/", katakana: "ラ・プレーゴ・ディ・アッテンデレ・ウン・モメント", romanization: "La prego di attendere un momento", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "ru", text: "Одну минуту, пожалуйста", meaning: "请稍等一下", ipa: "/ɐdˈnu mʲɪˈnutʊ pɐˈʐaɫʊstə/", katakana: "アドヌー・ミヌートゥ、パジャールスタ", romanization: "Odnu minutu, pozhaluysta", audioFile: null, scenario: "需要查询、取物品或暂时处理事务时使用，适合酒店、餐厅和柜台服务。", knowledge: "字面是「请给我一分钟」，实际常用于表示「请稍等」。较简短的「Минутку, пожалуйста」也很常见。", derived: [{ text: "Подождите, пожалуйста", meaning: "请等一下", ipa: "/pədɐˈʐdʲitʲe pɐˈʐaɫʊstə/", katakana: "パダジヂーチェ、パジャールスタ", romanization: "Podozhdite, pozhaluysta", audioFile: null }, { text: "Я сейчас вернусь", meaning: "我马上回来", ipa: "/ja sʲɪˈtɕas vʲɪrˈnusʲ/", katakana: "ヤー・スィチャース・ヴィルヌーシ", romanization: "Ya seychas vernus’", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "ar", text: "لحظة من فضلك", meaning: "请稍等一下", ipa: "/laħ.ðˤa min fadˤ.lik/", katakana: "ラフザ・ミン・ファドリク", romanization: "laḥẓa min faḍlik", audioFile: null, scenario: "需要查询信息、取物品或请客人短暂等待时使用，适合一般服务场合。", knowledge: "「من فضلك」相当于「请」。面对男性时常读作 min faḍlik，面对女性时结尾读音有所变化。阿拉伯语地区方言差异较大，这里采用现代标准阿拉伯语。", derived: [{ text: "سأعود حالاً", meaning: "我马上回来", ipa: "/sa.ʔa.ʕuː.du ħaː.lan/", katakana: "サアウードゥ・ハーラン", romanization: "saʾaʿūdu ḥālan", audioFile: null }, { text: "يرجى الانتظار قليلاً", meaning: "请稍候片刻，较正式", ipa: "/jur.dʒaː al.in.ti.ðˤaːr qa.liː.lan/", katakana: "ユルジャー・アルインティザール・カリーラン", romanization: "yurjā al-intiẓār qalīlan", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "th", text: "รอสักครู่ครับ/ค่ะ", meaning: "请稍等一下", ipa: "/rɔː sàk kʰrûː kʰráp/ / /rɔː sàk kʰrûː kʰâː/", katakana: "ロー・サッククルー・クラップ / カー", romanization: "ro sak khru khrap / kha", audioFile: null, scenario: "需要查询、取物品或暂时处理事务时使用，适合酒店、餐厅和柜台服务。", knowledge: "「สักครู่」表示一会儿、片刻。男性使用「ครับ」，女性使用「ค่ะ」。更正式的通知或广播可使用「กรุณารอสักครู่」。", derived: [{ text: "กรุณารอสักครู่ครับ/ค่ะ", meaning: "请稍候片刻，较正式", ipa: "/ka.ru.naː rɔː sàk kʰrûː kʰráp/ / /ka.ru.naː rɔː sàk kʰrûː kʰâː/", katakana: "カルナー・ロー・サッククルー・クラップ / カー", romanization: "karuna ro sak khru khrap / kha", audioFile: null }, { text: "เดี๋ยวกลับมาครับ/ค่ะ", meaning: "马上回来", ipa: "/dǐaw klàp maː kʰráp/ / /dǐaw klàp maː kʰâː/", katakana: "ディアオ・クラップ・マー・クラップ / カー", romanization: "diao klap ma khrap / kha", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "pt", text: "Um momento, por favor", meaning: "请稍等", ipa: "/ũ moˈmẽ.tu poʁ fa.voʁ/", katakana: "ウン・モメント・ポル・ファヴォール", romanization: "um momento, por favor", audioFile: null, scenario: "查询预约、准备房卡、取物品或办理手续时，对客人表示请稍候，是葡萄牙语服务业最自然的表达。", knowledge: "这是葡萄牙和巴西都非常常用的服务用语，比直接说「Espere」更礼貌、更符合酒店接待场景。", derived: [{ text: "Só um momento, por favor", meaning: "请稍等一下", ipa: "/sɔ ũ moˈmẽ.tu poʁ fa.voʁ/", katakana: "ソ・ウン・モメント・ポル・ファヴォール", romanization: "só um momento, por favor", audioFile: null }, { text: "Já volto", meaning: "我马上回来", ipa: "/ʒa ˈvɔw.tu/", katakana: "ジャ・ヴォウト", romanization: "já volto", audioFile: null }], status: "reviewed" },
{ chinese: "请稍等", lang: "he", text: "רק רגע, בבקשה", meaning: "请稍等", ipa: "/rak ˈʁe.ɡa be.va.kaˈʃa/", katakana: "ラク・レガ・ベヴァカシャ", romanization: "rak rega, bevakasha", audioFile: null, scenario: "办理入住、确认信息、准备物品或查询时，请客人稍候，是现代希伯来语服务场景中最自然的表达。", knowledge: "「רק רגע」字面意思是「就一会儿」，搭配「בבקשה」后语气礼貌自然，酒店、餐厅和商店都广泛使用。", derived: [{ text: "רגע אחד, בבקשה", meaning: "请稍等一下（较正式）", ipa: "/ˈʁe.ɡa eˈχad be.va.kaˈʃa/", katakana: "レガ・エハド・ベヴァカシャ", romanization: "rega echad, bevakasha", audioFile: null }, { text: "מיד אחזור", meaning: "我马上回来", ipa: "/miˈjad aχˈzor/", katakana: "ミヤド・アフゾル", romanization: "miyad achzor", audioFile: null }], status: "reviewed" },

      // ── 这边请 ──
{ chinese: "这边请", lang: "ko", text: "이쪽으로 오세요", meaning: "请往这边走 / 这边请", ipa: "/i.t͈ɕo.ɡɯ.ɾo o.se.jo/", katakana: "イッチョグロ・オセヨ", romanization: "ijjogeuro oseyo", audioFile: null, scenario: "引导客人前往座位、客房、电梯或指定区域时使用，适合前台、玄关和餐厅服务。", knowledge: "「이쪽」表示这边，「-으로」表示朝某个方向，「오세요」是礼貌地请对方过来。配合开放手掌指示方向会很自然。", derived: [{ text: "저를 따라오세요", meaning: "请跟我来", ipa: "/tɕʌ.ɾɯl t͈a.ɾa.o.se.jo/", katakana: "チョルル・ッタラオセヨ", romanization: "jeoreul ttaraoseyo", audioFile: null }, { text: "여기에 앉아 주세요", meaning: "请坐这里", ipa: "/jʌ.ɡi.e an.dʑa tɕu.se.jo/", katakana: "ヨギエ・アンジャ・ジュセヨ", romanization: "yeogie anja juseyo", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "yue", text: "呢邊請", meaning: "这边请", ipa: "/niː⁵⁵ piːn⁵⁵ tsʰɪŋ²⁵/", katakana: "ニービン・チェン", romanization: "ni1 bin1 cing2", audioFile: null, scenario: "引导客人前往座位、房间、电梯或指定区域时使用，适合酒店及餐厅服务。", knowledge: "「呢邊」表示这边。实际接待时可说「唔該，呢邊請」，语气更完整、更礼貌。", derived: [{ text: "唔該，呢邊請", meaning: "劳驾，这边请", ipa: "/m̩²¹ kɔːi̯⁵⁵ | niː⁵⁵ piːn⁵⁵ tsʰɪŋ²⁵/", katakana: "ンーゴイ、ニービン・チェン", romanization: "m4 goi1, ni1 bin1 cing2", audioFile: null }, { text: "請跟我嚟", meaning: "请跟我来", ipa: "/tsʰɪŋ²⁵ kɐn⁵⁵ ŋɔː¹³ lɐi̯²¹/", katakana: "チェン・ガン・ンゴー・ライ", romanization: "cing2 gan1 ngo5 lai4", audioFile: null }, { text: "請坐", meaning: "请坐", ipa: "/tsʰɪŋ²⁵ tsʰɔː¹³/", katakana: "チェン・ツォー", romanization: "cing2 co5", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "en", text: "This way, please", meaning: "这边请", ipa: "/ðɪs weɪ pliːz/", katakana: "ディス・ウェイ、プリーズ", romanization: "This way, please", audioFile: null, scenario: "引导客人前往座位、客房、电梯或指定区域时使用，适合前台、玄关和餐厅服务。", knowledge: "这是最简洁自然的服务表达。若需要由你亲自带路，也可以说「Please follow me」。", derived: [{ text: "Right this way, please", meaning: "请走这边，语气稍更热情", ipa: "/raɪt ðɪs weɪ pliːz/", katakana: "ライト・ディス・ウェイ、プリーズ", romanization: "Right this way, please", audioFile: null }, { text: "Please follow me", meaning: "请跟我来", ipa: "/pliːz ˈfɑː.loʊ miː/", katakana: "プリーズ・フォロー・ミー", romanization: "Please follow me", audioFile: null }, { text: "Please have a seat", meaning: "请坐", ipa: "/pliːz hæv ə siːt/", katakana: "プリーズ・ハヴ・ア・シート", romanization: "Please have a seat", audioFile: null }, { text: "After you", meaning: "您先请", ipa: "/ˈæf.tər juː/", katakana: "アフター・ユー", romanization: "After you", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "de", text: "Hier entlang, bitte", meaning: "请往这边走 / 这边请", ipa: "/hiːɐ̯ ɛntˈlaŋ ˈbɪtə/", katakana: "ヒーア・エントラング、ビッテ", romanization: "Hier entlang, bitte", audioFile: null, scenario: "引导客人前往座位、房间或指定区域时使用，适合酒店、餐厅和商店。", knowledge: "「hier entlang」表示沿这边走。也可以将 bitte 放在句首说「Bitte hier entlang」。", derived: [{ text: "Kommen Sie bitte mit", meaning: "请跟我来", ipa: "/ˈkɔmən ziː ˈbɪtə mɪt/", katakana: "コメン・ズィー・ビッテ・ミット", romanization: "Kommen Sie bitte mit", audioFile: null }, { text: "Bitte nehmen Sie Platz", meaning: "请入座", ipa: "/ˈbɪtə ˈneːmən ziː plat͡s/", katakana: "ビッテ・ネーメン・ズィー・プラッツ", romanization: "Bitte nehmen Sie Platz", audioFile: null }, { text: "Geradeaus, bitte", meaning: "请直走", ipa: "/ɡəˈʁaːdəʔaʊ̯s ˈbɪtə/", katakana: "ゲラーデアウス、ビッテ", romanization: "Geradeaus, bitte", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "fr", text: "Par ici, s’il vous plaît", meaning: "请往这边走 / 这边请", ipa: "/paʁ i.si sil vu plɛ/", katakana: "パール・イスィ、スィル・ヴ・プレ", romanization: "Par ici, s’il vous plaît", audioFile: null, scenario: "引导客人前往座位、客房、电梯或指定区域时使用，适合酒店和餐厅服务。", knowledge: "「Par ici」表示从这边、往这边。面对客人应使用礼貌形式「s’il vous plaît」。", derived: [{ text: "Veuillez me suivre, s’il vous plaît", meaning: "请跟我来，较正式", ipa: "/vø.je mə sɥivʁ sil vu plɛ/", katakana: "ヴイエ・ム・スュイーヴル、スィル・ヴ・プレ", romanization: "Veuillez me suivre, s’il vous plaît", audioFile: null }, { text: "Installez-vous, je vous en prie", meaning: "请入座 / 请安坐", ipa: "/ɛ̃s.ta.le vu ʒə vu.zɑ̃ pʁi/", katakana: "アンスタレ・ヴ、ジュ・ヴ・ザン・プリ", romanization: "Installez-vous, je vous en prie", audioFile: null }, { text: "Par là, s’il vous plaît", meaning: "请往那边走", ipa: "/paʁ la sil vu plɛ/", katakana: "パール・ラ、スィル・ヴ・プレ", romanization: "Par là, s’il vous plaît", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "es", text: "Por aquí, por favor", meaning: "请往这边走 / 这边请", ipa: "/poɾ aˈki poɾ faˈβoɾ/", katakana: "ポル・アキー、ポル・ファボール", romanization: "Por aquí, por favor", audioFile: null, scenario: "引导客人前往座位、房间或指定区域时使用，适合酒店、餐厅和商店。", knowledge: "「Por aquí」表示从这边、往这边。配合手势即可自然使用。", derived: [{ text: "Sígame, por favor", meaning: "请跟我来", ipa: "/ˈsi.ɣa.me poɾ faˈβoɾ/", katakana: "スィガメ、ポル・ファボール", romanization: "Sígame, por favor", audioFile: null }, { text: "Tome asiento, por favor", meaning: "请入座", ipa: "/ˈto.me aˈsjen.to poɾ faˈβoɾ/", katakana: "トメ・アスィエント、ポル・ファボール", romanization: "Tome asiento, por favor", audioFile: null }, { text: "Adelante, por favor", meaning: "请往前 / 请进", ipa: "/a.ðeˈlan.te poɾ faˈβoɾ/", katakana: "アデランテ、ポル・ファボール", romanization: "Adelante, por favor", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "it", text: "Da questa parte, prego", meaning: "请往这边走 / 这边请", ipa: "/da ˈkwe.sta ˈpar.te ˈprɛ.ɡo/", katakana: "ダ・クエスタ・パルテ、プレーゴ", romanization: "Da questa parte, prego", audioFile: null, scenario: "引导客人前往座位、客房或指定区域时使用，适合酒店和餐厅服务。", knowledge: "服务场合中，句尾使用「prego」比「per favore」更有迎宾和引导的感觉。较简短的说法是「Di qua, prego」。", derived: [{ text: "Di qua, prego", meaning: "这边请，较简短", ipa: "/di kwa ˈprɛ.ɡo/", katakana: "ディ・クア、プレーゴ", romanization: "Di qua, prego", audioFile: null }, { text: "Mi segua, per favore", meaning: "请跟我来", ipa: "/mi ˈse.ɡwa per faˈvo.re/", katakana: "ミ・セグア、ペル・ファヴォーレ", romanization: "Mi segua, per favore", audioFile: null }, { text: "Si accomodi, prego", meaning: "请入座 / 请自便", ipa: "/si akˈkɔ.mo.di ˈprɛ.ɡo/", katakana: "スィ・アッコモディ、プレーゴ", romanization: "Si accomodi, prego", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "ru", text: "Сюда, пожалуйста", meaning: "请往这边走 / 这边请", ipa: "/sʲʊˈda pɐˈʐaɫʊstə/", katakana: "スュダー、パジャールスタ", romanization: "Syuda, pozhaluysta", audioFile: null, scenario: "配合手势引导客人前往座位、客房或指定区域时使用，适合酒店和餐厅服务。", knowledge: "这是简洁自然的引导表达。「пожалуйста」在请求或引导对方行动时表示礼貌。", derived: [{ text: "За мной, пожалуйста", meaning: "请跟我来", ipa: "/zɐ mnoj pɐˈʐaɫʊstə/", katakana: "ザ・ムノーイ、パジャールスタ", romanization: "Za mnoy, pozhaluysta", audioFile: null }, { text: "Присаживайтесь, пожалуйста", meaning: "请坐", ipa: "/prʲɪˈsaʐɨvəjtʲɪsʲ pɐˈʐaɫʊstə/", katakana: "プリサージヴァイチェシ、パジャールスタ", romanization: "Prisazhivaytes’, pozhaluysta", audioFile: null }, { text: "Прямо, пожалуйста", meaning: "请直走", ipa: "/ˈprʲamə pɐˈʐaɫʊstə/", katakana: "プリャーマ、パジャールスタ", romanization: "Pryamo, pozhaluysta", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "ar", text: "تفضلوا من هنا", meaning: "各位请走这边", ipa: "/ta.fadˤ.dˤa.luː min hu.naː/", katakana: "タファッダルー・ミン・フナー", romanization: "tafaḍḍalū min hunā", audioFile: null, scenario: "引导一组客人或同行客人前往座位、房间或指定区域时使用，适合酒店和餐厅。", knowledge: "阿拉伯语中的「请」会随对象变化。对一位男性说「تفضل」，对一位女性说「تفضلي」，对多人说「تفضلوا」。因此不能把单数阳性形式视为男女通用。", derived: [{ text: "تفضل من هنا", meaning: "请走这边，对一位男性使用", ipa: "/ta.fadˤ.dˤal min hu.naː/", katakana: "タファッダル・ミン・フナー", romanization: "tafaḍḍal min hunā", audioFile: null }, { text: "تفضلي من هنا", meaning: "请走这边，对一位女性使用", ipa: "/ta.fadˤ.dˤa.liː min hu.naː/", katakana: "タファッダリー・ミン・フナー", romanization: "tafaḍḍalī min hunā", audioFile: null }, { text: "اتبعوني من فضلكم", meaning: "请各位跟我来", ipa: "/it.ta.bi.ʕuː.niː min fadˤ.li.kum/", katakana: "イッタビウーニー・ミン・ファドリクム", romanization: "ittabiʿūnī min faḍlikum", audioFile: null }, { text: "تفضلوا بالجلوس", meaning: "各位请坐", ipa: "/ta.fadˤ.dˤa.luː bil.dʒu.luːs/", katakana: "タファッダルー・ビルジュルース", romanization: "tafaḍḍalū bil-julūs", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "th", text: "เชิญทางนี้ครับ/ค่ะ", meaning: "这边请", ipa: "/tɕʰɤːn tʰaːŋ niː kʰráp/ / /tɕʰɤːn tʰaːŋ niː kʰâː/", katakana: "チューン・ターンニー・クラップ / カー", romanization: "choen thang ni khrap / kha", audioFile: null, scenario: "引导客人前往座位、客房、电梯或指定区域时使用，适合酒店和餐厅服务。", knowledge: "「ทางนี้」表示这边，「เชิญ」表示礼貌地邀请或请对方行动。你本人使用时说「เชิญทางนี้ครับ」。", derived: [{ text: "ตามมาทางนี้ครับ/ค่ะ", meaning: "请跟我走这边", ipa: "/taːm maː tʰaːŋ niː kʰráp/ / /taːm maː tʰaːŋ niː kʰâː/", katakana: "ターム・マー・ターンニー・クラップ / カー", romanization: "tam ma thang ni khrap / kha", audioFile: null }, { text: "เชิญนั่งครับ/ค่ะ", meaning: "请坐", ipa: "/tɕʰɤːn naŋ kʰráp/ / /tɕʰɤːn naŋ kʰâː/", katakana: "チューン・ナン・クラップ / カー", romanization: "choen nang khrap / kha", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "pt", text: "Por aqui, por favor", meaning: "这边请", ipa: "/poɾ aˈki poʁ fa.voʁ/", katakana: "ポル・アキー・ポル・ファヴォール", romanization: "por aqui, por favor", audioFile: null, scenario: "引导客人前往前台、餐厅、座位、电梯或房间时使用，是葡萄牙语酒店和服务业最自然的表达。", knowledge: "这是葡萄牙和巴西都广泛使用的引导用语。若需要带领客人同行，则更常说「Por favor, acompanhe-me」。", derived: [{ text: "Por favor, acompanhe-me", meaning: "请跟我来", ipa: "/poɾ faˈvoʁ a.kõˈpɐ.ɲi mi/", katakana: "ポル・ファヴォール・アコンパニ・ミ", romanization: "por favor, acompanhe-me", audioFile: null }, { text: "Pode entrar", meaning: "请进", ipa: "/ˈpɔ.dʒi ẽˈtɾaʁ/", katakana: "ポジ・エントラール", romanization: "pode entrar", audioFile: null }], status: "reviewed" },
{ chinese: "这边请", lang: "he", text: "בבקשה, לכאן", meaning: "这边请", ipa: "/be.va.kaˈʃa leˈkan/", katakana: "ベヴァカシャ・レカン", romanization: "bevakasha, lekan", audioFile: null, scenario: "引导客人前往前台、餐厅、座位、电梯或客房时使用，是现代希伯来语中自然、礼貌的表达。", knowledge: "「לכאן」表示「到这边」，与「בבקשה」组合后就是服务业中最自然的「这边请」。若需要带领客人同行，则更常使用「בבקשה, אחריי」。", derived: [{ text: "בבקשה, אחריי", meaning: "请跟我来", ipa: "/be.va.kaˈʃa a.χaˈʁaj/", katakana: "ベヴァカシャ・アハライ", romanization: "bevakasha, acharai", audioFile: null }, { text: "בבקשה, היכנסו", meaning: "请进", ipa: "/be.va.kaˈʃa hi.ka.neˈsu/", katakana: "ベヴァカシャ・ヒカネス", romanization: "bevakasha, hikanesu", audioFile: null }], status: "reviewed" },


      // ── 请慢用 ──
{ chinese: "请慢用", lang: "ko", text: "맛있게 드세요", meaning: "请慢用 / 请享用", ipa: "/ma.ɕit̚.k͈e tɯ.se.jo/", katakana: "マシッケ・ドゥセヨ", romanization: "masitge deuseyo", audioFile: null, scenario: "上菜后、说明完菜品或客人准备开始用餐时使用，是韩国餐饮服务中自然且常见的礼貌表达。", knowledge: "「맛있게」表示美味地、好好地，「드세요」是「吃」的敬语表达。整句应作为固定的用餐祝语记忆。", derived: [{ text: "맛있게 드십시오", meaning: "请慢用，语气比「맛있게 드세요」更正式郑重", ipa: "/ma.ɕit̚.k͈e tɯ.ɕip̚.ɕi.o/", katakana: "マシッケ・ドゥシプシオ", romanization: "masitge deusipsio", audioFile: null }, { text: "즐거운 식사 되세요", meaning: "祝您用餐愉快", ipa: "/tɕɯl.ɡʌ.un ɕik̚.s͈a twe.se.jo/", katakana: "チュルゴウン・シクサ・トェセヨ", romanization: "jeulgeoun siksa doeseyo", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "yue", text: "請慢用", meaning: "请慢用 / 请享用", ipa: "/tsʰɪŋ²⁵ maːn²² jʊŋ²²/", katakana: "チェン・マーンヨン", romanization: "cing2 maan6 jung6", audioFile: null, scenario: "上菜后请客人享用时使用，语气正式简洁，适合酒店餐厅、酒楼及较正式的餐饮服务。", knowledge: "「請慢用」比较接近正式服务用语；日常或较亲切的餐饮场景也常说「慢慢食」。", derived: [{ text: "慢慢食", meaning: "慢慢吃 / 请慢用，较口语亲切", ipa: "/maːn²² maːn²² sɪk̚²/", katakana: "マーンマーン・セッ", romanization: "maan6 maan6 sik6", audioFile: null }, { text: "趁熱食", meaning: "请趁热吃", ipa: "/tsʰɐn³³ jiːt̚² sɪk̚²/", katakana: "ツァンイッ・セッ", romanization: "can3 jit6 sik6", audioFile: null }, { text: "請慢慢享用", meaning: "请慢慢享用，较完整正式", ipa: "/tsʰɪŋ²⁵ maːn²² maːn²² hœːŋ³⁵ jʊŋ²²/", katakana: "チェン・マーンマーン・ヒョンヨン", romanization: "cing2 maan6 maan6 hoeng2 jung6", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "en", text: "Enjoy your meal", meaning: "请慢用 / 祝您用餐愉快", ipa: "/ɪnˈdʒɔɪ jʊr miːl/", katakana: "エンジョイ・ユア・ミール", romanization: "Enjoy your meal", audioFile: null, scenario: "上菜后、说明完菜品或客人准备开始用餐时使用，适合酒店餐厅和一般餐饮服务。", knowledge: "完整表达是「Enjoy your meal」。实际服务现场也经常简短地说「Enjoy!」，语气自然轻松。", derived: [{ text: "Enjoy!", meaning: "请享用，简短自然", ipa: "/ɪnˈdʒɔɪ/", katakana: "エンジョイ", romanization: "Enjoy!", audioFile: null }, { text: "I hope you enjoy your meal", meaning: "希望您用餐愉快，语气较完整温和", ipa: "/aɪ hoʊp ju ɪnˈdʒɔɪ jʊr miːl/", katakana: "アイ・ホープ・ユー・エンジョイ・ユア・ミール", romanization: "I hope you enjoy your meal", audioFile: null }, { text: "Please take your time and enjoy", meaning: "请慢慢享用，不必着急", ipa: "/pliːz teɪk jʊr taɪm ænd ɪnˈdʒɔɪ/", katakana: "プリーズ・テイク・ユア・タイム・アンド・エンジョイ", romanization: "Please take your time and enjoy", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "de", text: "Guten Appetit", meaning: "祝您用餐愉快 / 请慢用", ipa: "/ˈɡuːtn̩ apeˈtiːt/", katakana: "グーテン・アペティート", romanization: "Guten Appetit", audioFile: null, scenario: "上菜后或客人准备开始用餐时使用，是德语中最常见的用餐祝语。", knowledge: "这是固定表达，字面意思是「祝您有好胃口」。对一位客人或多位客人都可以使用。", derived: [{ text: "Lassen Sie es sich schmecken", meaning: "请好好享用 / 愿您吃得满意", ipa: "/ˈlasn̩ ziː ɛs zɪç ˈʃmɛkn̩/", katakana: "ラッセン・ズィー・エス・ズィヒ・シュメッケン", romanization: "Lassen Sie es sich schmecken", audioFile: null }, { text: "Ich wünsche Ihnen guten Appetit", meaning: "祝您用餐愉快，较完整正式", ipa: "/ɪç ˈvʏnʃə ˈiːnən ˈɡuːtn̩ apeˈtiːt/", katakana: "イヒ・ヴュンシェ・イーネン・グーテン・アペティート", romanization: "Ich wünsche Ihnen guten Appetit", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "fr", text: "Bon appétit", meaning: "请慢用 / 祝您用餐愉快", ipa: "/bɔ̃.n‿a.pe.ti/", katakana: "ボナペティ", romanization: "Bon appétit", audioFile: null, scenario: "上菜后或客人准备开始用餐时使用，是法语中标准且自然的用餐祝语。", knowledge: "「Bon」和「appétit」之间会发生连音，听起来接近「ボナペティ」。", derived: [{ text: "Je vous souhaite un bon appétit", meaning: "祝您用餐愉快，较完整正式", ipa: "/ʒə vu swɛt œ̃ bɔ̃.n‿a.pe.ti/", katakana: "ジュ・ヴ・スウェット・アン・ボナペティ", romanization: "Je vous souhaite un bon appétit", audioFile: null }, { text: "Bonne dégustation", meaning: "祝您品尝愉快，适合品鉴菜单、酒类或特色料理", ipa: "/bɔn de.ɡys.ta.sjɔ̃/", katakana: "ボンヌ・デギュスタスィオン", romanization: "Bonne dégustation", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "es", text: "Buen provecho", meaning: "请慢用 / 祝您用餐愉快", ipa: "/bwem proˈβe.tʃo/", katakana: "ブエン・プロベチョ", romanization: "Buen provecho", audioFile: null, scenario: "上菜后或客人开始用餐时使用，在西班牙语地区广泛通用。", knowledge: "不同地区的习惯略有差异。在许多拉丁美洲地区常说「Buen provecho」，西班牙也常听到「Que aproveche」。", derived: [{ text: "Que aproveche", meaning: "祝您用餐愉快，在西班牙较常见", ipa: "/ke a.proˈβe.tʃe/", katakana: "ケ・アプロベチェ", romanization: "Que aproveche", audioFile: null }, { text: "Disfrute de su comida", meaning: "请享用您的餐点", ipa: "/disˈfɾu.te ðe su koˈmi.ða/", katakana: "ディスフルテ・デ・ス・コミーダ", romanization: "Disfrute de su comida", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "it", text: "Buon appetito", meaning: "请慢用 / 祝您用餐愉快", ipa: "/bwɔn ap.peˈti.to/", katakana: "ブオン・アッペティート", romanization: "Buon appetito", audioFile: null, scenario: "上菜后或客人准备开始用餐时使用，是意大利语中标准且自然的用餐祝语。", knowledge: "「Buon appetito」适用于午餐、晚餐及一般用餐场景，对一位或多位客人都可以使用。", derived: [{ text: "Le auguro buon appetito", meaning: "祝您用餐愉快，较正式完整", ipa: "/le ˈau.ɡu.ro bwɔn ap.peˈti.to/", katakana: "レ・アウグロ・ブオン・アッペティート", romanization: "Le auguro buon appetito", audioFile: null }, { text: "Buona degustazione", meaning: "祝您品鉴愉快，适合套餐、酒类或特色料理", ipa: "/ˈbwɔ.na de.ɡu.staˈtsjo.ne/", katakana: "ブオナ・デグスタツィオーネ", romanization: "Buona degustazione", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "ru", text: "Приятного аппетита", meaning: "祝您用餐愉快 / 请慢用", ipa: "/prʲɪˈjatnəvə ɐpʲɪˈtʲitə/", katakana: "プリヤートナヴァ・アピチータ", romanization: "Priyatnogo appetita", audioFile: null, scenario: "上菜后或客人准备开始用餐时使用，是俄语中标准且常见的用餐祝语。", knowledge: "该表达对一位或多位客人都可以使用，不需要随性别或人数变化。", derived: [{ text: "Желаю вам приятного аппетита", meaning: "祝您用餐愉快，较完整正式", ipa: "/ʐɨˈla.jʊ vam prʲɪˈjatnəvə ɐpʲɪˈtʲitə/", katakana: "ジェラーユ・ヴァム・プリヤートナヴァ・アピチータ", romanization: "Zhelayu vam priyatnogo appetita", audioFile: null }, { text: "Наслаждайтесь ужином", meaning: "请享用晚餐", ipa: "/nəslɐˈʐdajtʲɪsʲ ˈuʐɨnəm/", katakana: "ナスラジュダーイチェシ・ウージナム", romanization: "Naslazhdaytes’ uzhinom", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "ar", text: "بالهناء والشفاء", meaning: "祝您用餐愉快 / 愿食物带来满足与健康", ipa: "/bil.ha.naːʔ waʃ.ʃi.faːʔ/", katakana: "ビルハナー・ワッシファー", romanization: "bil-hanāʾ wa-sh-shifāʾ", audioFile: null, scenario: "上菜后或客人开始用餐时使用，在多个阿拉伯语地区都能理解，是带有祝福意味的用餐表达。", knowledge: "阿拉伯语地区方言差异较大。「بالهناء والشفاء」是一种较广泛理解的祝福，表达食物带来愉悦和健康的愿望。", derived: [{ text: "تفضلوا بالطعام", meaning: "各位请用餐", ipa: "/ta.fadˤ.dˤa.luː bitˤ.tˤa.ʕaːm/", katakana: "タファッダルー・ビッタアーム", romanization: "tafaḍḍalū biṭ-ṭaʿām", audioFile: null }, { text: "صحة وعافية", meaning: "祝健康安好，部分地区常用的用餐祝语", ipa: "/sˤiħ.ħa wa ʕaː.fi.ja/", katakana: "スィッハ・ワ・アーフィヤ", romanization: "ṣiḥḥa wa ʿāfiya", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "th", text: "ทานให้อร่อยนะครับ/คะ", meaning: "请慢用 / 祝您吃得开心", ipa: "/tʰaːn hâj ʔa.rɔ̀j ná kʰráp/ / /tʰaːn hâj ʔa.rɔ̀j ná kʰáʔ/", katakana: "ターン・ハイ・アロイ・ナ・クラップ / カ", romanization: "than hai aroi na khrap / kha", audioFile: null, scenario: "上菜后或客人准备开始用餐时使用，语气亲切自然，适合酒店和餐厅服务。", knowledge: "男性说「ทานให้อร่อยนะครับ」，女性说「ทานให้อร่อยนะคะ」。这里女性结尾是「นะคะ」，不能写成「นะค่ะ」。你本人使用男性形式即可。", derived: [{ text: "ขอให้ทานอาหารให้อร่อยนะครับ/คะ", meaning: "祝您用餐愉快，较完整", ipa: "/kʰɔ̌ː hâj tʰaːn ʔaː.hǎːn hâj ʔa.rɔ̀j ná kʰráp/ / /kʰɔ̌ː hâj tʰaːn ʔaː.hǎːn hâj ʔa.rɔ̀j ná kʰáʔ/", katakana: "コー・ハイ・ターン・アーハーン・ハイ・アロイ・ナ・クラップ / カ", romanization: "kho hai than ahan hai aroi na khrap / kha", audioFile: null }, { text: "เชิญทานได้เลยครับ/ค่ะ", meaning: "请开始享用", ipa: "/tɕʰɤːn tʰaːn dâːj lɤːj kʰráp/ / /tɕʰɤːn tʰaːn dâːj lɤːj kʰâː/", katakana: "チューン・ターン・ダイ・ルーイ・クラップ / カー", romanization: "choen than dai loei khrap / kha", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "pt", text: "Bom apetite", meaning: "请慢用 / 祝您用餐愉快", ipa: "/bõ apeˈtʃi.tʃi/", katakana: "ボン・アペチーチ", romanization: "bom apetite", audioFile: null, scenario: "上菜后祝客人用餐愉快，是葡萄牙和巴西餐厅最自然、最常见的表达。", knowledge: "「Bom apetite」相当于法语 Bon appétit，适用于酒店、餐厅和家庭聚餐。若希望表达更具服务感，可补一句「Aproveite a refeição」。", derived: [{ text: "Aproveite a refeição", meaning: "请享用您的餐点", ipa: "/apɾovejˈtʃi a ʁefejˈsɐ̃w̃/", katakana: "アプロヴェイチ・ア・ヘフェイサォン", romanization: "aproveite a refeição", audioFile: null }, { text: "Espero que goste", meaning: "希望您会喜欢", ipa: "/esˈpɛɾu ki ˈɡɔs.tʃi/", katakana: "エスペロ・キ・ゴスチ", romanization: "espero que goste", audioFile: null }], status: "reviewed" },
{ chinese: "请慢用", lang: "he", text: "בתיאבון", meaning: "请慢用 / 祝您用餐愉快", ipa: "/be.te.aˈvon/", katakana: "ベテアヴォン", romanization: "bete'avon", audioFile: null, scenario: "上菜后祝客人用餐愉快，是现代希伯来语餐厅和家庭最自然、最常见的表达。", knowledge: "「בתיאבון」相当于英语 Enjoy your meal 或法语 Bon appétit，无论男女、人数多少都可直接使用，是以色列餐厅最标准的说法。", derived: [{ text: "בתיאבון, תהנו", meaning: "请慢用，祝您享用愉快", ipa: "/be.te.aˈvon te.heˈnu/", katakana: "ベテアヴォン・テヘヌ", romanization: "bete'avon, tehenu", audioFile: null }, { text: "מקווה שיהיה טעים", meaning: "希望您会喜欢", ipa: "/mikˈve she.jiˈje taˈim/", katakana: "ミクヴェ・シェイイェ・タイーム", romanization: "mikve sheyihye ta'im", audioFile: null }], status: "reviewed" },


      // ── 非常感谢 ──
{ chinese: "非常感谢", lang: "ko", text: "대단히 감사합니다", meaning: "非常感谢", ipa: "/tɛ.da.ni kam.sa.ham.ni.da/", katakana: "テダニ・カムサハムニダ", romanization: "daedanhi gamsahamnida", audioFile: null, scenario: "向客人表达较郑重的感谢，例如客人给予理解、配合或帮助时使用。", knowledge: "「대단히 감사합니다」比普通的「감사합니다」更加正式郑重，适合酒店、航空、百货等正式服务场合。", derived: [{ text: "정말 감사합니다", meaning: "真的非常感谢，语气诚恳自然", ipa: "/tɕʌŋ.mal kam.sa.ham.ni.da/", katakana: "チョンマル・カムサハムニダ", romanization: "jeongmal gamsahamnida", audioFile: null }, { text: "감사합니다", meaning: "谢谢，标准礼貌表达", ipa: "/kam.sa.ham.ni.da/", katakana: "カムサハムニダ", romanization: "gamsahamnida", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "yue", text: "多謝晒", meaning: "非常感谢", ipa: "/tɔː⁵⁵ tsɛː²² saːi̯³³/", katakana: "ドー・ジェー・サーイ", romanization: "do1 ze6 saai3", audioFile: null, scenario: "向客人表达诚挚感谢，例如客人给予帮助、理解、好评或配合时使用。", knowledge: "粤语口语中「多謝晒」比直接说「非常感謝」自然得多。「多謝」主要用于感谢礼物、帮助、称赞或他人给予的事物；「唔該」则常用于感谢服务、劳烦或小帮助。", derived: [{ text: "真係好多謝", meaning: "真的非常感谢，语气更诚恳", ipa: "/tsɐn⁵⁵ hɐi̯²² hou̯³⁵ tɔː⁵⁵ tsɛː²²/", katakana: "ザンハイ・ホウ・ドージェー", romanization: "zan1 hai6 hou2 do1 ze6", audioFile: null }, { text: "唔該晒", meaning: "非常感谢您的帮忙或服务", ipa: "/m̩²¹ kɔːi̯⁵⁵ saːi̯³³/", katakana: "ンーゴイ・サーイ", romanization: "m4 goi1 saai3", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "en", text: "Thank you very much", meaning: "非常感谢", ipa: "/ˈθæŋk juː ˈver.i mʌtʃ/", katakana: "サンキュー・ヴェリー・マッチ", romanization: "Thank you very much", audioFile: null, scenario: "向客人表达真诚感谢，例如客人给予帮助、耐心等待、理解或配合时使用。", knowledge: "这是正式稳妥的感谢表达。服务现场也常用语气较温暖的「Thank you so much」；感谢对方的理解或配合时，也可以使用「We really appreciate it」。", derived: [{ text: "Thank you so much", meaning: "真的非常感谢，语气温暖自然", ipa: "/ˈθæŋk juː soʊ mʌtʃ/", katakana: "サンキュー・ソー・マッチ", romanization: "Thank you so much", audioFile: null }, { text: "We really appreciate it", meaning: "我们对此非常感激", ipa: "/wiː ˈrɪə.li əˈpriː.ʃi.eɪt ɪt/", katakana: "ウィー・リアリー・アプリーシエイト・イット", romanization: "We really appreciate it", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "de", text: "Vielen Dank", meaning: "非常感谢", ipa: "/ˈfiːlən daŋk/", katakana: "フィーレン・ダンク", romanization: "Vielen Dank", audioFile: null, scenario: "向客人表达感谢，适合酒店、餐厅、商店及一般正式服务场合。", knowledge: "「Vielen Dank」是自然、礼貌且通用的感谢表达。想强调衷心感谢时，可以使用「Herzlichen Dank」。", derived: [{ text: "Herzlichen Dank", meaning: "衷心感谢，语气更郑重", ipa: "/ˈhɛʁt͡slɪçn̩ daŋk/", katakana: "ヘルツリヒェン・ダンク", romanization: "Herzlichen Dank", audioFile: null }, { text: "Ich danke Ihnen", meaning: "我感谢您，正式表达", ipa: "/ɪç ˈdaŋkə ˈiːnən/", katakana: "イヒ・ダンケ・イーネン", romanization: "Ich danke Ihnen", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "fr", text: "Merci beaucoup", meaning: "非常感谢", ipa: "/mɛʁ.si bo.ku/", katakana: "メルスィー・ボクー", romanization: "Merci beaucoup", audioFile: null, scenario: "向客人表达感谢，适合酒店、餐厅及一般正式服务场合。", knowledge: "这是法语中最通用自然的「非常感谢」。需要更正式完整地表达时，可以使用「Je vous remercie」。", derived: [{ text: "Je vous remercie", meaning: "我向您表示感谢，较正式", ipa: "/ʒə vu ʁə.mɛʁ.si/", katakana: "ジュ・ヴ・ルメルスィ", romanization: "Je vous remercie", audioFile: null }, { text: "Merci infiniment", meaning: "万分感谢，语气较强", ipa: "/mɛʁ.si ɛ̃.fi.ni.mɑ̃/", katakana: "メルスィー・アンフィニマン", romanization: "Merci infiniment", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "es", text: "Muchas gracias", meaning: "非常感谢", ipa: "/ˈmu.tʃas ˈɡɾa.sjas/", katakana: "ムーチャス・グラスィアス", romanization: "Muchas gracias", audioFile: null, scenario: "向客人表达感谢，适合酒店、餐厅及一般正式服务场合。", knowledge: "这是西班牙语中最通用自然的郑重感谢表达。需要表达个人的正式感谢时，可以使用「Se lo agradezco mucho」。", derived: [{ text: "Se lo agradezco mucho", meaning: "我对此非常感谢您，正式礼貌", ipa: "/se lo a.ɣɾaˈðes.ko ˈmu.tʃo/", katakana: "セ・ロ・アグラデスコ・ムーチョ", romanization: "Se lo agradezco mucho", audioFile: null }, { text: "Muchísimas gracias", meaning: "万分感谢，强调程度更强", ipa: "/muˈtʃi.si.mas ˈɡɾa.sjas/", katakana: "ムチスィマス・グラスィアス", romanization: "Muchísimas gracias", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "it", text: "Grazie mille", meaning: "非常感谢", ipa: "/ˈɡrat.tsje ˈmil.le/", katakana: "グラッツィエ・ミッレ", romanization: "Grazie mille", audioFile: null, scenario: "向客人表达感谢，适合酒店、餐厅及一般服务场合。", knowledge: "「Grazie mille」字面有「千次感谢」之意，是自然常用的强烈感谢表达。更正式时可以说「La ringrazio molto」。", derived: [{ text: "La ringrazio molto", meaning: "我非常感谢您，正式礼貌", ipa: "/la riŋˈɡrat.tsjo ˈmol.to/", katakana: "ラ・リングラッツィオ・モルト", romanization: "La ringrazio molto", audioFile: null }, { text: "Grazie di cuore", meaning: "衷心感谢", ipa: "/ˈɡrat.tsje di ˈkwɔː.re/", katakana: "グラッツィエ・ディ・クオーレ", romanization: "Grazie di cuore", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "ru", text: "Большое спасибо", meaning: "非常感谢", ipa: "/bɐlʲˈʂo.jə spɐˈsʲibə/", katakana: "バリショーエ・スパスィーバ", romanization: "Bolshoye spasibo", audioFile: null, scenario: "向客人表达感谢，适合酒店、餐厅及一般正式服务场合。", knowledge: "这是俄语中自然、常见且礼貌的「非常感谢」。若想使用更正式的表达，可以说「Благодарю вас」。", derived: [{ text: "Благодарю вас", meaning: "我感谢您，较正式", ipa: "/bləɡədɐˈrʲu vas/", katakana: "ブラガダリュー・ヴァス", romanization: "Blagodaryu vas", audioFile: null }, { text: "Огромное спасибо", meaning: "万分感谢，强调程度很强", ipa: "/ɐˈɡromnəjə spɐˈsʲibə/", katakana: "アグロームナエ・スパスィーバ", romanization: "Ogromnoye spasibo", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "ar", text: "شكراً جزيلاً", meaning: "非常感谢", ipa: "/ʃuk.ran d͡ʒa.ziː.lan/", katakana: "シュクラン・ジャズィーラン", romanization: "shukran jazīlan", audioFile: null, scenario: "向客人表达较郑重的感谢，适合酒店、机场、餐厅及商务接待等正式场合。", knowledge: "「شكراً جزيلاً」是现代标准阿拉伯语中广泛通用的郑重感谢表达。不同地区的口语发音可能略有差异。", derived: [{ text: "شكراً لكم", meaning: "感谢各位 / 感谢您们", ipa: "/ʃuk.ran la.kum/", katakana: "シュクラン・ラクム", romanization: "shukran lakum", audioFile: null }, { text: "أشكرك كثيراً", meaning: "我非常感谢您，对一位男性使用", ipa: "/ʔaʃ.ku.ru.ka ka.θiː.ran/", katakana: "アシュクルカ・カスィーラン", romanization: "ashkuruka kathīran", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "th", text: "ขอบคุณมากครับ/ค่ะ", meaning: "非常感谢", ipa: "/kʰɔ̀ːp.kʰun mâːk kʰráp/ / /kʰɔ̀ːp.kʰun mâːk kʰâː/", katakana: "コープクン・マーク・クラップ / カー", romanization: "khop khun mak khrap / kha", audioFile: null, scenario: "向客人表达感谢，适合酒店、餐厅及一般正式服务场合。男性说ครับ，女性说ค่ะ。", knowledge: "「ขอบคุณมาก」表示非常感谢。你本人使用时说「ขอบคุณมากครับ」。更加郑重正式时，可以使用「ขอบพระคุณมากครับ/ค่ะ」。", derived: [{ text: "ขอบพระคุณมากครับ/ค่ะ", meaning: "万分感谢，语气更加郑重正式", ipa: "/kʰɔ̀ːp.pʰrá.kʰun mâːk kʰráp/ / /kʰɔ̀ːp.pʰrá.kʰun mâːk kʰâː/", katakana: "コーププラクン・マーク・クラップ / カー", romanization: "khop phrakhun mak khrap / kha", audioFile: null }, { text: "ขอบคุณครับ/ค่ะ", meaning: "谢谢，标准礼貌表达", ipa: "/kʰɔ̀ːp.kʰun kʰráp/ / /kʰɔ̀ːp.kʰun kʰâː/", katakana: "コープクン・クラップ / カー", romanization: "khop khun khrap / kha", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "pt", text: "Muito obrigado(a)", meaning: "非常感谢", ipa: "/ˈmũj.tu o.bɾiˈɡa.du(a)/", katakana: "ムイント・オブリガード（オブリガーダ）", romanization: "muito obrigado(a)", audioFile: null, scenario: "向客人表达诚挚感谢，例如入住、退房、收到配合或帮助后，是葡萄牙语服务业最常用的正式表达。", knowledge: "说话人为男性时使用「Obrigado」，女性使用「Obrigada」，与客人性别无关，而是由说话者自己的性别决定。若想表达更深的谢意，可说「Muito obrigado(a) pela sua gentileza」。", derived: [{ text: "Muito obrigado(a) pela sua gentileza", meaning: "非常感谢您的关照", ipa: "/ˈmũj.tu o.bɾiˈɡa.du(a) ˈpɛ.la su.a ʒẽ.tʃiˈle.zɐ/", katakana: "ムイント・オブリガード・ペラ・スア・ジェンチレーザ", romanization: "muito obrigado(a) pela sua gentileza", audioFile: null }, { text: "Agradecemos muito", meaning: "我们非常感谢您", ipa: "/a.ɡɾa.deˈse.mus ˈmũj.tu/", katakana: "アグラデセムス・ムイント", romanization: "agradecemos muito", audioFile: null }], status: "reviewed" },
{ chinese: "非常感谢", lang: "he", text: "תודה רבה", meaning: "非常感谢", ipa: "/toˈda ʁaˈba/", katakana: "トダー・ラバー", romanization: "todah rabah", audioFile: null, scenario: "向客人表达真诚感谢，例如办理入住、退房、收到配合或帮助后，是现代希伯来语最自然的正式感谢表达。", knowledge: "「רבה」表示『非常、很多』，整句就是『非常感谢』。男女、单复数都可以直接使用，不需要变化。", derived: [{ text: "תודה רבה לכם", meaning: "非常感谢各位", ipa: "/toˈda ʁaˈba laˈχem/", katakana: "トダー・ラバー・ラヘム", romanization: "todah rabah lakhem", audioFile: null }, { text: "אנחנו מאוד מודים לכם", meaning: "我们衷心感谢各位", ipa: "/aˈnaχ.nu meˈod moˈdim laˈχem/", katakana: "アナフヌ・メオド・モディム・ラヘム", romanization: "anachnu me'od modim lakhem", audioFile: null }], status: "reviewed" },


      // ── 不客气 ──
{ chinese: "不客气", lang: "ko", text: "별말씀을요", meaning: "哪里的话 / 不客气", ipa: "/pjʌl.mal.s͈ɯ.mɯl.jo/", katakana: "ピョルマルスムルヨ", romanization: "byeolmalsseumeulyo", audioFile: null, scenario: "回应客人的感谢时使用，语气礼貌谦逊，适合酒店、餐厅及正式接待场合。", knowledge: "教科书常将「천만에요」译为不客气，但现代韩语日常和服务现场较少使用。「별말씀을요」或简洁的「아닙니다」通常更加自然。", derived: [{ text: "아닙니다", meaning: "哪里哪里 / 不客气，简洁正式", ipa: "/a.nim.ni.da/", katakana: "アニムニダ", romanization: "animnida", audioFile: null }, { text: "도움이 되어 기쁩니다", meaning: "很高兴能帮到您", ipa: "/to.u.mi twe.ʌ ki.p͈ɯm.ni.da/", katakana: "トウミ・トェオ・キップムニダ", romanization: "doumi doeeo gippeumnida", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "yue", text: "唔使客氣", meaning: "不用客气 / 不客气", ipa: "/m̩²¹ sɐi̯³⁵ haːk̚³ hɛi̯³³/", katakana: "ンーサイ・ハーッヘイ", romanization: "m4 sai2 haak3 hei3", audioFile: null, scenario: "回应客人的感谢时使用，适合酒店、餐厅及一般服务场合。", knowledge: "「唔使客氣」是直接而礼貌的回应。「唔該」通常用于表示感谢、劳驾或提出请求，本身并不等同于回应感谢时的「不客气」。", derived: [{ text: "唔使多謝", meaning: "不用谢", ipa: "/m̩²¹ sɐi̯³⁵ tɔː⁵⁵ tsɛː²²/", katakana: "ンーサイ・ドージェー", romanization: "m4 sai2 do1 ze6", audioFile: null }, { text: "應該嘅", meaning: "这是应该的 / 分内之事", ipa: "/jɪŋ⁵⁵ kɔːi̯⁵⁵ kɛː³⁵/", katakana: "インゴイ・ゲー", romanization: "jing1 goi1 ge3", audioFile: null }, { text: "小事啫", meaning: "小事而已，较亲切口语", ipa: "/siːu̯³⁵ siː²² tsɛː⁵⁵/", katakana: "シウシー・ジェー", romanization: "siu2 si6 ze1", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "en", text: "You’re welcome", meaning: "不客气", ipa: "/jʊr ˈwel.kəm/", katakana: "ユア・ウェルカム", romanization: "You’re welcome", audioFile: null, scenario: "回应客人感谢时使用，是最标准、稳妥且通用的表达。", knowledge: "酒店服务中也常使用语气更温暖的「My pleasure」或「It’s my pleasure」。「No problem」较随意，不建议作为高端服务场合的首选。", derived: [{ text: "My pleasure", meaning: "很乐意效劳 / 这是我的荣幸", ipa: "/maɪ ˈpleʒ.ər/", katakana: "マイ・プレジャー", romanization: "My pleasure", audioFile: null }, { text: "It’s my pleasure", meaning: "这是我的荣幸，较完整正式", ipa: "/ɪts maɪ ˈpleʒ.ər/", katakana: "イッツ・マイ・プレジャー", romanization: "It’s my pleasure", audioFile: null }, { text: "I’m happy to help", meaning: "很高兴能帮到您", ipa: "/aɪm ˈhæp.i tə help/", katakana: "アイム・ハッピー・トゥ・ヘルプ", romanization: "I’m happy to help", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "de", text: "Bitte schön", meaning: "不客气", ipa: "/ˈbɪtə ʃøːn/", katakana: "ビッテ・シェーン", romanization: "Bitte schön", audioFile: null, scenario: "回应客人感谢时使用，适合酒店、餐厅、商店及一般服务场合。", knowledge: "「Bitte schön」既可表示不客气，也可在递交物品时表示请收下。较完整的回应是「Gern geschehen」。", derived: [{ text: "Gern geschehen", meaning: "乐意效劳 / 不客气", ipa: "/ɡɛʁn ɡəˈʃeːən/", katakana: "ゲルン・ゲシェーエン", romanization: "Gern geschehen", audioFile: null }, { text: "Sehr gerne", meaning: "非常乐意", ipa: "/zeːɐ̯ ˈɡɛʁnə/", katakana: "ゼーア・ゲルネ", romanization: "Sehr gerne", audioFile: null }, { text: "Nichts zu danken", meaning: "不必谢", ipa: "/nɪçt͡s tsuː ˈdaŋkən/", katakana: "ニヒツ・ツー・ダンケン", romanization: "Nichts zu danken", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "fr", text: "Je vous en prie", meaning: "不客气 / 请别客气", ipa: "/ʒə vu.zɑ̃ pʁi/", katakana: "ジュ・ヴ・ザン・プリ", romanization: "Je vous en prie", audioFile: null, scenario: "回应客人感谢时使用，语气正式礼貌，适合酒店、餐厅及其他服务场合。", knowledge: "「Je vous en prie」比「De rien」更正式，更适合面对客人。「Avec plaisir」则带有很乐意为您服务的积极语气。", derived: [{ text: "Avec plaisir", meaning: "很乐意 / 乐意效劳", ipa: "/a.vɛk plɛ.ziʁ/", katakana: "アヴェック・プレズィール", romanization: "Avec plaisir", audioFile: null }, { text: "De rien", meaning: "没什么 / 不客气，较日常", ipa: "/də ʁjɛ̃/", katakana: "ドゥ・リヤン", romanization: "De rien", audioFile: null }, { text: "Tout le plaisir est pour moi", meaning: "荣幸的是我 / 这是我的荣幸", ipa: "/tu lə plɛ.ziʁ ɛ puʁ mwa/", katakana: "トゥ・ル・プレズィール・エ・プール・モワ", romanization: "Tout le plaisir est pour moi", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "es", text: "De nada", meaning: "不客气", ipa: "/de ˈna.ða/", katakana: "デ・ナダ", romanization: "De nada", audioFile: null, scenario: "回应客人感谢时使用，是西班牙语中最通用自然的表达。", knowledge: "正式服务场合也可以使用「Con mucho gusto」，表达很乐意为您服务。不同地区还常见「No hay de qué」。", derived: [{ text: "Con mucho gusto", meaning: "非常乐意 / 乐意效劳", ipa: "/kom ˈmu.tʃo ˈɡus.to/", katakana: "コン・ムーチョ・グスト", romanization: "Con mucho gusto", audioFile: null }, { text: "Es un placer", meaning: "这是我的荣幸", ipa: "/es um plaˈseɾ/", katakana: "エス・ウン・プラセール", romanization: "Es un placer", audioFile: null }, { text: "No hay de qué", meaning: "不必客气 / 没什么", ipa: "/no ai̯ ðe ˈke/", katakana: "ノ・アイ・デ・ケ", romanization: "No hay de qué", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "it", text: "Prego", meaning: "不客气 / 请", ipa: "/ˈprɛ.ɡo/", katakana: "プレーゴ", romanization: "Prego", audioFile: null, scenario: "回应客人感谢时使用，是意大利语中最标准简洁的表达，也可用于邀请、递物或表示请。", knowledge: "「Prego」含义广泛，需要根据语境理解。回应感谢时就是不客气；引导或递交物品时则接近请、请用。", derived: [{ text: "È un piacere", meaning: "这是我的荣幸 / 很乐意", ipa: "/ɛ um pjaˈtʃe.re/", katakana: "エ・ウン・ピアチェーレ", romanization: "È un piacere", audioFile: null }, { text: "Di niente", meaning: "没什么 / 不客气", ipa: "/di ˈnjɛn.te/", katakana: "ディ・ニエンテ", romanization: "Di niente", audioFile: null }, { text: "Ci mancherebbe", meaning: "哪里的话 / 当然应该，较自然口语", ipa: "/tʃi maŋ.keˈrɛb.be/", katakana: "チ・マンケレッベ", romanization: "Ci mancherebbe", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "ru", text: "Пожалуйста", meaning: "不客气 / 请", ipa: "/pɐˈʐaɫʊstə/", katakana: "パジャールスタ", romanization: "Pozhaluysta", audioFile: null, scenario: "回应客人感谢时使用，是俄语中最标准通用的表达，也可以表示请。", knowledge: "「Пожалуйста」同时可以表示请和不客气，具体含义由语境决定。", derived: [{ text: "Не за что", meaning: "没什么 / 不用谢，较日常", ipa: "/nʲe zə ʂtə/", katakana: "ニェ・ザ・シュタ", romanization: "Ne za chto", audioFile: null }, { text: "Рад помочь", meaning: "很乐意帮忙，由男性使用", ipa: "/rat pɐˈmotɕ/", katakana: "ラート・パモーチ", romanization: "Rad pomoch", audioFile: null }, { text: "Всегда рады помочь", meaning: "我们随时乐意为您效劳", ipa: "/fsʲɪɡˈda ˈradɨ pɐˈmotɕ/", katakana: "フシグダー・ラードゥイ・パモーチ", romanization: "Vsegda rady pomoch", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "ar", text: "عفواً", meaning: "不客气", ipa: "/ʕaf.wan/", katakana: "アフワン", romanization: "ʿafwan", audioFile: null, scenario: "回应客人感谢时使用，是现代标准阿拉伯语中简洁通用的表达。", knowledge: "「عفواً」也可根据语境表示对不起、劳驾或请再说一遍。更加热情完整的回应可以使用「على الرحب والسعة」。", derived: [{ text: "على الرحب والسعة", meaning: "非常乐意 / 别客气", ipa: "/ʕa.laː ar.raħ.bi wa as.sa.ʕa/", katakana: "アラ・ッラフビ・ワッサア", romanization: "ʿalā ar-raḥbi wa-s-saʿa", audioFile: null }, { text: "لا شكر على واجب", meaning: "不用谢，这是分内之事", ipa: "/laː ʃuk.ra ʕa.laː waː.dʒib/", katakana: "ラー・シュクラ・アラー・ワージブ", romanization: "lā shukra ʿalā wājib", audioFile: null }, { text: "يسعدني ذلك", meaning: "我很乐意 / 能帮到您我很高兴", ipa: "/jus.ʕi.du.niː ðaː.lik/", katakana: "ユスイドゥニー・ザーリク", romanization: "yusʿidunī dhālik", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "th", text: "ไม่เป็นไรครับ/ค่ะ", meaning: "不客气 / 没关系", ipa: "/mâj pen raj kʰráp/ / /mâj pen raj kʰâː/", katakana: "マイ・ペン・ライ・クラップ / カー", romanization: "mai pen rai khrap / kha", audioFile: null, scenario: "回应客人的感谢时使用，语气自然亲切，也可以表示没关系、没问题。男性说ครับ，女性说ค่ะ。", knowledge: "「ไม่เป็นไร」含义较广，可表示不客气、没关系或不要紧。服务场合想表达更积极的乐意效劳时，可以使用「ด้วยความยินดีครับ/ค่ะ」。", derived: [{ text: "ด้วยความยินดีครับ/ค่ะ", meaning: "非常乐意 / 乐意效劳，较正式", ipa: "/dûaj kʰwaːm jin.diː kʰráp/ / /dûaj kʰwaːm jin.diː kʰâː/", katakana: "ドゥアイ・クワーム・インディー・クラップ / カー", romanization: "duai khwam yindi khrap / kha", audioFile: null }, { text: "ยินดีครับ/ค่ะ", meaning: "很乐意，简洁自然", ipa: "/jin.diː kʰráp/ / /jin.diː kʰâː/", katakana: "インディー・クラップ / カー", romanization: "yindi khrap / kha", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "pt", text: "De nada", meaning: "不客气", ipa: "/dʒi ˈna.dɐ/", katakana: "ヂ・ナーダ", romanization: "de nada", audioFile: null, scenario: "回应客人的感谢时使用，是葡萄牙语最自然、最普遍的表达，适用于酒店、餐厅及各类服务场合。", knowledge: "「De nada」相当于英语 You're welcome。若希望表达更具服务感，也可说「Foi um prazer」（这是我的荣幸）或「Com prazer」（很乐意）。", derived: [{ text: "Foi um prazer", meaning: "这是我的荣幸", ipa: "/foj ũ pɾaˈzeʁ/", katakana: "フォイ・ウン・プラゼール", romanization: "foi um prazer", audioFile: null }, { text: "Com prazer", meaning: "很乐意", ipa: "/kõ pɾaˈzeʁ/", katakana: "コン・プラゼール", romanization: "com prazer", audioFile: null }], status: "reviewed" },
{ chinese: "不客气", lang: "he", text: "בבקשה", meaning: "不客气", ipa: "/be.va.kaˈʃa/", katakana: "ベヴァカシャ", romanization: "bevakasha", audioFile: null, scenario: "回应客人的感谢时使用，也是现代希伯来语中最常见、最自然的表达，酒店、餐厅及商店均可使用。", knowledge: "「בבקשה」除了表示『不客气』，还可以表示『请』，和俄语「Пожалуйста」一样需要根据语境理解。", derived: [{ text: "בשמחה", meaning: "很乐意", ipa: "/be.simˈχa/", katakana: "ベシムハ", romanization: "besimcha", audioFile: null }, { text: "אין בעד מה", meaning: "不用客气 / 不必谢", ipa: "/ein beˈad ma/", katakana: "エイン・ベアド・マー", romanization: "ein be'ad ma", audioFile: null }], status: "reviewed" },


      // ── 请慢走 ──
{ chinese: "请慢走", lang: "ko", text: "안녕히 가세요", meaning: "再见 / 请走好", ipa: "/an.njʌŋ.hi ka.se.jo/", katakana: "アンニョンヒ・カセヨ", romanization: "annyeonghi gaseyo", audioFile: null, scenario: "送别离开酒店、餐厅或接待场所的客人时使用，是韩语中最标准自然的礼貌告别语。", knowledge: "「안녕히 가세요」用于对即将离开的人说。若想表达路上小心或平安回去，可以说「조심히 들어가세요」。", derived: [{ text: "조심히 들어가세요", meaning: "请小心回去 / 路上小心", ipa: "/tɕo.ɕim.hi tɯ.ɾʌ.ɡa.se.jo/", katakana: "チョシミ・トゥロガセヨ", romanization: "josimhi deureogaseyo", audioFile: null }, { text: "다음에 또 뵙겠습니다", meaning: "期待下次再见，较正式", ipa: "/ta.ɯ.me t͈o pwep̚.k͈et̚.sɯm.ni.da/", katakana: "タウメ・ット・プェプケッスムニダ", romanization: "daeume tto boepgetseumnida", audioFile: null }, { text: "다음에 또 오세요", meaning: "欢迎下次再来", ipa: "/ta.ɯ.me t͈o o.se.jo/", katakana: "タウメ・ット・オセヨ", romanization: "daeume tto oseyo", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "yue", text: "慢慢行", meaning: "请慢走 / 走好", ipa: "/maːn²² maːn²² haːŋ²¹/", katakana: "マーンマーン・ハーン", romanization: "maan6 maan6 haang4", audioFile: null, scenario: "送别离开酒店、餐厅或店铺的客人时使用，语气亲切自然。", knowledge: "「慢慢行」是粤语中常见的送别表达，不是要求对方真的放慢速度，而是带有关心意味的「走好」。正式服务场合也可配合「多謝」或「再見」使用。", derived: [{ text: "多謝，慢慢行", meaning: "谢谢，请慢走", ipa: "/tɔː⁵⁵ tsɛː²² | maːn²² maːn²² haːŋ²¹/", katakana: "ドージェー、マーンマーン・ハーン", romanization: "do1 ze6, maan6 maan6 haang4", audioFile: null }, { text: "下次再嚟", meaning: "欢迎下次再来", ipa: "/haː²² tsʰiː³³ tsɔːi³³ lɐi̯²¹/", katakana: "ハーチー・ジョイ・ライ", romanization: "haa6 ci3 zoi3 lai4", audioFile: null }, { text: "再見", meaning: "再见", ipa: "/tsɔːi³³ kiːn³³/", katakana: "ジョイギン", romanization: "zoi3 gin3", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "en", text: "Take care", meaning: "请慢走 / 保重", ipa: "/teɪk ker/", katakana: "テイク・ケア", romanization: "Take care", audioFile: null, scenario: "送别客人时表达关心，适合较自然亲切的酒店、餐厅及一般服务场合。", knowledge: "英语中没有与中文「请慢走」完全对应的固定表达。服务现场通常根据时间和行程使用「Have a wonderful day」「Have a pleasant evening」或「Safe travels」。", derived: [{ text: "Have a wonderful day", meaning: "祝您今天过得愉快", ipa: "/hæv ə ˈwʌn.dɚ.fəl deɪ/", katakana: "ハヴ・ア・ワンダフル・デイ", romanization: "Have a wonderful day", audioFile: null }, { text: "Have a pleasant evening", meaning: "祝您度过一个愉快的夜晚", ipa: "/hæv ə ˈplez.ənt ˈiːv.nɪŋ/", katakana: "ハヴ・ア・プレザント・イーブニング", romanization: "Have a pleasant evening", audioFile: null }, { text: "Safe travels", meaning: "祝您一路平安，适合即将启程的客人", ipa: "/seɪf ˈtræv.əlz/", katakana: "セイフ・トラヴェルズ", romanization: "Safe travels", audioFile: null }, { text: "We look forward to welcoming you again", meaning: "期待再次欢迎您的到来", ipa: "/wi lʊk ˈfɔːr.wɚd tə ˈwel.kəm.ɪŋ ju əˈɡen/", katakana: "ウィー・ルック・フォワード・トゥ・ウェルカミング・ユー・アゲン", romanization: "We look forward to welcoming you again", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "de", text: "Auf Wiedersehen", meaning: "再见 / 请走好", ipa: "/aʊ̯f ˈviːdɐˌzeːən/", katakana: "アウフ・ヴィーダーゼーエン", romanization: "Auf Wiedersehen", audioFile: null, scenario: "送别离开酒店、餐厅或正式接待场所的客人时使用，是德语中标准礼貌的告别语。", knowledge: "「Kommen Sie gut nach Hause」只适合明确知道客人正在回家时使用。一般服务场合更自然的是「Auf Wiedersehen」并配合时段祝福。", derived: [{ text: "Einen schönen Tag noch", meaning: "祝您接下来一天愉快", ipa: "/ˈaɪ̯nən ˈʃøːnən taːk nɔx/", katakana: "アイネン・シェーネン・ターク・ノッホ", romanization: "Einen schönen Tag noch", audioFile: null }, { text: "Einen schönen Abend noch", meaning: "祝您接下来晚上愉快", ipa: "/ˈaɪ̯nən ˈʃøːnən ˈaːbn̩t nɔx/", katakana: "アイネン・シェーネン・アーベント・ノッホ", romanization: "Einen schönen Abend noch", audioFile: null }, { text: "Kommen Sie gut nach Hause", meaning: "请平安回家", ipa: "/ˈkɔmən ziː ɡuːt naːx ˈhaʊ̯zə/", katakana: "コメン・ズィー・グート・ナーハ・ハウゼ", romanization: "Kommen Sie gut nach Hause", audioFile: null }, { text: "Wir freuen uns auf Ihren nächsten Besuch", meaning: "期待您的下次光临", ipa: "/viːɐ̯ ˈfʁɔɪ̯ən ʊns aʊ̯f ˈiːʁən ˈnɛːçstən bəˈzuːx/", katakana: "ヴィーア・フロイエン・ウンス・アウフ・イーレン・ネーヒステン・ベズーフ", romanization: "Wir freuen uns auf Ihren nächsten Besuch", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "fr", text: "Au revoir, bonne journée", meaning: "再见，祝您今天愉快", ipa: "/o ʁə.vwaʁ | bɔn ʒuʁ.ne/", katakana: "オ・ルヴォワール、ボンヌ・ジュルネ", romanization: "Au revoir, bonne journée", audioFile: null, scenario: "白天送别离开酒店、餐厅或店铺的客人时使用，是自然且礼貌的服务表达。", knowledge: "「Bonne continuation」更常用于祝对方接下来的工作、旅程或人生进展顺利，不是普通送客时的首选。傍晚或晚上应将「bonne journée」换成「bonne soirée」。", derived: [{ text: "Au revoir, bonne soirée", meaning: "再见，祝您晚上愉快", ipa: "/o ʁə.vwaʁ | bɔn swa.ʁe/", katakana: "オ・ルヴォワール、ボンヌ・ソワレ", romanization: "Au revoir, bonne soirée", audioFile: null }, { text: "Bon retour", meaning: "祝您返程顺利", ipa: "/bɔ̃ ʁə.tuʁ/", katakana: "ボン・ルトゥール", romanization: "Bon retour", audioFile: null }, { text: "À bientôt", meaning: "回头见 / 期待很快再见", ipa: "/a bjɛ̃.to/", katakana: "ア・ビヤント", romanization: "À bientôt", audioFile: null }, { text: "Au plaisir de vous accueillir à nouveau", meaning: "期待再次接待您", ipa: "/o plɛ.ziʁ də vu.z‿a.kœ.jiʁ a nu.vo/", katakana: "オ・プレズィール・ドゥ・ヴ・ザクイイール・ア・ヌヴォ", romanization: "Au plaisir de vous accueillir à nouveau", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "es", text: "Que le vaya bien", meaning: "祝您一切顺利 / 请走好", ipa: "/ke le ˈβa.ʝa βjen/", katakana: "ケ・レ・バヤ・ビエン", romanization: "Que le vaya bien", audioFile: null, scenario: "送别离开酒店、餐厅或服务场所的客人时使用，语气礼貌自然。", knowledge: "这是西班牙语中较通用的送别祝福。也可以根据时间使用「Que tenga un buen día」或「Que tenga una buena noche」。", derived: [{ text: "Que tenga un buen día", meaning: "祝您今天愉快", ipa: "/ke ˈteŋ.ɡa um bweŋ ˈdi.a/", katakana: "ケ・テンガ・ウン・ブエン・ディア", romanization: "Que tenga un buen día", audioFile: null }, { text: "Que tenga una buena noche", meaning: "祝您晚上愉快 / 晚安", ipa: "/ke ˈteŋ.ɡa ˈu.na ˈβwe.na ˈno.tʃe/", katakana: "ケ・テンガ・ウナ・ブエナ・ノチェ", romanization: "Que tenga una buena noche", audioFile: null }, { text: "Buen viaje", meaning: "一路平安 / 旅途愉快", ipa: "/bwem ˈbja.xe/", katakana: "ブエン・ビアヘ", romanization: "Buen viaje", audioFile: null }, { text: "Esperamos volver a recibirle pronto", meaning: "期待很快再次接待您", ipa: "/es.peˈɾa.mos βolˈβeɾ a re.siˈβiɾ.le ˈpɾon.to/", katakana: "エスペラモス・ボルベル・ア・レスィビルレ・プロント", romanization: "Esperamos volver a recibirle pronto", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "it", text: "Arrivederci e buona giornata", meaning: "再见，祝您今天愉快", ipa: "/ar.ri.veˈder.tʃi e ˈbwɔ.na dʒorˈna.ta/", katakana: "アッリヴェデルチ・エ・ブオナ・ジョルナータ", romanization: "Arrivederci e buona giornata", audioFile: null, scenario: "白天送别离开酒店、餐厅或正式服务场所的客人时使用。", knowledge: "傍晚或晚上应将「buona giornata」换成「buona serata」。单独使用「Arrivederci」也已经足够礼貌。", derived: [{ text: "Arrivederci e buona serata", meaning: "再见，祝您晚上愉快", ipa: "/ar.ri.veˈder.tʃi e ˈbwɔ.na seˈra.ta/", katakana: "アッリヴェデルチ・エ・ブオナ・セラータ", romanization: "Arrivederci e buona serata", audioFile: null }, { text: "Buon viaggio", meaning: "一路平安 / 旅途愉快", ipa: "/bwɔn ˈvjad.dʒo/", katakana: "ブオン・ヴィアッジョ", romanization: "Buon viaggio", audioFile: null }, { text: "Speriamo di rivederla presto", meaning: "期待很快再次见到您", ipa: "/speˈrja.mo di ri.veˈder.la ˈpre.sto/", katakana: "スペリアーモ・ディ・リヴェデルラ・プレスト", romanization: "Speriamo di rivederla presto", audioFile: null }, { text: "Stia bene", meaning: "请保重", ipa: "/ˈsti.a ˈbɛ.ne/", katakana: "スティア・ベーネ", romanization: "Stia bene", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "ru", text: "До свидания. Всего доброго", meaning: "再见，祝您一切顺利", ipa: "/də svʲɪˈdanʲɪjə | fsʲɪˈvo ˈdobrəvə/", katakana: "ダ・スヴィダーニヤ。フスィヴォー・ドーブラヴァ", romanization: "Do svidaniya. Vsego dobrogo", audioFile: null, scenario: "送别离开酒店、餐厅或正式接待场所的客人时使用，是自然礼貌的正式告别表达。", knowledge: "「Счастливого пути」更适合明确知道客人即将出发旅行时使用。普通送客时使用「До свидания」或「Всего доброго」更加自然。", derived: [{ text: "Счастливого пути", meaning: "祝您一路平安，适合即将启程的客人", ipa: "/ɕːɪsˈlʲivəvə pʊˈtʲi/", katakana: "シスリーヴァヴァ・プチー", romanization: "Schastlivogo puti", audioFile: null }, { text: "Хорошего дня", meaning: "祝您今天愉快", ipa: "/xɐˈroʂɨvə dʲnʲa/", katakana: "ハローシェヴァ・ドニャ", romanization: "Khoroshego dnya", audioFile: null }, { text: "Приходите к нам ещё", meaning: "欢迎再次光临", ipa: "/prʲɪxɐˈdʲitʲe k nam jɪˈɕːo/", katakana: "プリハヂーチェ・ク・ナム・イショー", romanization: "Prikhodite k nam yeshchyo", audioFile: null }, { text: "Берегите себя", meaning: "请保重", ipa: "/bʲɪrʲɪˈɡʲitʲe sʲɪˈbʲa/", katakana: "ビリギーチェ・スィビャー", romanization: "Beregite sebya", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "ar", text: "مع السلامة", meaning: "再见 / 一路平安", ipa: "/ma.ʕa as.sa.laː.ma/", katakana: "マア・ッサラーマ", romanization: "maʿa as-salāma", audioFile: null, scenario: "送别离开酒店、餐厅或接待场所的客人时使用，是阿拉伯语中广泛通用的告别表达。", knowledge: "字面含有「伴随平安」之意，可对即将离开的人使用。不同阿拉伯语地区的实际发音会略有差异。", derived: [{ text: "إلى اللقاء", meaning: "再见 / 下次见", ipa: "/ʔi.laː al.li.qaːʔ/", katakana: "イラー・ッリカー", romanization: "ilā al-liqāʾ", audioFile: null }, { text: "نتمنى لكم رحلة آمنة", meaning: "祝各位旅途平安", ipa: "/na.ta.man.naː la.kum riħ.la.tan ʔaː.mi.na/", katakana: "ナタマンナー・ラクム・リフラタン・アーミナ", romanization: "natamannā lakum riḥlatan āmina", audioFile: null }, { text: "نتطلع إلى الترحيب بكم مرة أخرى", meaning: "期待再次欢迎各位到来", ipa: "/na.ta.tˤal.la.ʕu ʔi.laː at.tar.ħiː.bi bi.kum mar.ra.tan ʔux.raː/", katakana: "ナタタッラウ・イラッタルヒービ・ビクム・マッラタン・ウフラー", romanization: "nataṭallaʿu ilā at-tarḥībi bikum marratan ukhrā", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "th", text: "ขอบคุณครับ/ค่ะ เดินทางปลอดภัยนะครับ/คะ", meaning: "谢谢，祝您一路平安", ipa: "/kʰɔ̀ːp.kʰun kʰráp kʰâː | dɤːn.tʰaːŋ plɔ̀ːt.pʰaj ná kʰráp kʰáʔ/", katakana: "コープクン・クラップ / カー。ドゥーンターン・プロートパイ・ナ・クラップ / カ", romanization: "khop khun khrap/kha, doen thang plotphai na khrap/kha", audioFile: null, scenario: "送别离开酒店或即将继续行程的客人时使用，兼具感谢与祝福，适合正式服务场合。", knowledge: "泰语中没有与中文「请慢走」完全相同的固定服务用语。送客时通常会表达感谢，并祝客人旅途平安。男性使用「ครับ」，女性在「นะ」后使用「คะ」。", derived: [{ text: "เดินทางปลอดภัยนะครับ/คะ", meaning: "祝您一路平安", ipa: "/dɤːn.tʰaːŋ plɔ̀ːt.pʰaj ná kʰráp/ / /dɤːn.tʰaːŋ plɔ̀ːt.pʰaj ná kʰáʔ/", katakana: "ドゥーンターン・プロートパイ・ナ・クラップ / カ", romanization: "doen thang plotphai na khrap / kha", audioFile: null }, { text: "แล้วพบกันใหม่นะครับ/คะ", meaning: "期待下次再见", ipa: "/lɛ́ːw pʰóp kan mài ná kʰráp/ / /lɛ́ːw pʰóp kan mài ná kʰáʔ/", katakana: "レーオ・ポップカン・マイ・ナ・クラップ / カ", romanization: "laeo phop kan mai na khrap / kha", audioFile: null }, { text: "หวังว่าจะได้ต้อนรับคุณอีกครั้งครับ/ค่ะ", meaning: "期待再次接待您", ipa: "/wǎŋ wâː tɕa dâːj tɔ̂ːn.ráp kʰun ʔìːk kʰráŋ kʰráp/ / /wǎŋ wâː tɕa dâːj tɔ̂ːn.ráp kʰun ʔìːk kʰráŋ kʰâː/", katakana: "ワン・ワー・ジャ・ダイ・トーンラップ・クン・イーククラン・クラップ / カー", romanization: "wang wa cha dai tonrap khun ik khrang khrap / kha", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "he", text: "דרך צלחה", meaning: "一路平安 / 请慢走", ipa: "/ˈde.reχ tslaˈχa/", katakana: "デレフ・ツラハ", romanization: "derekh tslakha", audioFile: null, scenario: "送别离开的客人时使用，相当于祝对方一路顺利，是现代希伯来语较自然的送别表达。", knowledge: "希伯来语没有完全对应日语「请慢走」的固定服务用语。酒店更常祝客人一路顺利，或配合「שלום」作为结束问候。", derived: [{ text: "להתראות", meaning: "再见", ipa: "/le.hit.raˈot/", katakana: "レヒトラオト", romanization: "lehitraot", audioFile: null }, { text: "נסיעה טובה", meaning: "一路平安（乘车、旅行）", ipa: "/ne.siˈa toˈva/", katakana: "ネシア・トヴァ", romanization: "nesi'ah tovah", audioFile: null }], status: "reviewed" },
{ chinese: "请慢走", lang: "pt", text: "Tenha um bom dia", meaning: "祝您今天愉快", ipa: "/ˈtẽ.ɲɐ ũ bõ ˈdʒi.ɐ/", katakana: "テンニャ・ウン・ボン・ジーア", romanization: "tenha um bom dia", audioFile: null, scenario: "客人离店、离开餐厅或服务结束时使用，是葡萄牙语酒店最自然的送别表达。根据时间也可替换为 Boa tarde 或 Boa noite。", knowledge: "葡萄牙语没有与日语「请慢走」完全对应的固定表达。酒店服务中通常祝客人今天愉快，或祝一路平安，比直译更自然。", derived: [{ text: "Volte sempre", meaning: "欢迎再次光临", ipa: "/ˈvɔw.tʃi ˈsẽ.pɾi/", katakana: "ヴォウチ・センプリ", romanization: "volte sempre", audioFile: null }, { text: "Boa viagem", meaning: "一路平安", ipa: "/ˈbo.ɐ vi.aˈʒẽj̃/", katakana: "ボア・ヴィアジェン", romanization: "boa viagem", audioFile: null }], status: "reviewed" },


     // ── 再见 ──
{ chinese: "再见", lang: "ko", text: "안녕히 가세요", meaning: "再见 / 请走好", ipa: "/an.njʌŋ.hi ka.se.jo/", katakana: "アンニョンヒ・カセヨ", romanization: "annyeonghi gaseyo", audioFile: null, scenario: "送别离开酒店、餐厅或接待场所的客人时使用，说话者留在原处。", knowledge: "「안녕히 가세요」用于对离开的人说；若自己离开、对方留下，则说「안녕히 계세요」。服务现场送客时通常使用前者。", derived: [{ text: "다음에 또 뵙겠습니다", meaning: "期待下次再见，正式礼貌", ipa: "/ta.ɯ.me t͈o pwep̚.k͈et̚.sɯm.ni.da/", katakana: "タウメ・ット・プェプケッスムニダ", romanization: "daeume tto boepgetseumnida", audioFile: null }, { text: "안녕히 계세요", meaning: "再见，请留步；自己离开时对留下的人说", ipa: "/an.njʌŋ.hi kje.se.jo/", katakana: "アンニョンヒ・ケセヨ", romanization: "annyeonghi gyeseyo", audioFile: null }, { text: "또 뵙겠습니다", meaning: "期待再次见到您", ipa: "/t͈o pwep̚.k͈et̚.sɯm.ni.da/", katakana: "ット・プェプケッスムニダ", romanization: "tto boepgetseumnida", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "yue", text: "再見", meaning: "再见", ipa: "/tsɔːi³³ kiːn³³/", katakana: "ジョイギン", romanization: "zoi3 gin3", audioFile: null, scenario: "送别离开酒店、餐厅或接待场所的客人时使用，正式且通用。", knowledge: "日常粤语也常说「拜拜」，但正式服务场合使用「再見」更稳妥。可配合「多謝」或「慢慢行」使语气更温暖。", derived: [{ text: "多謝，再見", meaning: "谢谢，再见", ipa: "/tɔː⁵⁵ tsɛː²² | tsɔːi³³ kiːn³³/", katakana: "ドージェー、ジョイギン", romanization: "do1 ze6, zoi3 gin3", audioFile: null }, { text: "下次見", meaning: "下次见", ipa: "/haː²² tsʰiː³³ kiːn³³/", katakana: "ハーチー・ギン", romanization: "haa6 ci3 gin3", audioFile: null }, { text: "拜拜", meaning: "拜拜，较口语亲切", ipa: "/paːi³³ paːi³³/", katakana: "バーイバーイ", romanization: "baai1 baai3", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "en", text: "Goodbye", meaning: "再见", ipa: "/ˌɡʊdˈbaɪ/", katakana: "グッドバイ", romanization: "Goodbye", audioFile: null, scenario: "送别客人时使用，是清楚、正式且通用的告别表达。", knowledge: "单独说「Goodbye」有时显得稍正式或带有结束感。酒店服务中通常会配合时段祝福，例如「Goodbye. Have a wonderful day」。", derived: [{ text: "Goodbye. Have a wonderful day", meaning: "再见，祝您今天愉快", ipa: "/ˌɡʊdˈbaɪ | hæv ə ˈwʌn.dɚ.fəl deɪ/", katakana: "グッドバイ。ハヴ・ア・ワンダフル・デイ", romanization: "Goodbye. Have a wonderful day", audioFile: null }, { text: "We hope to see you again", meaning: "期待再次见到您", ipa: "/wi hoʊp tə siː ju əˈɡen/", katakana: "ウィー・ホープ・トゥ・スィー・ユー・アゲン", romanization: "We hope to see you again", audioFile: null }, { text: "See you again", meaning: "期待再见，较亲切", ipa: "/siː ju əˈɡen/", katakana: "スィー・ユー・アゲン", romanization: "See you again", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "de", text: "Auf Wiedersehen", meaning: "再见", ipa: "/aʊ̯f ˈviːdɐˌzeːən/", katakana: "アウフ・ヴィーダーゼーエン", romanization: "Auf Wiedersehen", audioFile: null, scenario: "送别酒店、餐厅或其他正式服务场所的客人时使用，是标准礼貌表达。", knowledge: "面对客人应优先使用「Auf Wiedersehen」。「Tschüss」较随意；电话结束时则使用「Auf Wiederhören」。", derived: [{ text: "Auf Wiederhören", meaning: "再见，电话中使用", ipa: "/aʊ̯f ˈviːdɐˌhøːʁən/", katakana: "アウフ・ヴィーダーヘーレン", romanization: "Auf Wiederhören", audioFile: null }, { text: "Bis zum nächsten Mal", meaning: "下次见", ipa: "/bɪs tsʊm ˈnɛːçstən maːl/", katakana: "ビス・ツム・ネーヒステン・マール", romanization: "Bis zum nächsten Mal", audioFile: null }, { text: "Auf Wiedersehen und einen schönen Tag noch", meaning: "再见，祝您接下来一天愉快", ipa: "/aʊ̯f ˈviːdɐˌzeːən ʊnt ˈaɪ̯nən ˈʃøːnən taːk nɔx/", katakana: "アウフ・ヴィーダーゼーエン・ウント・アイネン・シェーネン・ターク・ノッホ", romanization: "Auf Wiedersehen und einen schönen Tag noch", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "fr", text: "Au revoir", meaning: "再见", ipa: "/o ʁə.vwaʁ/", katakana: "オ・ルヴォワール", romanization: "Au revoir", audioFile: null, scenario: "送别酒店、餐厅或商店的客人时使用，是法语中标准且礼貌的告别表达。", knowledge: "服务现场常在「Au revoir」后加上「Bonne journée」或「Bonne soirée」。若确实期待不久后再次见面，可以说「À bientôt」。", derived: [{ text: "Au revoir, bonne journée", meaning: "再见，祝您今天愉快", ipa: "/o ʁə.vwaʁ | bɔn ʒuʁ.ne/", katakana: "オ・ルヴォワール、ボンヌ・ジュルネ", romanization: "Au revoir, bonne journée", audioFile: null }, { text: "Au revoir, bonne soirée", meaning: "再见，祝您晚上愉快", ipa: "/o ʁə.vwaʁ | bɔn swa.ʁe/", katakana: "オ・ルヴォワール、ボンヌ・ソワレ", romanization: "Au revoir, bonne soirée", audioFile: null }, { text: "À bientôt", meaning: "回头见 / 期待很快再见", ipa: "/a bjɛ̃.to/", katakana: "ア・ビヤント", romanization: "À bientôt", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "es", text: "Hasta luego", meaning: "再见 / 回头见", ipa: "/ˈas.ta ˈlwe.ɣo/", katakana: "アスタ・ルエゴ", romanization: "Hasta luego", audioFile: null, scenario: "送别酒店、餐厅或一般服务场所的客人时使用，比单独说「Adiós」更自然亲切。", knowledge: "「Adiós」并非错误，但有时带有分别时间较长或结束感较强的语气。服务现场通常更常用「Hasta luego」并配合时段祝福。", derived: [{ text: "Hasta pronto", meaning: "期待很快再见", ipa: "/ˈas.ta ˈpɾon.to/", katakana: "アスタ・プロント", romanization: "Hasta pronto", audioFile: null }, { text: "Que tenga un buen día", meaning: "祝您今天愉快", ipa: "/ke ˈteŋ.ɡa um bweŋ ˈdi.a/", katakana: "ケ・テンガ・ウン・ブエン・ディア", romanization: "Que tenga un buen día", audioFile: null }, { text: "Esperamos verle de nuevo", meaning: "期待再次见到您", ipa: "/es.peˈɾa.mos ˈβeɾ.le ðe ˈnwe.βo/", katakana: "エスペラモス・ベルレ・デ・ヌエボ", romanization: "Esperamos verle de nuevo", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "it", text: "Arrivederci", meaning: "再见", ipa: "/ar.ri.veˈder.tʃi/", katakana: "アッリヴェデルチ", romanization: "Arrivederci", audioFile: null, scenario: "送别酒店、餐厅或正式服务场所的客人时使用，是标准礼貌表达。", knowledge: "「Ciao」较随意，不建议作为对初次见面客人的首选。「ArrivederLa」更加正式，但现代服务现场一般使用「Arrivederci」已足够礼貌。", derived: [{ text: "Arrivederci e buona giornata", meaning: "再见，祝您今天愉快", ipa: "/ar.ri.veˈder.tʃi e ˈbwɔ.na dʒorˈna.ta/", katakana: "アッリヴェデルチ・エ・ブオナ・ジョルナータ", romanization: "Arrivederci e buona giornata", audioFile: null }, { text: "Arrivederci e buona serata", meaning: "再见，祝您晚上愉快", ipa: "/ar.ri.veˈder.tʃi e ˈbwɔ.na seˈra.ta/", katakana: "アッリヴェデルチ・エ・ブオナ・セラータ", romanization: "Arrivederci e buona serata", audioFile: null }, { text: "A presto", meaning: "回头见 / 期待很快再见", ipa: "/a ˈpre.sto/", katakana: "ア・プレスト", romanization: "A presto", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "ru", text: "До свидания", meaning: "再见", ipa: "/də svʲɪˈdanʲɪjə/", katakana: "ダ・スヴィダーニヤ", romanization: "Do svidaniya", audioFile: null, scenario: "送别酒店、餐厅或正式服务场所的客人时使用，是俄语中标准礼貌的告别表达。", knowledge: "「Пока」较随意，适合熟人或朋友，不建议对客人使用。服务现场可在「До свидания」后补充一天愉快或一切顺利。", derived: [{ text: "До свидания. Всего доброго", meaning: "再见，祝您一切顺利", ipa: "/də svʲɪˈdanʲɪjə | fsʲɪˈvo ˈdobrəvə/", katakana: "ダ・スヴィダーニヤ。フスィヴォー・ドーブラヴァ", romanization: "Do svidaniya. Vsego dobrogo", audioFile: null }, { text: "До новых встреч", meaning: "期待下次再见", ipa: "/də ˈnovɨx fstrʲetɕ/", katakana: "ダ・ノーヴィフ・フストレーチ", romanization: "Do novykh vstrech", audioFile: null }, { text: "Хорошего дня", meaning: "祝您今天愉快", ipa: "/xɐˈroʂɨvə dʲnʲa/", katakana: "ハローシェヴァ・ドニャ", romanization: "Khoroshego dnya", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "ar", text: "مع السلامة", meaning: "再见 / 一路平安", ipa: "/ma.ʕa as.sa.laː.ma/", katakana: "マア・ッサラーマ", romanization: "maʿa as-salāma", audioFile: null, scenario: "送别离开酒店、餐厅或接待场所的客人时使用，是阿拉伯语地区广泛通用的告别表达。", knowledge: "「وداعاً」虽然可译为再见，但较书面，且容易带有长期分别或最终告别的感觉。一般服务现场使用「مع السلامة」更自然。", derived: [{ text: "إلى اللقاء", meaning: "再见 / 下次见", ipa: "/ʔi.laː al.li.qaːʔ/", katakana: "イラー・ッリカー", romanization: "ilā al-liqāʾ", audioFile: null }, { text: "نتمنى أن نراكم مرة أخرى", meaning: "期待再次见到各位", ipa: "/na.ta.man.naː ʔan na.raː.kum mar.ra.tan ʔux.raː/", katakana: "ナタマンナー・アン・ナラークム・マッラタン・ウフラー", romanization: "natamannā an narākum marratan ukhrā", audioFile: null }, { text: "يوماً سعيداً", meaning: "祝您今天愉快", ipa: "/jaw.man sa.ʕiː.dan/", katakana: "ヤウマン・サイーダン", romanization: "yawman saʿīdan", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "th", text: "ขอบคุณครับ/ค่ะ สวัสดีครับ/ค่ะ", meaning: "谢谢，再见", ipa: "/kʰɔ̀ːp.kʰun kʰráp kʰâː | sà.wàt.diː kʰráp kʰâː/", katakana: "コープクン・クラップ / カー。サワッディー・クラップ / カー", romanization: "khop khun khrap/kha, sawatdee khrap/kha", audioFile: null, scenario: "送别离开酒店、餐厅或接待场所的客人时使用，是比单独说「ลาก่อน」更自然的服务表达。", knowledge: "泰语的「สวัสดีครับ/ค่ะ」既可用于见面问候，也可用于礼貌告别。「ลาก่อน」虽然字面是再见，但通常带有分别较久或较郑重的感觉，不是日常服务送客的首选。", derived: [{ text: "สวัสดีครับ/ค่ะ", meaning: "再见，礼貌通用", ipa: "/sà.wàt.diː kʰráp/ / /sà.wàt.diː kʰâː/", katakana: "サワッディー・クラップ / カー", romanization: "sawatdee khrap / kha", audioFile: null }, { text: "แล้วพบกันใหม่นะครับ/คะ", meaning: "期待下次再见", ipa: "/lɛ́ːw pʰóp kan mài ná kʰráp/ / /lɛ́ːw pʰóp kan mài ná kʰáʔ/", katakana: "レーオ・ポップカン・マイ・ナ・クラップ / カ", romanization: "laeo phop kan mai na khrap / kha", audioFile: null }, { text: "หวังว่าจะได้พบกันอีกครับ/ค่ะ", meaning: "期待再次见到您", ipa: "/wǎŋ wâː tɕa dâːj pʰóp kan ʔìːk kʰráp/ / /wǎŋ wâː tɕa dâːj pʰóp kan ʔìːk kʰâː/", katakana: "ワン・ワー・ジャ・ダイ・ポップカン・イーク・クラップ / カー", romanization: "wang wa cha dai phop kan ik khrap / kha", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "pt", text: "Até logo", meaning: "再见", ipa: "/aˈtɛ ˈlɔ.ɡu/", katakana: "アテ・ローゴ", romanization: "até logo", audioFile: null, scenario: "送别离店或离开餐厅的客人时使用，是葡萄牙语服务业中最自然、最常见的再见表达。", knowledge: "「Até logo」字面意思是「待会儿见」，但实际相当于日常的「再见」。酒店服务中通常还会搭配「Tenha um bom dia」或「Volte sempre」等送别语。", derived: [{ text: "Tenha um bom dia", meaning: "祝您今天愉快", ipa: "/ˈtẽ.ɲɐ ũ bõ ˈdʒi.ɐ/", katakana: "テンニャ・ウン・ボン・ジーア", romanization: "tenha um bom dia", audioFile: null }, { text: "Volte sempre", meaning: "欢迎再次光临", ipa: "/ˈvɔw.tʃi ˈsẽ.pɾi/", katakana: "ヴォウチ・センプリ", romanization: "volte sempre", audioFile: null }], status: "reviewed" },
{ chinese: "再见", lang: "he", text: "להתראות", meaning: "再见", ipa: "/le.hit.raˈot/", katakana: "レヒトラオト", romanization: "lehitraot", audioFile: null, scenario: "送别离开的客人时使用，是现代希伯来语最标准、最自然的正式再见表达。", knowledge: "「להתראות」字面意思是「期待再次相见」，男女、人数都不需要变化，适用于酒店、餐厅及正式服务场合。", derived: [{ text: "יום טוב", meaning: "祝您今天愉快", ipa: "/jom tov/", katakana: "ヨム・トヴ", romanization: "yom tov", audioFile: null }, { text: "שלום", meaning: "再见（亦可表示你好）", ipa: "/ʃaˈlom/", katakana: "シャローム", romanization: "shalom", audioFile: null }], status: "reviewed" },

    ];
