/*
 * 服务用语词库 — 在此追加 phrases 条目
 * 必填: chinese, lang, text, meaning, ipa, katakana, romanization, scenario, knowledge, derived
 * 可选: audioFile (mp3 路径，有则优先播放)
 */

const LANGUAGES = [
      { id: "ko", name: "韩语", lang: "ko-KR" },
      { id: "yue", name: "粤语", lang: "zh-HK" },
      { id: "en", name: "英语", lang: "en-US" },
      { id: "de", name: "德语", lang: "de-DE" },
      { id: "fr", name: "法语", lang: "fr-FR" },
      { id: "es", name: "西班牙语", lang: "es-ES" },
      { id: "it", name: "意大利语", lang: "it-IT" },
      { id: "ru", name: "俄语", lang: "ru-RU" },
      { id: "ar", name: "阿拉伯语", lang: "ar-SA" },
      { id: "th", name: "泰语", lang: "th-TH" }
    ];

    /*
     * phrases 数组 — 追加新条目只需 push 同结构对象
     * 必填: chinese, lang, text, meaning, ipa, katakana, romanization, scenario, knowledge, derived
     * 可选: audioFile (mp3 路径，有则优先播放)
     */


const phrases = [
      // ── 您好 ──
      { chinese: "您好", lang: "ko", text: "안녕하세요", meaning: "您好（礼貌问候）", ipa: "an.njʌŋ.ha.se.jo", katakana: "アンニョンハセヨ", romanization: "annyeonghaseyo", audioFile: null, scenario: "进店、接电话、面对顾客时的标准问候。比「안녕」更正式。", knowledge: "「세요」是敬语结尾。对长辈、顾客、上司使用。同事间熟络后可用「안녕하세요」或简化为「안녕」。", derived: [{ text: "안녕하십니까", meaning: "更正式的问候（广播、正式场合）" }, { text: "반갑습니다", meaning: "见到您很高兴" }] },
      { chinese: "您好", lang: "yue", text: "您好", meaning: "您好（正式问候）", ipa: "nei5 hou2", katakana: "ネイホウ", romanization: "nei5 hou2 / nei hou", audioFile: null, scenario: "粤语区服务业标准问候，适用于酒店、餐厅、商场。", knowledge: "「您」比「你」更尊重。口语也可说「你好」，但「您好」更正式。", derived: [{ text: "早晨", meaning: "早上好（粤语常用）" }, { text: "午安", meaning: "下午好" }] },
      { chinese: "您好", lang: "en", text: "Hello", meaning: "您好", ipa: "həˈloʊ", katakana: "ハロウ", romanization: "hello", audioFile: null, scenario: "通用问候，适用于零售、酒店前台、电话接听。", knowledge: "服务业中可配合微笑与眼神接触。对熟客可说 \"Hi\" 或 \"Good to see you\"。", derived: [{ text: "Good day", meaning: "祝您有美好的一天（较正式）" }, { text: "How may I help you?", meaning: "有什么可以帮您？" }] },
      { chinese: "您好", lang: "de", text: "Guten Tag", meaning: "您好（日安）", ipa: "ˈɡuːtən taːk", katakana: "グーテンターク", romanization: "Guten Tag", audioFile: null, scenario: "白天正式问候，适用于商店、银行、酒店。", knowledge: "字面意为「美好的一天」。早晨用 Guten Morgen，傍晚用 Guten Abend。", derived: [{ text: "Grüß Gott", meaning: "您好（奥地利、巴伐利亚）" }, { text: "Hallo", meaning: "你好（较随意）" }] },
      { chinese: "您好", lang: "fr", text: "Bonjour", meaning: "您好 / 日安", ipa: "bɔ̃.ʒuʁ", katakana: "ボンジュール", romanization: "bonjour", audioFile: null, scenario: "进入店铺、餐厅或开始对话时的必备问候。", knowledge: "法国文化中，进店必须说 Bonjour，否则可能被视为无礼。傍晚后用 Bonsoir。", derived: [{ text: "Enchanté(e)", meaning: "幸会" }, { text: "Bienvenue", meaning: "欢迎" }] },
      { chinese: "您好", lang: "es", text: "Buenos días", meaning: "您好 / 早上好", ipa: "ˈbwe.nos ˈdi.as", katakana: "ブエノスディアス", romanization: "buenos días", audioFile: null, scenario: "白天问候顾客的标准用语，适用于酒店、餐厅。", knowledge: "下午用 Buenas tardes，晚上用 Buenas noches。拉丁美洲同样通用。", derived: [{ text: "Hola", meaning: "你好（较随意）" }, { text: "¿En qué puedo ayudarle?", meaning: "有什么可以帮您？" }] },
      { chinese: "您好", lang: "it", text: "Buongiorno", meaning: "您好 / 日安", ipa: "ˌbwɔnˈdʒɔr.no", katakana: "ボンジョルノ", romanization: "buongiorno", audioFile: null, scenario: "白天正式问候，进入商店或开始服务时使用。", knowledge: "傍晚后改用 Buonasera。对年轻人或非正式场合可用 Ciao。", derived: [{ text: "Salve", meaning: "您好（介于正式与随意之间）" }, { text: "Piacere", meaning: "幸会" }] },
      { chinese: "您好", lang: "ru", text: "Здравствуйте", meaning: "您好", ipa: "zdraˈstvujtʲe", katakana: "ズドラーストヴイチェ", romanization: "zdravstvuyte", audioFile: null, scenario: "对陌生人、顾客的正式问候，服务业标准用语。", knowledge: "复数/敬语形式。对熟人单数用 Здравствуй。源自「祝您健康」。", derived: [{ text: "Добрый день", meaning: "日安（稍随意）" }, { text: "Привет", meaning: "你好（非正式）" }] },
      { chinese: "您好", lang: "ar", text: "السلام عليكم", meaning: "愿平安归于您", ipa: "as.sa.laː.mu ʕa.laj.kum", katakana: "アッサラームアレイクム", romanization: "as-salāmu ʿalaykum", audioFile: null, scenario: "穆斯林地区及阿拉伯国家通用问候，表示尊重与祝福。", knowledge: "对方常回「وعليكم السلام wa ʿalaykum as-salām」。非穆斯林顾客同样可使用，显示文化尊重。", derived: [{ text: "أهلاً وسهلاً", meaning: "欢迎" }, { text: "مرحباً", meaning: "你好" }] },
      { chinese: "您好", lang: "th", text: "สวัสดีครับ/ค่ะ", meaning: "您好", ipa: "sa.wat.diː kʰrap̚/kʰa", katakana: "サワッディークラップ/カー", romanization: "sawatdi khrap (男) / kha (女)", audioFile: null, scenario: "泰国服务业最常用问候，男女用语后缀不同。", knowledge: "男性说「ครับ khrap」，女性说「ค่ะ kha」。结尾 particle 表示礼貌。", derived: [{ text: "สวัสดี", meaning: "你好（省略后缀，较随意）" }, { text: "ยินดีต้อนรับ", meaning: "欢迎" }] },

      // ── 早上好 ──
      { chinese: "早上好", lang: "ko", text: "좋은 아침입니다", meaning: "早上好", ipa: "tso.un a.tɕʰim.im.ni.da", katakana: "チョウン アチミムニダ", romanization: "joeun achimimnida", audioFile: null, scenario: "上午时段问候顾客或同事，酒店早餐、早班服务常用。", knowledge: "也可简说「안녕하세요」。「좋은 아침」更强调时段。", derived: [{ text: "굿모닝", meaning: "Good morning（外来语，较随意）" }] },
      { chinese: "早上好", lang: "yue", text: "早晨", meaning: "早上好", ipa: "zou2 san4", katakana: "ジョウサン", romanization: "jou2 saan4 / zou san", audioFile: null, scenario: "粤语区上午问候的标准说法，茶餐厅、酒店常用。", knowledge: "「早晨」是粤语特有表达，不是「早上好」的直接翻译，但意思相同。", derived: [{ text: "早", meaning: "早（更简短）" }, { text: "早安", meaning: "早安（书面/台湾影响）" }] },
      { chinese: "早上好", lang: "en", text: "Good morning", meaning: "早上好", ipa: "ˌɡʊd ˈmɔːrnɪŋ", katakana: "グッドモーニング", romanization: "good morning", audioFile: null, scenario: "上午至中午前的标准问候，酒店、航空、高端零售常用。", knowledge: "通常用于 12 点前。配合姓名更亲切：\"Good morning, Mr. Smith.\"", derived: [{ text: "Morning", meaning: "早（同事间随意）" }] },
      { chinese: "早上好", lang: "de", text: "Guten Morgen", meaning: "早上好", ipa: "ˈɡuːtən ˈmɔʁɡən", katakana: "グーテンモルゲン", romanization: "Guten Morgen", audioFile: null, scenario: "上午正式问候，通常至 10–11 点。", knowledge: "德国服务业非常注重时段问候。10 点后逐渐改用 Guten Tag。", derived: [{ text: "Morgen", meaning: "早（同事间）" }] },
      { chinese: "早上好", lang: "fr", text: "Bonjour", meaning: "早上好 / 日安", ipa: "bɔ̃.ʒuʁ", katakana: "ボンジュール", romanization: "bonjour", audioFile: null, scenario: "法语中全天通用，上午同样使用 Bonjour。", knowledge: "法国不区分「早上好」的专用词，Bonjour 涵盖上午至傍晚。", derived: [{ text: "Bonne matinée", meaning: "祝您上午愉快（告别时用）" }] },
      { chinese: "早上好", lang: "es", text: "Buenos días", meaning: "早上好", ipa: "ˈbwe.nos ˈdi.as", katakana: "ブエノスディアス", romanization: "buenos días", audioFile: null, scenario: "上午至约 14 点前的标准问候。", knowledge: "字面意为「美好的日子」。西班牙与拉美通用。", derived: [{ text: "¿Cómo amaneció?", meaning: "今天过得怎么样？（拉美，较亲切）" }] },
      { chinese: "早上好", lang: "it", text: "Buongiorno", meaning: "早上好 / 日安", ipa: "ˌbwɔnˈdʒɔr.no", katakana: "ボンジョルノ", romanization: "buongiorno", audioFile: null, scenario: "上午至下午前的问候，咖啡吧、酒店早餐常用。", knowledge: "约 17 点后改用 Buonasera。", derived: [{ text: "Buona giornata", meaning: "祝您有美好的一天（告别时）" }] },
      { chinese: "早上好", lang: "ru", text: "Доброе утро", meaning: "早上好", ipa: "ˈdob.rə.je ˈu.trə", katakana: "ドーブラエウートラ", romanization: "dobroe utro", audioFile: null, scenario: "上午问候，酒店、餐厅早班服务。", knowledge: "中性形式，对任何人可用。约 10–11 点后改用 Добрый день。", derived: [{ text: "Доброе утро, чем могу помочь?", meaning: "早上好，有什么可以帮您？" }] },
      { chinese: "早上好", lang: "ar", text: "صباح الخير", meaning: "早上好", ipa: "sˤa.baːħ al.xajr", katakana: "サバーハルハイル", romanization: "sabāḥ al-khayr", audioFile: null, scenario: "上午问候，回应为「صباح النور ṣabāḥ an-nūr」。", knowledge: "字面意为「美好的早晨」。海湾国家服务业通用。", derived: [{ text: "صباح النور", meaning: "光明的早晨（回问候）" }] },
      { chinese: "早上好", lang: "th", text: "สวัสดีตอนเช้าครับ/ค่ะ", meaning: "早上好", ipa: "sa.wat.diː tɔn.tɕʰaːw kʰrap̚/kʰa", katakana: "サワッディートンチャオクラップ/カー", romanization: "sawatdi ton chao khrap/kha", audioFile: null, scenario: "强调早晨时段的问候，比单纯「สวัสดี」更明确。", knowledge: "日常也可只说「สวัสดี」。加「ตอนเช้า」强调时间。", derived: [{ text: "อรุณสวัสดิ์", meaning: "早安（书面/正式）" }] },

      // ── 欢迎光临 ──
      { chinese: "欢迎光临", lang: "ko", text: "어서 오세요", meaning: "欢迎光临", ipa: "ʌ.sʌ o.se.jo", katakana: "オソオセヨ", romanization: "eoseo oseyo", audioFile: null, scenario: "顾客进店时的标准欢迎语，零售、餐厅通用。", knowledge: "「어서」有「请快」之意，「오세요」是「请来的」敬语。语气热情但不夸张。", derived: [{ text: "환영합니다", meaning: "欢迎（更正式，活动/会议）" }, { text: "어서 들어오세요", meaning: "请进" }] },
      { chinese: "欢迎光临", lang: "yue", text: "欢迎光临", meaning: "欢迎光临", ipa: "fun1 jing4 gwong1 lam4", katakana: "ファンイェンクァンリャム", romanization: "fun1 jing4 gwong1 lam4", audioFile: null, scenario: "港澳及广东零售业标准欢迎语，进店时由店员说出。", knowledge: "源自普通话，粤语区服务业广泛使用。也可说「欢迎」。", derived: [{ text: "请入嚟", meaning: "请进来（更口语）" }, { text: "随便睇", meaning: "随便看看" }] },
      { chinese: "欢迎光临", lang: "en", text: "Welcome", meaning: "欢迎光临", ipa: "ˈwɛlkəm", katakana: "ウェルカム", romanization: "welcome", audioFile: null, scenario: "顾客进入店铺、酒店、餐厅时的标准欢迎。", knowledge: "可扩展为 \"Welcome to [store name]\" 或 \"Welcome, how can I help you?\"", derived: [{ text: "Welcome in", meaning: "欢迎进来（英式）" }, { text: "Right this way", meaning: "这边请" }] },
      { chinese: "欢迎光临", lang: "de", text: "Herzlich willkommen", meaning: "热烈欢迎", ipa: "ˈhɛʁts.lɪç ˈvɪl.kɔ.mən", katakana: "ヘルツリッヒヴィルコメン", romanization: "Herzlich willkommen", audioFile: null, scenario: "酒店、餐厅、活动接待的标准欢迎语。", knowledge: "简短版可用 \"Willkommen\"。 Herzlich 加强「衷心」之意。", derived: [{ text: "Willkommen in unserem Geschäft", meaning: "欢迎光临本店" }] },
      { chinese: "欢迎光临", lang: "fr", text: "Bienvenue", meaning: "欢迎", ipa: "bjɛ̃.və.ny", katakana: "ビアンヴニュ", romanization: "bienvenue", audioFile: null, scenario: "迎接顾客进入店铺或场所。", knowledge: "注意发音：最后的 ue 要清晰。配合手势引导效果更佳。", derived: [{ text: "Soyez les bienvenus", meaning: "欢迎各位（复数）" }, { text: "Entrez, je vous en prie", meaning: "请进" }] },
      { chinese: "欢迎光临", lang: "es", text: "Bienvenido/a", meaning: "欢迎", ipa: "bjen.be.ˈni.ðo/ða", katakana: "ビエンベニード/ビエンベニーダ", romanization: "bienvenido (男) / bienvenida (女)", audioFile: null, scenario: "迎接顾客，需注意阴阳性。对多人用 Bienvenidos。", knowledge: "酒店常用 \"Bienvenido a [hotel name]\"。", derived: [{ text: "Pase, por favor", meaning: "请进" }, { text: "Adelante", meaning: "请（进来）" }] },
      { chinese: "欢迎光临", lang: "it", text: "Benvenuto/a", meaning: "欢迎", ipa: "ben.veˈnu.to/ta", katakana: "ベンヴェヌート/ベンヴェヌータ", romanization: "benvenuto (男) / benvenuta (女)", audioFile: null, scenario: "迎接顾客进入商店、餐厅。", knowledge: "对女顾客用 benvenuta，男顾客用 benvenuto，不确定时用 benvenuti（复数）。", derived: [{ text: "Benvenuti", meaning: "欢迎各位" }, { text: "Prego, entri pure", meaning: "请进" }] },
      { chinese: "欢迎光临", lang: "ru", text: "Добро пожаловать", meaning: "欢迎", ipa: "ˌdob.rə pə.ʐɨˈlɑ.vətʲ", katakana: "ドーブラパジャルーヴァチ", romanization: "dobro pozhalovat'", audioFile: null, scenario: "酒店、餐厅、商店迎接顾客的标准用语。", knowledge: "也可用于「欢迎再来」。语气热情、正式。", derived: [{ text: "Проходите, пожалуйста", meaning: "请进" }, { text: "Рады вас видеть", meaning: "很高兴见到您" }] },
      { chinese: "欢迎光临", lang: "ar", text: "أهلاً وسهلاً", meaning: "欢迎", ipa: "ʔah.lan wa sah.lan", katakana: "アフランワサフラン", romanization: "ahlan wa sahlan", audioFile: null, scenario: "阿拉伯国家店铺、酒店迎接客人的热情表达。", knowledge: "字面含「你像家人一样容易相处」之意。可单独说「أهلاً ahlan」。", derived: [{ text: "مرحباً بكم", meaning: "欢迎各位" }, { text: "تفضل", meaning: "请 / 请进" }] },
      { chinese: "欢迎光临", lang: "th", text: "ยินดีต้อนรับครับ/ค่ะ", meaning: "欢迎", ipa: "jin.diː tɔːn.rap̚ kʰrap̚/kʰa", katakana: "インディートンハップクラップ/カー", romanization: "yin di ton rap khrap/kha", audioFile: null, scenario: "酒店、商场、餐厅迎接客人的正式欢迎语。", knowledge: "「ยินดี」= 高兴，「ต้อนรับ」= 迎接。合意为「很高兴迎接您」。", derived: [{ text: "เชิญค่ะ/ครับ", meaning: "请（进）" }, { text: "เข้ามาได้เลย", meaning: "请随便进来" }] },

      // ── 请稍等 ──
      { chinese: "请稍等", lang: "ko", text: "잠시만 기다려 주세요", meaning: "请稍等一下", ipa: "dʑam.ɕi.man ki.dʌ.ɾʲʌ ju.se.jo", katakana: "チャムシマン キドリョ ジュセヨ", romanization: "jamsiman gidaryeo juseyo", audioFile: null, scenario: "顾客等待时、去取货或查询时使用。", knowledge: "「잠시만」= 一会儿，「기다려 주세요」= 请等待。比「기다리세요」更礼貌。", derived: [{ text: "조금만 기다려 주세요", meaning: "请再等一下" }, { text: "금방 갖다 드릴게요", meaning: "马上给您拿来" }] },
      { chinese: "请稍等", lang: "yue", text: "请稍等", meaning: "请稍等", ipa: "cing2 saau2 dang2", katakana: "チンサウダン", romanization: "cing2 saau2 dang2", audioFile: null, scenario: "顾客需要等待时使用，如去取货、查询库存。", knowledge: "口语也说「等阵」或「请等一下」。「稍等」较正式。", derived: [{ text: "等阵", meaning: "等一下（口语）" }, { text: "即刻返嚟", meaning: "马上回来" }] },
      { chinese: "请稍等", lang: "en", text: "One moment, please", meaning: "请稍等", ipa: "wʌn ˈmoʊmənt pliːz", katakana: "ワンモーメントプリーズ", romanization: "one moment, please", audioFile: null, scenario: "处理请求前让顾客等待，电话、柜台均适用。", knowledge: "也可以说 \"Just a moment\" 或 \"Please hold\"。保持语气 calm 和 professional。", derived: [{ text: "I'll be right with you", meaning: "马上为您服务" }, { text: "Please bear with me", meaning: "请包涵稍候" }] },
      { chinese: "请稍等", lang: "de", text: "Einen Moment, bitte", meaning: "请稍等", ipa: "ˈaɪnən moˈmɛnt ˈbɪtə", katakana: "アイネンモーメントビッテ", romanization: "Einen Moment, bitte", audioFile: null, scenario: "顾客等待时使用，查询或取货前说明。", knowledge: "也可以说 \"Bitte warten Sie einen Moment\"。bitte 表示请。", derived: [{ text: "Ich bin gleich zurück", meaning: "我马上回来" }, { text: "Einen Augenblick", meaning: "请稍等（稍正式）" }] },
      { chinese: "请稍等", lang: "fr", text: "Un instant, s'il vous plaît", meaning: "请稍等", ipa: "œ̃.n‿ɛs.tɑ̃ sil vu plɛ", katakana: "アンエスタンシルヴプレ", romanization: "un instant, s'il vous plaît", audioFile: null, scenario: "服务过程中需要顾客等待时使用。", knowledge: "对年轻人可用 \"Un instant, s'il te plaît\"。保持 eye contact。", derived: [{ text: "Je reviens tout de suite", meaning: "我马上回来" }, { text: "Veuillez patienter", meaning: "请耐心等待（较正式）" }] },
      { chinese: "请稍等", lang: "es", text: "Un momento, por favor", meaning: "请稍等", ipa: "un moˈmen.to poɾ faˈβoɾ", katakana: "ウンモメントポルファボール", romanization: "un momento, por favor", audioFile: null, scenario: "取货、查询、处理付款前使用。", knowledge: "也可以说 \"Espere un momento, por favor\"。por favor 不可省略。", derived: [{ text: "Enseguida regreso", meaning: "我马上回来" }, { text: "Aguarde, por favor", meaning: "请等候（拉美常用）" }] },
      { chinese: "请稍等", lang: "it", text: "Un attimo, per favore", meaning: "请稍等", ipa: "un ˈat.ti.mo per ˈfa.vo.re", katakana: "ウンアッティモペルファヴォーレ", romanization: "un attimo, per favore", audioFile: null, scenario: "需要短暂离开或查询时使用。", knowledge: "attimo 意为「一瞬间」。也可以说 \"Un momento, per favore\"。", derived: [{ text: "Torno subito", meaning: "马上回来" }, { text: "La prego di attendere", meaning: "请您稍候（正式）" }] },
      { chinese: "请稍等", lang: "ru", text: "Одну минуту, пожалуйста", meaning: "请稍等", ipa: "ˈod.nu mʲɪˈnu.tu pə.ʐɑlˈsta", katakana: "オドヌミヌートゥポジャルスタ", romanization: "odnu minutu, pozhaluysta", audioFile: null, scenario: "服务中需要顾客等待时使用。", knowledge: "也可以说 \"Минуточку, пожалуйста\"（稍随意）。пожалуйста = 请。", derived: [{ text: "Сейчас вернусь", meaning: "马上回来" }, { text: "Подождите, пожалуйста", meaning: "请等一下" }] },
      { chinese: "请稍等", lang: "ar", text: "لحظة من فضلك", meaning: "请稍等", ipa: "laħ.za min fad.lik", katakana: "ラハザミンファドリク", romanization: "lahẓa min faḍlik", audioFile: null, scenario: "处理请求前请顾客等待。", knowledge: "对男性用 فضلك，对女性用 فضلِك。也可以说「انتظر من فضلك」。", derived: [{ text: "سأعود حالاً", meaning: "我马上回来" }, { text: "دقيقة واحدة", meaning: "一分钟" }] },
      { chinese: "请稍等", lang: "th", text: "รอสักครู่ครับ/ค่ะ", meaning: "请稍等", ipa: "rɔː sàk.kʰrùː kʰrap̚/kʰa", katakana: "ローサッククルークラップ/カー", romanization: "ro sak khu khrap/kha", audioFile: null, scenario: "取货、查询、处理事务前使用。", knowledge: "「สักครู่」= 一会儿。也可以说「กรุณารอสักครู่」更正式。", derived: [{ text: "เดี๋ยวกลับมา", meaning: "马上回来" }, { text: "ขอเวลาสักครู่", meaning: "请给我一点时间" }] },

      // ── 这边请 ──
      { chinese: "这边请", lang: "ko", text: "이쪽으로 오세요", meaning: "请往这边走", ipa: "i.tɕ͡ok.kkʌ.ro o.se.jo", katakana: "イジョッケロ オセヨ", romanization: "ijjogeuro oseyo", audioFile: null, scenario: "引导顾客入座、前往座位或指定区域时使用。", knowledge: "配合手势指向方向。也可以说「이리 오세요」（请到这边来）。", derived: [{ text: "앉으세요", meaning: "请坐" }, { text: "따라오세요", meaning: "请跟我来" }] },
      { chinese: "这边请", lang: "yue", text: "呢边请", meaning: "这边请", ipa: "ni1 bin1 cing2", katakana: "ニービンチン", romanization: "ni1 bin1 cing2 / ni bin cheng", audioFile: null, scenario: "引导顾客入座或前往指定位置。", knowledge: "「呢边」= 这边，「请」= 请。配合手势使用。", derived: [{ text: "请坐", meaning: "请坐" }, { text: "跟我嚟", meaning: "跟我来" }] },
      { chinese: "这边请", lang: "en", text: "This way, please", meaning: "这边请", ipa: "ðɪs weɪ pliːz", katakana: "ディスウェイプリーズ", romanization: "this way, please", audioFile: null, scenario: "引导顾客到座位、房间或指定区域。", knowledge: "也可以说 \"Right this way\" 或 \"Follow me, please\"。配合手势和微笑。", derived: [{ text: "Please have a seat", meaning: "请坐" }, { text: "After you", meaning: "您先请" }] },
      { chinese: "这边请", lang: "de", text: "Bitte hier entlang", meaning: "请这边走", ipa: "ˈbɪtə hiːɐ̯ ɛntˈlaŋ", katakana: "ビッテヒーアエントラン", romanization: "Bitte hier entlang", audioFile: null, scenario: "引导顾客前往座位或区域。", knowledge: "也可以说 \"Kommen Sie bitte mit\"（请跟我来）。", derived: [{ text: "Bitte nehmen Sie Platz", meaning: "请入座" }, { text: "Geradeaus", meaning: "直走" }] },
      { chinese: "这边请", lang: "fr", text: "Par ici, s'il vous plaît", meaning: "请这边走", ipa: "paʁ i.si sil vu plɛ", katakana: "パリーシシルヴプレ", romanization: "par ici, s'il vous plaît", audioFile: null, scenario: "引导顾客入座或前往指定位置。", knowledge: "也可以说 \"Suivez-moi, s'il vous plaît\"（请跟我来）。", derived: [{ text: "Asseyez-vous, je vous en prie", meaning: "请坐" }, { text: "Par là", meaning: "往那边" }] },
      { chinese: "这边请", lang: "es", text: "Por aquí, por favor", meaning: "请这边走", ipa: "poɾ aˈki poɾ faˈβoɾ", katakana: "ポルアキーポルファボール", romanization: "por aquí, por favor", audioFile: null, scenario: "引导顾客到座位或区域。", knowledge: "也可以说 \"Sígame, por favor\"（请跟我来）。", derived: [{ text: "Tome asiento, por favor", meaning: "请坐" }, { text: "Adelante", meaning: "请（往前走）" }] },
      { chinese: "这边请", lang: "it", text: "Da questa parte, per favore", meaning: "请这边走", ipa: "da ˈkwesta ˈparte per ˈfa.vo.re", katakana: "ダクエスタパルテペルファヴォーレ", romanization: "da questa parte, per favore", audioFile: null, scenario: "引导顾客入座或前往指定区域。", knowledge: "简短版可用 \"Di qua, prego\"。prego 有「请」之意。", derived: [{ text: "Mi segua, per favore", meaning: "请跟我来" }, { text: "Si accomodi, prego", meaning: "请坐" }] },
      { chinese: "这边请", lang: "ru", text: "Сюда, пожалуйста", meaning: "请这边走", ipa: "sʲʊˈda pə.ʐɑlˈsta", katakana: "スダポジャルスタ", romanization: "syuda, pozhaluysta", audioFile: null, scenario: "引导顾客到座位或指定位置。", knowledge: "也可以说 \"Прошу сюда\" 或 \"За мной, пожалуйста\"（请跟我来）。", derived: [{ text: "Присаживайтесь", meaning: "请坐" }, { text: "Прямо", meaning: "直走" }] },
      { chinese: "这边请", lang: "ar", text: "تفضل من هنا", meaning: "请这边走", ipa: "tafaḍ.dal min haː.naː", katakana: "タファッダルミンハナー", romanization: "tafaḍḍal min huna", audioFile: null, scenario: "引导客人前往座位或区域。", knowledge: "「تفضل tafaḍḍal」本身有「请」之意，男女通用。", derived: [{ text: "اتبعني", meaning: "请跟我来" }, { text: "تفضل بالجلوس", meaning: "请坐" }] },
      { chinese: "这边请", lang: "th", text: "ทางนี้ครับ/ค่ะ", meaning: "这边请", ipa: "tʰaːŋ niː kʰrap̚/kʰa", katakana: "タンニークラップ/カー", romanization: "thang ni khrap/kha", audioFile: null, scenario: "引导顾客前往座位或区域。", knowledge: "也可以说「เชิญทางนี้」（请走这边，更正式）。", derived: [{ text: "ตามมาครับ/ค่ะ", meaning: "请跟我来" }, { text: "เชิญนั่ง", meaning: "请坐" }] },

      // ── 请慢用 ──
      { chinese: "请慢用", lang: "ko", text: "맛있게 드세요", meaning: "请慢用 / 请好好享用", ipa: "ma.sit.kke deu.se.jo", katakana: "マシッケ ドゥセヨ", romanization: "masitge deuseyo", audioFile: null, scenario: "上菜后或顾客用餐开始时使用。", knowledge: "字面意为「请美味地吃」。韩国餐厅最常用服务用语之一。", derived: [{ text: "잘 드세요", meaning: "请慢用（稍随意）" }, { text: "천천히 드세요", meaning: "请慢慢吃" }] },
      { chinese: "请慢用", lang: "yue", text: "慢慢食", meaning: "请慢用", ipa: "maan6 maan6 sik6", katakana: "マーンマーンシック", romanization: "maan6 maan6 sik6 / maan maan sik", audioFile: null, scenario: "上菜后告知顾客慢慢享用，茶餐厅、酒楼常用。", knowledge: "粤语特有表达，直译「慢慢吃」。也可说「请慢用」。", derived: [{ text: "请慢用", meaning: "请慢用（普通话借词）" }, { text: "趁热食", meaning: "趁热吃" }] },
      { chinese: "请慢用", lang: "en", text: "Enjoy your meal", meaning: "请慢用", ipa: "ɪnˈdʒɔɪ jɔːr miːl", katakana: "エンジョイユアミール", romanization: "enjoy your meal", audioFile: null, scenario: "上菜后或顾客开始用餐时使用。", knowledge: "美式也常说 \"Enjoy!\" 简短版。语气自然、温暖。", derived: [{ text: "Bon appétit", meaning: "请慢用（法语借词，高端餐厅）" }, { text: "Please take your time", meaning: "请慢慢享用" }] },
      { chinese: "请慢用", lang: "de", text: "Guten Appetit", meaning: "祝您用餐愉快", ipa: "ˈɡuːtən ˌapəˈtiː", katakana: "グーテンアペティート", romanization: "Guten Appetit", audioFile: null, scenario: "上菜后祝顾客用餐愉快。", knowledge: "德国用餐文化重要用语。也可说 \"Essen Sie schön\"（请好好吃）。", derived: [{ text: "Lassen Sie es sich schmecken", meaning: "请慢慢品尝" }, { text: "Prost", meaning: "干杯（饮品时）" }] },
      { chinese: "请慢用", lang: "fr", text: "Bon appétit", meaning: "请慢用", ipa: "bɔ̃‿na.pe.ti", katakana: "ボナペティ", romanization: "bon appétit", audioFile: null, scenario: "上菜后标准用语，全球法语餐厅通用。", knowledge: "注意连读发音。即使非法语餐厅，高端场合也常用。", derived: [{ text: "Je vous souhaite un bon appétit", meaning: "祝您用餐愉快（更正式）" }] },
      { chinese: "请慢用", lang: "es", text: "Buen provecho", meaning: "请慢用", ipa: "bwen proˈβetʃo", katakana: "ブエンプロベーチョ", romanization: "buen provecho", audioFile: null, scenario: "上菜后或用餐开始时的祝福。", knowledge: "拉丁美洲通用。也可以说 \"Que aproveche\"（祝您吃得满意）。", derived: [{ text: "Disfrute su comida", meaning: "请享用您的餐点" }] },
      { chinese: "请慢用", lang: "it", text: "Buon appetito", meaning: "请慢用", ipa: "ˌbwɔn ap.peˈti.to", katakana: "ボーナペッティート", romanization: "buon appetito", audioFile: null, scenario: "上菜后祝顾客用餐愉快。", knowledge: "意大利用餐礼仪重要用语。上菜时说出表示关怀。", derived: [{ text: "Si gusti", meaning: "请品尝（较正式）" }] },
      { chinese: "请慢用", lang: "ru", text: "Приятного аппетита", meaning: "祝您用餐愉快", ipa: "prʲɪˈyat.nə.və ɐp.pʲɪˈtʲi.ta", katakana: "プリヤートナヴァアッペティータ", romanization: "priyatnogo appetita", audioFile: null, scenario: "上菜后祝顾客用餐愉快。", knowledge: "俄罗斯用餐文化标准用语。对多人同样适用。", derived: [{ text: "Кушайте на здоровье", meaning: "请慢用（直译：吃着健康）" }] },
      { chinese: "请慢用", lang: "ar", text: "بالهناء والشفاء", meaning: "祝您用餐愉快", ipa: "bil.hanaːʔ waʃ.ʃifaːʔ", katakana: "ビルハナー ワッシファー", romanization: "bil-hana' wash-shifa'", audioFile: null, scenario: "上菜后祝福顾客，意为「愿您享受并健康」。", knowledge: "也可说「تفضل بالأكل tafaḍḍal bil-akl」（请用餐）。", derived: [{ text: "صحة وعافية", meaning: "健康与福祉" }] },
      { chinese: "请慢用", lang: "th", text: "ทานให้อร่อยนะครับ/ค่ะ", meaning: "请慢用 / 请好好吃", ipa: "tʰaːn hâi a.rɔ̀j na kʰrap̚/kʰa", katakana: "タンハイアロイナクラップ/カー", romanization: "than hai a-roi na khrap/kha", audioFile: null, scenario: "上菜后祝顾客用餐愉快。", knowledge: "「อร่อย a-roi」= 美味。语气亲切，泰国餐厅极常用。", derived: [{ text: "เชิญทาน", meaning: "请用餐" }, { text: "ทานเลย", meaning: "请吃吧" }] },

      // ── 非常感谢 ──
      { chinese: "非常感谢", lang: "ko", text: "대단히 감사합니다", meaning: "非常感谢", ipa: "tɛ.dan.hi kam.sa.ham.ni.da", katakana: "テダンヒ カムサハムニダ", romanization: "daedanhi gamsahamnida", audioFile: null, scenario: "收到顾客感谢后的回应，或向顾客表达深切谢意。", knowledge: "比「감사합니다」程度更深。对顾客帮助、投诉后和解时使用。", derived: [{ text: "정말 감사합니다", meaning: "真的非常感谢" }, { text: "감사합니다", meaning: "谢谢" }] },
      { chinese: "非常感谢", lang: "yue", text: "非常感谢", meaning: "非常感谢", ipa: "faai3 cyun4 gam2 zaa6", katakana: "ファイーチュンガムジャー", romanization: "faai3 cyun4 gam2 zaa6", audioFile: null, scenario: "向顾客表达诚挚感谢，如投诉处理后、收到好评。", knowledge: "也可说「好多次谢」或「多谢晒」。「非常感谢」较正式。", derived: [{ text: "多谢", meaning: "谢谢" }, { text: "唔该", meaning: "谢谢 / 麻烦了" }] },
      { chinese: "非常感谢", lang: "en", text: "Thank you very much", meaning: "非常感谢", ipa: "θæŋk ju ˈvɛri mʌtʃ", katakana: "サンキューベリーマッチ", romanization: "thank you very much", audioFile: null, scenario: "向顾客表达真诚感谢，如完成服务、收到小费。", knowledge: "也可以说 \"Thank you so much\" 或 \"I really appreciate it\"。", derived: [{ text: "Thanks a lot", meaning: "多谢（较随意）" }, { text: "Much appreciated", meaning: "非常感激" }] },
      { chinese: "非常感谢", lang: "de", text: "Vielen Dank", meaning: "非常感谢", ipa: "ˈfiːlən daŋk", katakana: "フィーレンダンク", romanization: "Vielen Dank", audioFile: null, scenario: "向顾客表达感谢。", knowledge: "更强调可用 \"Herzlichen Dank\"（衷心感谢）。", derived: [{ text: "Danke schön", meaning: "谢谢" }, { text: "Ich danke Ihnen", meaning: "我感谢您（正式）" }] },
      { chinese: "非常感谢", lang: "fr", text: "Merci beaucoup", meaning: "非常感谢", ipa: "mɛʁ.si bo.ku", katakana: "メルシーボクー", romanization: "merci beaucoup", audioFile: null, scenario: "向顾客表达感谢。", knowledge: "beaucoup = 很多。更正式可用 \"Je vous remercie\"（我感谢您）。", derived: [{ text: "Merci infiniment", meaning: "无限感谢" }, { text: "Merci", meaning: "谢谢" }] },
      { chinese: "非常感谢", lang: "es", text: "Muchas gracias", meaning: "非常感谢", ipa: "ˈmu.tʃas ˈɡra.sjas", katakana: "ムチャスグラシアス", romanization: "muchas gracias", audioFile: null, scenario: "向顾客表达感谢。", knowledge: "也可以说 \"Le agradezco mucho\"（我非常感激您，更正式）。", derived: [{ text: "Mil gracias", meaning: "千谢（强调）" }, { text: "Gracias", meaning: "谢谢" }] },
      { chinese: "非常感谢", lang: "it", text: "Grazie mille", meaning: "非常感谢", ipa: "ˈɡrat.tsi.e ˈmil.le", katakana: "グラツィエミッレ", romanization: "grazie mille", audioFile: null, scenario: "向顾客表达感谢。", knowledge: "mille = 一千，意为「千谢」。也可以说 \"La ringrazio molto\"（正式）。", derived: [{ text: "Grazie di cuore", meaning: "衷心感谢" }, { text: "Grazie", meaning: "谢谢" }] },
      { chinese: "非常感谢", lang: "ru", text: "Большое спасибо", meaning: "非常感谢", ipa: "bɐlʲˈʂo.jɪ spɐˈsʲi.bə", katakana: "ボリショエスパシーバ", romanization: "bol'shoye spasibo", audioFile: null, scenario: "向顾客表达感谢。", knowledge: "большое = 大的/很多的。也可以说 \"Огромное спасибо\"（巨大感谢）。", derived: [{ text: "Спасибо", meaning: "谢谢" }, { text: "Благодарю вас", meaning: "我感谢您（正式）" }] },
      { chinese: "非常感谢", lang: "ar", text: "شكراً جزيلاً", meaning: "非常感谢", ipa: "ʃuk.ran d͡ʒa.ziː.lan", katakana: "シュクランジャズィーラン", romanization: "shukran jazilan", audioFile: null, scenario: "向客人表达感谢。", knowledge: "也可以说 \"شكراً لك shukran lak\"（谢谢你）。 جزيلاً = 大量的。", derived: [{ text: "شكراً", meaning: "谢谢" }, { text: "أشكرك", meaning: "我感谢你" }] },
      { chinese: "非常感谢", lang: "th", text: "ขอบคุณมากครับ/ค่ะ", meaning: "非常感谢", ipa: "kʰɔ̀p kʰun maːk kʰrap̚/kʰa", katakana: "コップクンマークラップ/カー", romanization: "khop khun mak khrap/kha", audioFile: null, scenario: "向顾客表达感谢。", knowledge: "「มาก mak」= 很多。也可以说「ขอบใจมาก」较随意。", derived: [{ text: "ขอบคุณครับ/ค่ะ", meaning: "谢谢" }, { text: "ขอบใจ", meaning: "谢谢（较随意）" }] },

      // ── 不客气 ──
      { chinese: "不客气", lang: "ko", text: "천만에요", meaning: "不客气", ipa: "tɕʰʌn.man.e.jo", katakana: "チョンマネヨ", romanization: "cheonmaneyo", audioFile: null, scenario: "回应顾客感谢时使用。", knowledge: "也可以说「별말씀을요」（哪里的话）。两者均表示「不必客气」。", derived: [{ text: "아닙니다", meaning: "不是的 / 不客气" }, { text: "도와드릴게요", meaning: "我来帮您" }] },
      { chinese: "不客气", lang: "yue", text: "唔使客氣", meaning: "不用客气", ipa: "m4 sai2 haak3 hei3", katakana: "ムーサイハーキー", romanization: "m4 sai2 haak3 hei3", audioFile: null, scenario: "回应顾客感谢时使用。", knowledge: "也可以说「唔该」或「应分嘅」。粤语中「唔使」= 不用。", derived: [{ text: "唔该", meaning: "不客气 / 谢谢" }, { text: "好小事啫", meaning: "小事一桩" }] },
      { chinese: "不客气", lang: "en", text: "You're welcome", meaning: "不客气", ipa: "jʊr ˈwɛlkəm", katakana: "ユアウェルカム", romanization: "you're welcome", audioFile: null, scenario: "回应顾客感谢的标准用语。", knowledge: "也可以说 \"My pleasure\"、\"No problem\" 或 \"Happy to help\"。", derived: [{ text: "It's my pleasure", meaning: "这是我的荣幸" }, { text: "Anytime", meaning: "随时效劳" }] },
      { chinese: "不客气", lang: "de", text: "Bitte schön", meaning: "不客气", ipa: "ˈbɪtə ʃøːn", katakana: "ビッテショーン", romanization: "Bitte schön", audioFile: null, scenario: "回应顾客感谢时使用。", knowledge: "也可以说 \"Gern geschehen\"（乐意效劳）或 \"Kein Problem\"。", derived: [{ text: "Nichts zu danken", meaning: "不必谢" }, { text: "Gerne", meaning: "乐意" }] },
      { chinese: "不客气", lang: "fr", text: "Je vous en prie", meaning: "不客气 / 请别客气", ipa: "ʒə vu.z‿ɑ̃ pʁi", katakana: "ジュヴーザンプリ", romanization: "je vous en prie", audioFile: null, scenario: "回应顾客感谢时使用。", knowledge: "也可以说 \"De rien\"（没什么）或 \"Avec plaisir\"（很乐意）。", derived: [{ text: "C'est normal", meaning: "这是应该的" }, { text: "Pas de quoi", meaning: "不客气（较随意）" }] },
      { chinese: "不客气", lang: "es", text: "De nada", meaning: "不客气", ipa: "de ˈna.ða", katakana: "デナダ", romanization: "de nada", audioFile: null, scenario: "回应顾客感谢时使用。", knowledge: "也可以说 \"Con mucho gusto\"（非常乐意）或 \"No hay de qué\"。", derived: [{ text: "Es un placer", meaning: "这是我的荣幸" }, { text: "Para servirle", meaning: "乐意效劳" }] },
      { chinese: "不客气", lang: "it", text: "Prego", meaning: "不客气 / 请", ipa: "ˈpre.ɡo", katakana: "プレーゴ", romanization: "prego", audioFile: null, scenario: "回应感谢或表示「请」的多用途词。", knowledge: "意大利语「prego」既可回应感谢，也可表示「请」。", derived: [{ text: "Di niente", meaning: "没什么" }, { text: "Figurati", meaning: "别客气（较随意）" }] },
      { chinese: "不客气", lang: "ru", text: "Пожалуйста", meaning: "不客气 / 请", ipa: "pə.ʐɑlˈsta", katakana: "ポジャルスタ", romanization: "pozhaluysta", audioFile: null, scenario: "回应感谢时使用（也可表示「请」）。", knowledge: "俄语中「请」和「不客气」用同一词。根据语境区分。", derived: [{ text: "Не за что", meaning: "没什么（回应感谢）" }, { text: "Всегда рад помочь", meaning: "随时乐意帮忙" }] },
      { chinese: "不客气", lang: "ar", text: "عفواً", meaning: "不客气", ipa: "ʕaf.wan", katakana: "アフワン", romanization: "afwan", audioFile: null, scenario: "回应客人感谢时使用。", knowledge: "也可以说「لا شكر على واجب」（不用谢，分内之事）。", derived: [{ text: "العفو", meaning: "不客气" }, { text: "على الرحب والسعة", meaning: "别客气" }] },
      { chinese: "不客气", lang: "th", text: "ไม่เป็นไรครับ/ค่ะ", meaning: "不客气 / 没关系", ipa: "mâj pen raj kʰrap̚/kʰa", katakana: "マイペンライクラップ/カー", romanization: "mai pen rai khrap/kha", audioFile: null, scenario: "回应顾客感谢时使用。", knowledge: "泰国文化中「mai pen rai」含义广泛：不客气、没关系、没问题。", derived: [{ text: "ยินดีครับ/ค่ะ", meaning: "乐意效劳" }, { text: "ด้วยความยินดี", meaning: "非常乐意" }] },

      // ── 请慢走 ──
      { chinese: "请慢走", lang: "ko", text: "조심히 가세요", meaning: "请慢走 / 路上小心", ipa: "tso.ɕim.hi ka.se.jo", katakana: "チョシムヒ ガセヨ", romanization: "joshimhi gaseyo", audioFile: null, scenario: "送别顾客时使用，表达关心。", knowledge: "字面意为「请小心地走」。韩国送别标准用语。", derived: [{ text: "안녕히 가세요", meaning: "再见（您走好）" }, { text: "다음에 또 오세요", meaning: "欢迎下次再来" }] },
      { chinese: "请慢走", lang: "yue", text: "慢慢行", meaning: "请慢走", ipa: "maan6 maan6 haang4", katakana: "マーンマーンハーン", romanization: "maan6 maan6 haang4", audioFile: null, scenario: "送别顾客时使用。", knowledge: "「行 haang4」= 走。与「慢慢食」对仗，一送一迎。", derived: [{ text: "再见", meaning: "再见" }, { text: "下次再嚟", meaning: "下次再来" }] },
      { chinese: "请慢走", lang: "en", text: "Take care", meaning: "请慢走 / 保重", ipa: "teɪk kɛr", katakana: "テイクケア", romanization: "take care", audioFile: null, scenario: "送别顾客时使用，表达关心。", knowledge: "也可以说 \"Have a nice day\" 或 \"Safe travels\"。", derived: [{ text: "Have a good evening", meaning: "祝您有个美好的夜晚" }, { text: "See you again", meaning: "再见" }] },
      { chinese: "请慢走", lang: "de", text: "Kommen Sie gut nach Hause", meaning: "请平安回家", ipa: "ˈkɔmən ziː ɡuːt naːx ˈhaʊzə", katakana: "コメンジーグートナッハハウゼ", romanization: "Kommen Sie gut nach Hause", audioFile: null, scenario: "送别顾客时使用。", knowledge: "简短版可用 \"Auf Wiedersehen\"（再见）或 \"Tschüss\"（非正式）。", derived: [{ text: "Einen schönen Abend", meaning: "祝您晚上愉快" }, { text: "Bis bald", meaning: "回头见" }] },
      { chinese: "请慢走", lang: "fr", text: "Bonne continuation", meaning: "祝您一切顺利", ipa: "bɔn kɔ̃.ti.nɥa.sjɔ̃", katakana: "ボンコントニュアシオン", romanization: "bonne continuation", audioFile: null, scenario: "送别顾客时使用。", knowledge: "也可以说 \"Bonne journée\"（祝您有美好的一天）或 \"Au revoir\"（再见）。", derived: [{ text: "À bientôt", meaning: "回头见" }, { text: "Bon voyage", meaning: "一路平安" }] },
      { chinese: "请慢走", lang: "es", text: "Que le vaya bien", meaning: "祝您一切顺利", ipa: "ke le ˈba.a ˈbjen", katakana: "ケレバイアビエン", romanization: "que le vaya bien", audioFile: null, scenario: "送别顾客时使用。", knowledge: "也可以说 \"Cuídese\"（保重）或 \"Hasta luego\"（回头见）。", derived: [{ text: "Que tenga un buen día", meaning: "祝您有美好的一天" }, { text: "Vuelva pronto", meaning: "欢迎再来" }] },
      { chinese: "请慢走", lang: "it", text: "Arrivederci e buona giornata", meaning: "再见，祝您有美好的一天", ipa: "ar.ri.veˈder.tʃi e ˈbwɔ.na dʒorˈna.ta", katakana: "アリヴェデルチ エ ボーナジョルナータ", romanization: "arrivederci e buona giornata", audioFile: null, scenario: "送别顾客时使用。", knowledge: "简短版可用 \"Arrivederci\"（再见）或 \"Buona serata\"（晚上用）。", derived: [{ text: "Torni presto", meaning: "欢迎再来" }, { text: "Stia bene", meaning: "保重" }] },
      { chinese: "请慢走", lang: "ru", text: "Счастливого пути", meaning: "祝您一路平安", ipa: "ʂɐsʲˈlʲi.və.və ˈputʲɪ", katakana: "スチスリーヴァヴァプーティ", romanization: "schastlivogo puti", audioFile: null, scenario: "送别顾客时使用。", knowledge: "也可以说 \"До свидания\"（再见）或 \"Всего доброго\"（祝您一切顺利）。", derived: [{ text: "Приходите ещё", meaning: "欢迎再来" }, { text: "Берегите себя", meaning: "保重" }] },
      { chinese: "请慢走", lang: "ar", text: "مع السلامة", meaning: "请慢走 / 一路平安", ipa: "maʕa‿s.sa.laː.ma", katakana: "マアッサラーマ", romanization: "ma'a as-salama", audioFile: null, scenario: "送别客人时使用，意为「带着平安」。", knowledge: "对留下的人说「في أمان الله fī amān Allāh」。此语用于送别离开的人。", derived: [{ text: "إلى اللقاء", meaning: "再见" }, { text: "نراك قريباً", meaning: "回头见" }] },
      { chinese: "请慢走", lang: "th", text: "เดินทางปลอดภัยนะครับ/ค่ะ", meaning: "请一路平安", ipa: "dɤːn tʰaːŋ plɔ̀t.pʰaj na kʰrap̚/kʰa", katakana: "ドンタンポロッパイナクラップ/カー", romanization: "doen thang plot phai na khrap/kha", audioFile: null, scenario: "送别顾客时使用。", knowledge: "也可以说「ลาก่อน」（再见）或「ไว้เจอกันใหม่」（下次见）。", derived: [{ text: "ขอให้โชคดี", meaning: "祝您好运" }, { text: "มาใหม่นะ", meaning: "欢迎再来" }] },

      // ── 再见 ──
      { chinese: "再见", lang: "ko", text: "안녕히 가세요", meaning: "再见（您走好）", ipa: "an.njʌŋ.hi ka.se.jo", katakana: "アンニョンヒ ガセヨ", romanization: "annyeonghi gaseyo", audioFile: null, scenario: "送别离开的顾客时使用。说话者留下。", knowledge: "若自己离开则说「안녕히 계세요」（您留步）。方向性不同。", derived: [{ text: "다음에 뵙겠습니다", meaning: "下次见（正式）" }, { text: "또 봐요", meaning: "再见（较随意）" }] },
      { chinese: "再见", lang: "yue", text: "再见", meaning: "再见", ipa: "zoi3 gin3", katakana: "ジョイギン", romanization: "zoi3 gin3 / joi gin", audioFile: null, scenario: "送别顾客时使用。", knowledge: "粤语口语也说「拜拜」。「再见」正式且通用。", derived: [{ text: "拜拜", meaning: "拜拜（口语）" }, { text: "下次见", meaning: "下次见" }] },
      { chinese: "再见", lang: "en", text: "Goodbye", meaning: "再见", ipa: "ˌɡʊdˈbaɪ", katakana: "グッバイ", romanization: "goodbye", audioFile: null, scenario: "送别顾客时使用。", knowledge: "服务业更常用 \"Have a nice day\" 或 \"See you next time\" 更温暖。", derived: [{ text: "See you soon", meaning: "回头见" }, { text: "Have a great day", meaning: "祝您有美好的一天" }] },
      { chinese: "再见", lang: "de", text: "Auf Wiedersehen", meaning: "再见", ipa: "aʊf ˈviːdɐˌzeːən", katakana: "アウフヴィーダーゼーエン", romanization: "Auf Wiedersehen", audioFile: null, scenario: "正式送别用语。", knowledge: "非正式用 \"Tschüss\" 或 \"Bis bald\"（回头见）。", derived: [{ text: "Auf Wiederhören", meaning: "再见（电话用语）" }, { text: "Bis zum nächsten Mal", meaning: "下次见" }] },
      { chinese: "再见", lang: "fr", text: "Au revoir", meaning: "再见", ipa: "o ʁə.vwaʁ", katakana: "オルヴォワール", romanization: "au revoir", audioFile: null, scenario: "送别顾客的标准用语。", knowledge: "也可以说 \"À bientôt\"（回头见）或 \"Bonne soirée\"（祝您晚上愉快）。", derived: [{ text: "À la prochaine", meaning: "下次见" }, { text: "Bonne journée", meaning: "祝您有美好的一天" }] },
      { chinese: "再见", lang: "es", text: "Adiós", meaning: "再见", ipa: "aˈðjos", katakana: "アディオス", romanization: "adiós", audioFile: null, scenario: "送别顾客时使用。", knowledge: "日常更常用 \"Hasta luego\"（回头见）或 \"Que tenga un buen día\"。", derived: [{ text: "Hasta pronto", meaning: "回头见" }, { text: "Nos vemos", meaning: "再见（较随意）" }] },
      { chinese: "再见", lang: "it", text: "Arrivederci", meaning: "再见", ipa: "ar.ri.veˈder.tʃi", katakana: "アリヴェデルチ", romanization: "arrivederci", audioFile: null, scenario: "送别顾客的标准用语。", knowledge: "非正式用 \"Ciao\"。正式场合用 \"Arrivederci\" 或 \"ArrivederLa\"（更敬）。", derived: [{ text: "A presto", meaning: "回头见" }, { text: "Buona giornata", meaning: "祝您有美好的一天" }] },
      { chinese: "再见", lang: "ru", text: "До свидания", meaning: "再见", ipa: "də svʲɪˈda.nʲə", katakana: "ドスヴィダーニヤ", romanization: "do svidaniya", audioFile: null, scenario: "送别顾客的标准用语。", knowledge: "非正式用 \"Пока\"（口语）。对顾客保持 \"До свидания\"。", derived: [{ text: "Всего хорошего", meaning: "祝您一切顺利" }, { text: "Увидимся", meaning: "回头见" }] },
      { chinese: "再见", lang: "ar", text: "وداعاً", meaning: "再见", ipa: "wa.daː.an", katakana: "ワダーアン", romanization: "wada'an", audioFile: null, scenario: "送别客人时使用。", knowledge: "也可以说「مع السلامة ma'a as-salama」（一路平安）或「إلى اللقاء ila al-liqa'」（后会有期）。", derived: [{ text: "في أمان الله", meaning: "愿上帝保佑您" }, { text: "إلى اللقاء", meaning: "后会有期" }] },
      { chinese: "再见", lang: "th", text: "ลาก่อนครับ/ค่ะ", meaning: "再见", ipa: "laː kɔ̀n kʰrap̚/kʰa", katakana: "ラーコーンクラップ/カー", romanization: "la kon khrap/kha", audioFile: null, scenario: "送别顾客时使用。", knowledge: "「ลาก่อน」= 再见。也可以说「แล้วเจอกัน」（回头见）。", derived: [{ text: "แล้วเจอกันใหม่", meaning: "下次见" }, { text: "ไว้คุยกันใหม่", meaning: "再聊" }] }
    ];
